Repository woocommerce/google-listings-and-ads, pull requests merged in 2021-08, with the labels that each got.

#925 Add filter to allow overriding all product attributes
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: enhancement

#934 Handle all loading states within the `PhoneNumberCard` component
  js/src/components/contact-information/index.js
  js/src/components/contact-information/phone-number-card.js
  js/src/hooks/useGoogleMCPhoneNumber.js
Labels: category: refactor

#941 Trim product descriptions to 5000 characters
  src/Polyfills/MBString.php
  src/Polyfills/bootstrap.php
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: bug

#942 Add root files and directories to version replace path
  .gitignore
  package.json
Labels: type: enhancement

#948 Fix pre sync errors being skipped in the issues table
  src/MerchantCenter/MerchantStatuses.php
Labels: type: bug

#955 Silently log exception when checking MC contact info
  src/MerchantCenter/MerchantCenterService.php
  src/Notes/ContactInformation.php
Labels: type: bug

#958 Add DB migration and remove an unneccesary index from merchant_issues table
  src/DB/Installer.php
  src/DB/Migration/AbstractMigration.php
  src/DB/Migration/MigrationInterface.php
  src/DB/Migration/MigrationVersion141.php
  src/DB/Migration/Migrator.php
  src/DB/Table.php
  src/DB/Table/MerchantIssueTable.php
  src/DB/TableInterface.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/DBServiceProvider.php
  tests/Unit/DB/Migration/MigratorTest.php
Labels: type: bug

#959 Add integration with WooCommerce Pre Orders extension
  src/Integration/WooCommercePreOrders.php
  src/Internal/DependencyManagement/IntegrationServiceProvider.php
  src/Product/ProductHelper.php
  src/Product/WCProductAdapter.php
Labels: type: enhancement
