Repository woocommerce/google-listings-and-ads, pull requests merged in 2021-07, with the labels that each got.

#828 Add unit test configurations
  .travis.yml
  README.md
  bin/install-wp-tests.sh
  composer.json
  package.json
  phpcs.xml.dist
  phpunit.xml.dist
  tests/Unit/Assets/AdminScriptAssetTest.php
  tests/Unit/Product/BatchProductHelperTest.php
  tests/bootstrap.php
  tests/wp-function-stubs.php
Labels: type: technical debt

#846 Add unit tests for BatchProductHelper and ProductFactory
  src/Exception/InvalidClass.php
  src/Exception/ValidateInterface.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/AbstractProductSyncerBatchedJob.php
  src/Jobs/AbstractProductSyncerJob.php
  src/Jobs/ProductSyncerJobInterface.php
  src/Product/BatchProductHelper.php
  src/Product/ProductFactory.php
  src/Product/ProductHelper.php
  src/Product/ProductSyncer.php
  src/Product/SyncerHooks.php
  src/Product/WCProductAdapter.php
  tests/Framework/ContainerAwareUnitTest.php
  tests/Framework/UnitTest.php
  tests/Tools/HelperTrait/ProductMetaTrait.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Tools/HelperTrait/SettingsTrait.php
  tests/Unit/Product/BatchProductHelperTest.php
  tests/Unit/Product/ProductFactoryTest.php
Labels: type: technical debt

#854 Add unit tests for ProductHelper and ProductMetaHandler
  src/Product/ProductMetaHandler.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/ProductMetaHandlerTest.php
Labels: type: technical debt

#855 Add unit tests for ProductRepository
  src/Product/ProductRepository.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Product/ProductRepositoryTest.php
Labels: type: technical debt

#865 Create test products manually instead of using a provider
  tests/Unit/Product/BatchProductHelperTest.php
Labels: type: technical debt

#869 Set `CI_BRANCH_BASE` for `bundlewatch` on push events
  .travis.yml
  package.json
Labels: priority: low, type: enhancement

#868 Add unit tests for AttributeManager and AbstractAttribute
  src/Product/Attributes/Adult.php
  src/Product/Attributes/AgeGroup.php
  src/Product/Attributes/AttributeInterface.php
  src/Product/Attributes/AttributeManager.php
  src/Product/Attributes/Brand.php
  src/Product/Attributes/Color.php
  src/Product/Attributes/Condition.php
  src/Product/Attributes/GTIN.php
  src/Product/Attributes/Gender.php
  src/Product/Attributes/IsBundle.php
  src/Product/Attributes/MPN.php
  src/Product/Attributes/Material.php
  src/Product/Attributes/Multipack.php
  src/Product/Attributes/Pattern.php
  src/Product/Attributes/Size.php
  src/Product/Attributes/SizeSystem.php
  src/Product/Attributes/SizeType.php
  tests/Unit/Product/Attributes/AbstractAttributeTest.php
  tests/Unit/Product/Attributes/AttributeManagerTest.php
Labels: type: technical debt

#874 Add unit tests for WCProductAdapter
  src/Exception/InvalidValue.php
  src/Product/ProductSyncer.php
  src/Product/WCProductAdapter.php
  tests/Tools/HelperTrait/DataTrait.php
  tests/Tools/HelperTrait/ProductMetaTrait.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Tools/HelperTrait/SettingsTrait.php
  tests/Unit/Product/BatchProductHelperTest.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/WCProductAdapterTest.php
  tests/bootstrap.php
  tests/data/test-image-1.png
  tests/data/test-image-2.png
Labels: type: technical debt

#856 Add unit tests for functions within `.~/data/utils.js`
  js/src/data/utils.js
  js/src/data/utils.test.js
Labels: type: technical debt

#866 Add unit tests for functions within `.~/reports/utils.js`
  js/src/reports/utils.js
  js/src/reports/utils.test.js
Labels: type: technical debt

#871 Fix some edge cases and add unit tests for `checkErrors` function
  js/src/components/free-listings/configure-product-listings/__snapshots__/checkErrors.test.js.snap
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
Labels: type: technical debt

#880 Don't sync invisible products to MC
  js/src/product-attributes/index.scss
  src/Admin/MetaBox/ChannelVisibilityMetaBox.php
  src/DB/ProductFeedQueryHelper.php
  src/HelperTraits/ViewHelperTrait.php
  src/Product/ProductHelper.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/SyncerHooksTest.php
  views/meta-box/channel_visibility.php
Labels: type: enhancement

#892 Optionally clean up plugin data on uninstall
  src/DB/Installer.php
  src/DB/Table.php
  src/DB/Table/BudgetRecommendationTable.php
  src/DB/Table/MerchantIssueTable.php
  src/DB/Table/ShippingRateTable.php
  src/DB/Table/ShippingTimeTable.php
  src/DB/TableManager.php
  src/Integration/WooCommerceProductBundles.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Options/Options.php
  src/Options/OptionsInterface.php
  src/Options/Transients.php
  src/Options/TransientsInterface.php
  src/PluginHelper.php
  src/Product/Attributes/AttributeManager.php
  src/Product/ProductMetaHandler.php
  uninstall.php
Labels: type: enhancement

#899 Fix Switch URL flow, import `Button` from `/components`
  js/src/setup-mc/setup-stepper/setup-accounts/google-mc-account/switch-url-card/index.js
Labels: type: bug

#894 Skip orphaned variations instead of throwing errors when syncing products
  src/API/Site/Controllers/MerchantCenter/IssuesController.php
  src/API/Site/Controllers/MerchantCenter/ProductVisibilityController.php
  src/Admin/MetaBox/ChannelVisibilityMetaBox.php
  src/Product/BatchProductHelper.php
  src/Product/ProductFactory.php
  src/Product/ProductHelper.php
  src/Proxies/WC.php
  tests/Unit/Product/ProductHelperTest.php
  uninstall.php
Labels: priority: high, type: bug

#905 Allow safe HTML tags for product descriptions
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: enhancement

#909 Check if fetched Google ids is an array before processing
  src/MerchantCenter/MerchantStatuses.php
Labels: type: bug

#911 Add filter to optionally apply shortcodes in product descriptions
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: enhancement

#919 Add API endpoints to update and fetch contact information
  src/API/Google/Settings.php
  src/API/Site/Controllers/MerchantCenter/ContactInformationController.php
  src/API/Site/Controllers/MerchantCenter/PhoneNumberController.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/MerchantCenter/ContactInformation.php
  src/MerchantCenter/MerchantVerification.php
  src/Utility/AddressUtility.php
  tests/Tools/HelperTrait/MerchantTrait.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ContactInformationControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/PhoneNumberControllerTest.php
  tests/Unit/MerchantCenter/ContactInformationTest.php
  tests/Unit/MerchantCenter/MerchantVerificationTest.php
  tests/Unit/Utility/AddressUtilityTest.php
Labels: type: enhancement
