Repository woocommerce/google-listings-and-ads, pull requests merged in 2021-11, with the labels that each got.

#1073 Avoid including a nodejs library to reduce the index.js bundle size by 42%
  package-lock.json
  package.json
  webpack.config.js
Labels: type: technical debt - dependency extraction

#1023 Retry Action Scheduler jobs on timeout
  src/ActionScheduler/ActionScheduler.php
  src/ActionScheduler/ActionSchedulerInterface.php
  src/Jobs/AbstractActionSchedulerJob.php
  src/Jobs/AbstractBatchedActionSchedulerJob.php
  src/Jobs/ActionSchedulerJobMonitor.php
  src/Jobs/UpdateAllProducts.php
Labels: type: enhancement

#1082 Use task list API for checking if we should show tasks list.
  google-listings-and-ads.php
  readme.txt
  src/TaskList/TaskListTrait.php
Labels: type: technical debt

#1081 Update `in_stock` and `out_of_stock` availability enums
  src/Product/WCProductAdapter.php
Labels: type: enhancement

#1092 Add name and domain to account API to facilitate UX improvements
  src/API/Google/Proxy.php
  src/API/Site/Controllers/MerchantCenter/AccountController.php
  src/ConnectionTest.php
Labels: merchant center

#1095 Adding setup & testing documentation and update deprecated attribute
  README.md
Labels: priority: low, type: documentation
