Repository woocommerce/google-listings-and-ads, pull requests merged in 2021-09, with the labels that each got.

#992 Fetch the product from DB when hooking to create product actions
  src/Product/SyncerHooks.php
Labels: type: bug

#1010 Clean up `Note` classes
  src/Notes/CompleteSetup.php
  src/Notes/ContactInformation.php
  src/Notes/Note.php
  src/Notes/SetupCampaign.php
  src/Notes/SetupCampaignTwoWeeks.php
Labels: category: refactor

#998 Add phone verification service
  composer.json
  composer.lock
  src/API/Google/Merchant.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/MerchantCenter/PhoneVerification.php
  src/MerchantCenter/PhoneVerificationException.php
  src/Proxies/WP.php
  src/Utility/ISOUtility.php
  src/Value/PhoneNumber.php
  tests/Unit/API/Google/MerchantTest.php
  tests/Unit/MerchantCenter/PhoneVerificationTest.php
  tests/Unit/Utility/ISOUtilityTest.php
  tests/Unit/Value/PhoneNumberTest.php
Labels: type: enhancement

#991 Add unit tests for PHPView and DateTimeUtility
  src/Infrastructure/ViewFactory.php
  src/Utility/DateTimeUtility.php
  src/View/PHPViewFactory.php
  tests/Unit/Utility/DateTimeUtilityTest.php
  tests/Unit/View/PHPViewFactoryTest.php
  tests/Unit/View/PHPViewTest.php
  tests/data/test-php-view-partial.php
  tests/data/test-php-view.php
Labels: type: enhancement

#1015 Replace "Wordpress.com" with "WordPress.com"
  js/src/settings/disconnect-accounts/index.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
Labels: type: bug

#1017 Phone Verification: Refactor ContactInformation Service and API
  src/API/Site/Controllers/MerchantCenter/ContactInformationController.php
  src/MerchantCenter/ContactInformation.php
  tests/Unit/MerchantCenter/ContactInformationTest.php
Labels: type: enhancement

#1006 Add phone verification API endpoints
  src/API/Site/Controllers/MerchantCenter/ContactInformationController.php
  src/API/Site/Controllers/MerchantCenter/PhoneVerificationController.php
  src/API/Site/Controllers/MerchantCenter/ReportsController.php
  src/API/Site/Controllers/ResponseFromExceptionTrait.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/MerchantCenter/PhoneVerification.php
  src/MerchantCenter/PhoneVerificationException.php
  tests/Framework/RESTControllerUnitTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/PhoneVerificationControllerTest.php
  tests/Unit/MerchantCenter/PhoneVerificationTest.php
  tests/bootstrap.php
Labels: type: enhancement

#1026 Limit the number of addtional product images
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: enhancement

#1025 Separate Phone and Address settings
  js/src/components/account-card/index.js
  js/src/components/contact-information/contact-information-preview-card.js
  js/src/components/contact-information/contact-information-preview-card.scss
  js/src/components/contact-information/index.js
  js/src/components/contact-information/no-contact-information-card.js
  js/src/components/contact-information/no-contact-information-card.scss
  js/src/components/contact-information/phone-number-card/index.js
  js/src/components/contact-information/phone-number-card/phone-number-card-preview.js
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  js/src/components/contact-information/store-address-card.js
  js/src/components/contact-information/store-address-card.scss
  js/src/css/abstracts/_mixins.scss
  js/src/settings/edit-phone-number.js
  js/src/settings/edit-store-address.js
  js/src/settings/index.js
  js/src/utils/urls.js
  src/MerchantCenter/MerchantCenterService.php
  src/Notes/ContactInformation.php
  src/PluginHelper.php
  src/Tracking/README.md
Labels: type: technical debt - external devX
