Repository woocommerce/google-listings-and-ads, pull requests merged in 2021-06, with the labels that each got.

#780 Add the missing second parameter deps for all usages of `useSelect`
  .eslintrc
  js/src/components/free-listings/configure-product-listings/useSettings.js
  js/src/dashboard/summary-section/usePerformance.js
  js/src/hooks/useAdminUrl.js
  js/src/hooks/useCountryKeyNameMap.js
  js/src/hooks/useExistingGoogleAdsAccounts.js
  js/src/hooks/useExistingGoogleMCAccounts.js
  js/src/hooks/useGetCountries.js
  js/src/hooks/useGoogleAdsAccount.js
  js/src/hooks/useGoogleAdsAccountBillingStatus.js
  js/src/hooks/useShippingRates.js
  js/src/hooks/useShippingTimes.js
  js/src/hooks/useStoreCountry.js
  js/src/hooks/useTargetAudience.js
  js/src/hooks/useTargetAudienceFinalCountryCodes.js
  js/src/reports/products/products-report-filters.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/add-rate-button/add-rate-modal/useGetRemainingCountryCodes.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/add-time-button/add-time-modal/useGetRemainingCountryCodes.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/index.js
Labels: category: refactor, type: technical debt

#783 Check if product description is not empty before using it
  src/Product/WCProductAdapter.php
Labels: type: bug

#785 Strip shortcodes used in product description before sync
  src/Product/WCProductAdapter.php
Labels: type: bug

#791 Add shipping for all target audience countries
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Product/BatchProductHelper.php
  src/Product/WCProductAdapter.php
Labels: type: enhancement

#797 Use a constant batch size (100) for update all product job
  src/Jobs/AbstractBatchedActionSchedulerJob.php
  src/Jobs/UpdateAllProducts.php
Labels: type: enhancement

#800 Prevent conflicts in channel visibility meta box form
  src/Admin/MetaBox/AbstractMetaBox.php
  src/Admin/MetaBox/ChannelVisibilityMetaBox.php
  src/HelperTraits/ViewHelperTrait.php
  src/Product/SyncerHooks.php
  views/meta-box/channel_visibility.php
Labels: priority: high, type: bug

#753 Use WooCommerce CRUD class methods to handle metadata
  src/Google/GlobalSiteTag.php
  src/Integration/YoastWooCommerceSeo.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Product/Attributes/AttributeManager.php
  src/Product/ProductMetaHandler.php
Labels: type: technical debt

#788 Guzzle Conflict with other plugins
  bin/prefix-vendor-namespace.php
  composer.json
  src/API/Google/ApiExceptionTrait.php
  src/API/Google/Connection.php
  src/API/Google/Proxy.php
  src/Google/Ads/GoogleAdsClient.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/Requirements/PluginValidator.php
  src/Internal/Requirements/WCBookingsValidator.php
Labels: priority: critical

#696 Update deprecated `stylelint-config-wordpress` to `@wordpress/stylelint-config@19.0.4`,
  .stylelintrc
  package-lock.json
  package.json
Labels: priority: low, type: technical debt

#809 Don't use order in product query by default
  src/Product/ProductRepository.php
Labels: type: enhancement

#820 Update travis config to use latest version of WP and WC
  .travis.yml
Labels: type: technical debt
