Repository woocommerce/google-listings-and-ads, pull requests merged in 2021-12, with the labels that each got.

#1110 Update min. WC version to 5.7 (L-2).
  README.md
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: type: technical debt, type: technical debt - dependency extraction

#1144 Shipping Integration - Pre-fill shipping rates
  src/API/Site/Controllers/MerchantCenter/ShippingRateBatchController.php
  src/API/Site/Controllers/MerchantCenter/ShippingRateController.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Proxies/WC.php
  src/Shipping/ShippingZone.php
  tests/Unit/Shipping/ShippingZoneTest.php
Labels: type: enhancement

#1107 Add a script to report outdated externalized dependencies.
  .externalized.json
  package-lock.json
  package.json
  webpack.config.js
Labels: type: technical debt, type: technical debt - dependency extraction

#1162 Create new instance of query instead of using shared object
  src/API/Site/Controllers/MerchantCenter/ShippingRateController.php
Labels: type: bug, priority: high

#1160 Code refactor: Change `useShippingRates` and `useShippingTimes` to use `useAppSelectDispatch`
  js/src/edit-free-campaign/index.js
  js/src/hooks/useShippingRates.js
  js/src/hooks/useShippingTimes.js
Labels: type: technical debt

#1164 Remove WC's `is_ajax` (deprecated in 6.1) in favor of proxied WP `wp_doing_ajax`
  src/Admin/ActivationRedirect.php
  src/Admin/BulkEdit/CouponBulkEdit.php
  src/Installer.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Proxies/WP.php
Labels: type: technical debt
