Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-08, with the labels that each got.

#1613 Update PR template, recommend `changelog: none` label,
  .github/PULL_REQUEST_TEMPLATE.md
Labels: changelog: none

#1615 Revert campaign name suffix
  src/API/Google/AdsReport.php
  src/API/Site/Controllers/Ads/CampaignController.php
  tests/Unit/API/Google/AdsReportTest.php
  tests/Unit/API/Site/Controllers/Ads/CampaignControllerTest.php
Labels: changelog: none

#1614 PMax Milestone 2
  js/src/components/campaign-conversion-notice/conversion-statuses.js
  js/src/components/campaign-conversion-notice/index.js
  js/src/components/campaign-conversion-notice/index.scss
  js/src/components/campaign-conversion-notice/index.test.js
  js/src/components/campaign-conversion-notice/reports-notice.js
  js/src/components/campaign-conversion-notice/reports-notice.scss
  js/src/components/campaign-conversion-notice/reports-notice.test.js
  js/src/components/dismissible-notice/index.js
  js/src/components/dismissible-notice/index.test.js
  js/src/constants.js
  js/src/dashboard/index.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useAdsCampaigns.js
  js/src/reports/programs/campaign-name-cell.js
  js/src/reports/programs/campaign-name-cell.scss
  js/src/reports/programs/campaign-name-cell.test.js
  js/src/reports/programs/compare-programs-table-card.js
  js/src/reports/programs/index.js
  js/src/reports/programs/programs-report-filters.js
  js/src/utils/getConversionCampaignStatusNotice.js
  js/src/utils/getConversionCampaignStatusNotice.test.js
  js/src/utils/urls.js
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsReport.php
  src/API/Google/Query/AdsCampaignReportQuery.php
  src/API/Site/Controllers/Ads/CampaignController.php
  src/API/Site/Controllers/Ads/ReportsController.php
  src/Admin/Admin.php
  src/Ads/AccountService.php
  src/Ads/AdsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Notes/AfterCampaignMigration.php
  src/Notes/BeforeCampaignMigration.php
  src/Options/OptionsInterface.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsCampaignTest.php
  tests/Unit/API/Google/AdsReportTest.php
  tests/Unit/API/Site/Controllers/Ads/CampaignControllerTest.php
  tests/Unit/Ads/AccountServiceTest.php
  tests/Unit/Ads/AdsServiceTest.php
  tests/Unit/Notes/AfterCampaignMigrationTest.php
  tests/Unit/Notes/BeforeCampaignMigrationTest.php
  tests/mocks/ads/reports/programs.json
  tests/proxy/mocks/ads/reports/programs.json
Labels: changelog: none

#1617 Fix `doc~s~` typo in `release.yml`, add `type: documentation`
  .github/release.yml
Labels: changelog: none

#1627 Test - Set default timeout
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/utils/track-event.js
Labels: changelog: none

#1616 Free Listings + Paid Ads: Combine the audience and shipping steps
  .eslintrc.js
  js/src/components/free-listings/choose-audience-section/choose-audience-section.js
  js/src/components/free-listings/choose-audience-section/choose-audience-section.scss
  js/src/components/free-listings/choose-audience-section/index.js
  js/src/components/free-listings/choose-audience/index.js
  js/src/components/free-listings/choose-audience/index.scss
  js/src/components/free-listings/configure-product-listings/__snapshots__/checkErrors.test.js.snap
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/edit-free-campaign/index.js
  js/src/hooks/useDebouncedCallbackEffect.js
  js/src/setup-mc/setup-stepper/choose-audience/form-content.js
  js/src/setup-mc/setup-stepper/choose-audience/index.js
  js/src/setup-mc/setup-stepper/choose-audience/useAutoClearShippingEffect.js
  js/src/setup-mc/setup-stepper/choose-audience/useAutoSaveTargetAudienceEffect.js
  js/src/setup-mc/setup-stepper/choose-audience/useAutoSaveTargetAudienceEffect.test.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/setup-stepper/setup-free-listings/form-content.js
  js/src/setup-mc/setup-stepper/setup-free-listings/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time-section.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/add-time-button/add-time-modal/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/add-time-button/add-time-modal/useGetRemainingCountryCodes.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/add-time-button/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/countriesTimeInput.test.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input-form/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/edit-time-modal/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/index.scss
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input/index.scss
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/getCountriesTimeArray.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/index.scss
  js/src/setup-mc/setup-stepper/setup-free-listings/useAutoSaveSettingsEffect.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useAutoSaveSettingsEffect.test.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useAutoSaveShippingRatesEffect.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useSaveSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useShippingRatesSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useShippingRatesSuggestions.test.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useShippingRatesWithSavedSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useShippingRatesWithSavedSuggestions.test.js
  js/src/setup-mc/setup-stepper/stepNameKeyMap.js
  js/src/setup-mc/setup-stepper/useTargetAudienceWithSuggestions.js
  package-lock.json
  package.json
Labels: changelog: update

#1618 Free Listings + Paid Ads: UI updates for get started page and onboarding flow
  jest.config.js
  js/src/components/account-card/google-ads-logo.svg
  js/src/components/account-card/google-merchant-center-logo.svg
  js/src/components/account-card/index.js
  js/src/components/contact-information/index.js
  js/src/components/contact-information/phone-number-card/phone-number-card.scss
  js/src/components/contact-information/store-address-card.scss
  js/src/components/free-listings/choose-audience-section/choose-audience-section.js
  js/src/components/free-listings/configure-product-listings/hero/google-free-listing.png
  js/src/components/free-listings/configure-product-listings/hero/google-free-listing.svg
  js/src/components/free-listings/configure-product-listings/hero/index.js
  js/src/components/free-listings/configure-product-listings/hero/index.scss
  js/src/components/google-mc-account-card/create-account-card.js
  js/src/components/google-mc-account-card/disabled-card.js
  js/src/components/shipping-rate-section/shipping-rate-section.js
  js/src/components/stepper/step-content-header/index.js
  js/src/components/stepper/step-content-header/index.scss
  js/src/components/vertical-gap-layout/index.js
  js/src/components/vertical-gap-layout/index.scss
  js/src/get-started-page/customer-quotes-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.scss
  js/src/setup-mc/setup-stepper/setup-accounts/google-mc-account/index.js
  js/src/setup-mc/setup-stepper/setup-accounts/google-mc-account/index.scss
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
  js/src/wcdl/section/index.scss
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/mocks/assets/imageMock.js
Labels: changelog: update

#1619 Free Listings + Paid Ads: Add step 4 to the onboarding flow
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/index.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/setup-mc/setup-stepper/stepNameKeyMap.js
  js/src/setup-mc/setup-stepper/store-requirements/index.js
  js/src/utils/urls.js
  src/MerchantCenter/MerchantCenterService.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
Labels: changelog: none

#1629 E2E Fix for redirecting to single product page.
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/utils/visit-product-page.js
Labels: type: bug, changelog: fix

#1628 Remove wc-admin installation from E2E env setup
  tests/e2e/docker/initialize.sh
Labels: changelog: dev

#1602 Hook for handling multiple errors for rejected promises
  js/src/edit-free-campaign/index.js
  js/src/utils/createErrorMessageForRejectedPromises.js
  js/src/utils/createErrorMessageForRejectedPromises.test.js
  js/src/utils/createMessageForMultipleErrors.js
  js/src/utils/createMessageForMultipleErrors.test.js
Labels: type: bug, changelog: fix

#1626 Use visibility:hidden to hide the element but preserving offset
  js/src/css/shared/_woocommerce-admin.scss
Labels: type: bug, changelog: fix

#1631 Onload conflict when tracking events
  js/src/gtag-events/index.js
Labels: type: bug, changelog: fix

#1634 Release 2.0.4
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1635 Release/2.0.4
  changelog.txt
  google-listings-and-ads.php
  js/src/css/shared/_woocommerce-admin.scss
  js/src/edit-free-campaign/index.js
  js/src/gtag-events/index.js
  js/src/utils/createErrorMessageForRejectedPromises.js
  js/src/utils/createErrorMessageForRejectedPromises.test.js
  js/src/utils/createMessageForMultipleErrors.js
  js/src/utils/createMessageForMultipleErrors.test.js
  package-lock.json
  package.json
  readme.txt
  tests/e2e/docker/initialize.sh
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/utils/track-event.js
  tests/e2e/utils/visit-product-page.js
Labels: changelog: none

#1638 Free Listings + Paid Ads: Add the product feed status section UI
  js/src/data/actions.js
  js/src/data/selectors.js
  js/src/product-feed/product-statistics/status-box/sync-status.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.scss
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/utils/getNumberOfSyncProducts.js
Labels: changelog: none

#1642 Fix a compatibility issue with WC 6.5+ that the store country might be `undefined` and further break the onboarding setup
  js/src/hooks/useStoreCountry.js
  tests/unit/wc-admin-dependency.test.js
Labels: type: bug, changelog: fix

#1624 Run PHPCS checks for unit tests
  .github/workflows/php-coding-standards.yml
  package.json
  tests/Framework/RESTControllerUnitTest.php
  tests/Tools/HelperTrait/CouponTrait.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Tools/HelperTrait/MerchantTrait.php
  tests/Tools/HelperTrait/ProductMetaTrait.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsCampaignTest.php
  tests/Unit/API/Google/AdsReportTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
  tests/Unit/API/Google/MerchantTest.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/API/Google/SiteVerificationTest.php
  tests/Unit/API/Site/Controllers/Ads/AccountControllerTest.php
  tests/Unit/API/Site/Controllers/Ads/BudgetRecommendationControllerTest.php
  tests/Unit/API/Site/Controllers/Ads/CampaignControllerTest.php
  tests/Unit/API/Site/Controllers/Google/AccountControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/AccountControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ContactInformationControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/PhoneVerificationControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/RequestReviewControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingRateControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/SupportedCountriesControllerTest.php
  tests/Unit/Ads/AccountServiceTest.php
  tests/Unit/Coupon/CouponMetaHandlerTest.php
  tests/Unit/Coupon/CouponSyncerTest.php
  tests/Unit/Coupon/SyncerHooksTest.php
  tests/Unit/Coupon/WCCouponAdapterTest.php
  tests/Unit/DB/Table/BudgetRecommendationTableTest.php
  tests/Unit/Google/GoogleHelperTest.php
  tests/Unit/Jobs/UpdateAllProductsTest.php
  tests/Unit/Jobs/UpdateProductsTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
  tests/Unit/MerchantCenter/ValidateAddressTest.php
  tests/Unit/Notes/AfterCampaignMigrationTest.php
  tests/Unit/Notes/BeforeCampaignMigrationTest.php
  tests/Unit/Product/Attributes/AttributeManagerTest.php
  tests/Unit/Product/ProductFilterTest.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/ProductMetaHandlerTest.php
  tests/Unit/Product/ProductSyncerTest.php
  tests/Unit/Product/SyncerHooksTest.php
  tests/Unit/Product/WCProductAdapterTest.php
  tests/Unit/Shipping/GoogleAdapter/DBShippingSettingsAdapterTest.php
  tests/Unit/Shipping/GoogleAdapter/PostcodesRateGroupAdapterTest.php
  tests/Unit/Shipping/GoogleAdapter/StatesRateGroupAdapterTest.php
  tests/Unit/Shipping/GoogleAdapter/WCShippingSettingsAdapterTest.php
  tests/Unit/Shipping/ServiceRatesCollectionTest.php
  tests/Unit/Shipping/ShippingZoneTest.php
  tests/Unit/Shipping/SyncerHooksTest.php
  tests/Unit/Shipping/ZoneLocationsParserTest.php
  tests/Unit/Shipping/ZoneMethodsParserTest.php
  tests/bootstrap.php
  tests/phpcs.xml.dist
Labels: changelog: dev

#1645 Release 2.1.0
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
  src/API/Google/Settings.php
  src/Google/GoogleHelper.php
  src/Jobs/UpdateShippingSettings.php
  src/Shipping/CountryRatesCollection.php
  src/Shipping/GoogleAdapter/AbstractRateGroupAdapter.php
  src/Shipping/GoogleAdapter/AbstractShippingSettingsAdapter.php
  src/Shipping/GoogleAdapter/DBShippingSettingsAdapter.php
  src/Shipping/GoogleAdapter/PostcodesRateGroupAdapter.php
  src/Shipping/GoogleAdapter/StatesRateGroupAdapter.php
  src/Shipping/GoogleAdapter/WCShippingSettingsAdapter.php
  src/Shipping/LocationRate.php
  src/Shipping/LocationRatesCollection.php
  src/Shipping/LocationRatesProcessor.php
  src/Shipping/PostcodeRange.php
  src/Shipping/ServiceRatesCollection.php
  src/Shipping/ShippingLocation.php
  src/Shipping/ShippingRate.php
  src/Shipping/ShippingRegion.php
  src/Shipping/ShippingSuggestionService.php
  src/Shipping/ShippingZone.php
  src/Shipping/SyncerHooks.php
  src/Shipping/ZoneLocationsParser.php
  src/Shipping/ZoneMethodsParser.php
Labels: changelog: none

#1653 Update Plugin Icons
  wordpress_org_assets/icon-128x128.png
  wordpress_org_assets/icon-256x256.png
  wordpress_org_assets/icon-no-bg.svg
  wordpress_org_assets/icon.svg
Labels: changelog: tweak

#1633 Add a filter to disable GTag tracking
  src/Google/GlobalSiteTag.php
Labels: changelog: tweak

#1649 Free Listings + Paid Ads: Add the boost product listings section
  js/src/components/stepper/step-content-footer/index.scss
  js/src/css/abstracts/_variables.scss
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.scss
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/wcdl/section/card/footer/index.scss
  js/src/wcdl/section/index.js
  js/src/wcdl/section/index.scss
Labels: changelog: none

#1650 Free Listings + Paid Ads: Add the paid ads previews to the boost product listings section
  .eslintrc.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.js
  js/src/components/paid-ads/campaign-preview/campaign-preview.js
  js/src/components/paid-ads/campaign-preview/campaign-preview.scss
  js/src/components/paid-ads/campaign-preview/components/placeholder.js
  js/src/components/paid-ads/campaign-preview/components/product-banner.js
  js/src/components/paid-ads/campaign-preview/components/product-cover.js
  js/src/components/paid-ads/campaign-preview/components/scaled-text.js
  js/src/components/paid-ads/campaign-preview/components/search-bar.js
  js/src/components/paid-ads/campaign-preview/components/shop-logo.js
  js/src/components/paid-ads/campaign-preview/images/ad-corner-buttons-image.svg
  js/src/components/paid-ads/campaign-preview/images/gmail-logo.svg
  js/src/components/paid-ads/campaign-preview/images/google-shopping-logo.svg
  js/src/components/paid-ads/campaign-preview/images/map-background.png
  js/src/components/paid-ads/campaign-preview/images/product-sample-image.jpg
  js/src/components/paid-ads/campaign-preview/images/shop-sample-logo.png
  js/src/components/paid-ads/campaign-preview/images/youtube-logo.svg
  js/src/components/paid-ads/campaign-preview/index.js
  js/src/components/paid-ads/campaign-preview/mockup-display.js
  js/src/components/paid-ads/campaign-preview/mockup-gmail.js
  js/src/components/paid-ads/campaign-preview/mockup-map.js
  js/src/components/paid-ads/campaign-preview/mockup-search.js
  js/src/components/paid-ads/campaign-preview/mockup-shopping.js
  js/src/components/paid-ads/campaign-preview/mockup-youtube.js
  js/src/hooks/useCountdown.js
  js/src/hooks/useCountdown.test.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.scss
  package.json
Labels: changelog: none

#1654 Free Listings + Paid Ads: Add the Google Ads account setup section
  js/src/components/account-card/index.js
  js/src/components/app-button/index.js
  js/src/components/google-ads-account-card/authorize-ads.js
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-ads-account-card/connected-google-ads-account-card.js
  js/src/components/google-ads-account-card/create-account.js
  js/src/data/actions.js
  js/src/data/resolvers.js
  js/src/settings/linked-accounts.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/google-ads-account-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
Labels: changelog: fix
