Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-01, with the labels that each got.

#1178 Update some devDependencies, `npm audit fix`
  .externalized.json
  package-lock.json
  package.json
Labels: type: technical debt

#1179 Drop support for WC 5.7 (L-3).
  README.md
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: type: technical debt, type: technical debt - dependency extraction

#1161 Pre-fill shipping rates in Setup MC
  js/src/hooks/useCallbackOnceEffect.js
  js/src/hooks/useCallbackOnceEffect.test.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/useSaveSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/useShippingRatesSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/useShippingRatesSuggestions.test.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/useShippingRatesWithSavedSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/useShippingRatesWithSavedSuggestions.test.js
Labels: type: enhancement

#1187 Fix the partial update of MC settings state in the reducer
  js/src/data/reducer.js
  js/src/data/test/reducer.test.js
Labels: priority: high

#1184 Fix the issue that all data on the report pages are not shown
  jest.config.js
  js/src/data/reducer.js
  js/src/data/test/reducer.test.js
Labels: priority: high

#1154 Map shipping classes rates
  src/API/Site/Controllers/MerchantCenter/ShippingRateController.php
  src/Product/WCProductAdapter.php
  src/Proxies/WC.php
  src/Shipping/ShippingZone.php
  tests/Unit/Shipping/ShippingZoneTest.php
Labels: type: enhancement

#1175 Shipping Integration - Shipping class rates API
  src/API/Google/Settings.php
  src/API/Site/Controllers/MerchantCenter/ShippingRateController.php
Labels: type: enhancement

#1197 Use lodash via DEWP instead of packing it to bundle files
  js/src/edit-free-campaign/index.js
  js/src/hooks/useIsEqualRefValue.js
  js/src/setup-ads/setup-ads-form.js
Labels: type: technical debt - dependency extraction

#1192 Add automatic settings for shipping rates
  src/API/Google/Settings.php
  src/API/Site/Controllers/MerchantCenter/SettingsController.php
  src/API/Site/Controllers/MerchantCenter/ShippingRateController.php
  src/Admin/BulkEdit/CouponBulkEdit.php
  src/Admin/MetaBox/CouponChannelVisibilityMetaBox.php
  src/Coupon/CouponSyncer.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/MerchantCenter/MerchantCenterService.php
  src/MerchantCenter/TargetAudience.php
  src/Product/BatchProductHelper.php
  src/Product/ProductHelper.php
  src/Shipping/ShippingZone.php
  src/Tracking/TrackerSnapshot.php
  src/Value/MerchantCenterSettings.php
  tests/Unit/Coupon/CouponSyncerTest.php
  tests/Unit/Product/BatchProductHelperTest.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/ProductSyncerTest.php
  tests/Unit/Shipping/ShippingZoneTest.php
Labels: type: enhancement

#1202 Change the shipping rate API response and request args
  src/API/Site/Controllers/MerchantCenter/ShippingRateBatchController.php
  src/API/Site/Controllers/MerchantCenter/ShippingRateController.php
  src/API/Site/Controllers/MerchantCenter/ShippingRateSuggestionsController.php
  src/API/Site/Controllers/ShippingRateSchemaTrait.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
Labels: type: enhancement

#1201 Split shipping rates and shipping times section, and add automatic shipping rates option
  js/src/components/free-listings/choose-audience/form-content.js
  js/src/components/free-listings/choose-audience/index.scss
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
  js/src/components/free-listings/configure-product-listings/combined-shipping/index.js
  js/src/components/free-listings/configure-product-listings/combined-shipping/index.scss
  js/src/components/free-listings/configure-product-listings/shipping-rate-section.js
  js/src/components/free-listings/configure-product-listings/shipping-time-section.js
  js/src/edit-free-campaign/setup-free-listings/form-content.js
  js/src/setup-mc/setup-stepper/choose-audience/form-content.js
  js/src/setup-mc/setup-stepper/setup-free-listings/combined-shipping.js
  js/src/setup-mc/setup-stepper/setup-free-listings/form-content.js
  js/src/setup-mc/setup-stepper/setup-free-listings/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate-section.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time-section.js
  js/src/wcdl/radio-helper-text/index.scss
Labels: type: enhancement, status: on hold

#1216 Update Google Ads credit incentive in WordPress.org plugin landing page
  readme.txt
Labels: priority: high

#1215 Remove free shipping options from MC settings
  src/MerchantCenter/MerchantCenterService.php
  src/Tracking/TrackerSnapshot.php
  src/Value/MerchantCenterSettings.php
Labels: type: enhancement

#1217 Update Google Ads credit incentive info in plugin UI
  js/src/components/paid-ads/budget-section/free-ad-credit/country-modal/country-amount.js
  js/src/components/paid-ads/budget-section/free-ad-credit/country-modal/index.js
  js/src/components/paid-ads/budget-section/free-ad-credit/index.js
  js/src/dashboard/summary-section/paid-campaign-promotion-card.js
  js/src/get-started-page/faqs.js
  js/src/hooks/useFreeAdCredit.js
  js/src/product-feed/submission-success-guide/index.js
Labels: priority: high
