Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-03, with the labels that each got.

#1279 Change id and name in favour of value and label
  js/src/components/tree-select-control/index.js
  js/src/components/tree-select-control/index.test.js
  js/src/components/tree-select-control/list.js
  js/src/components/tree-select-control/tags.js
  js/src/pages/component-test/index.js
Labels: component

#1262 Shipping rates UI changes: wp.data
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/test/reducer.test.js
  js/src/edit-free-campaign/index.js
  js/src/utils/isInShippingRates.js
  js/src/utils/isInShippingRates.test.js
  js/src/utils/isSameShippingRate.js
Labels: type: enhancement

#1263 Shipping rates UI changes: Remove `offers_free_shipping` and `free_shipping_threshold` settings
  js/src/components/free-listings/configure-product-listings/__snapshots__/checkErrors.test.js.snap
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
  js/src/components/free-listings/configure-product-listings/shipping-rate/shipping-rate-setup/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/index.js
  js/src/edit-free-campaign/setup-free-listings/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate-section.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/index.js
Labels: type: enhancement

#1264 Shipping rates UI changes: Better card title layout
  js/src/components/free-listings/configure-product-listings/shipping-time-section.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time-section.js
  js/src/wcdl/section/card/index.js
  js/src/wcdl/section/card/title/index.js
  js/src/wcdl/section/card/title/index.scss
Labels: type: enhancement

#1265 Shipping rates UI changes: Better SelectControl label
  js/src/components/free-listings/configure-product-listings/shipping-rate/shipping-rate-setup/add-rate-button/add-rate-modal/index.js
  js/src/components/free-listings/configure-product-listings/shipping-rate/shipping-rate-setup/countries-price-input/edit-rate-button/edit-rate-modal/index.js
  js/src/components/free-listings/configure-product-listings/shipping-rate/shipping-rate-setup/countries-price-input/edit-rate-button/edit-rate-modal/index.scss
  js/src/wcdl/select-control/index.scss
Labels: type: enhancement

#1284 Cast empty arrays to objects in APIs if property type is object.
  src/API/Site/Controllers/BaseController.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingRateControllerTest.php
Labels: type: enhancement

#1267 Shipping rates UI changes: Make Setup MC support country-level free shipping and minimum order amount
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js
  js/src/components/shipping-rate-section/minimum-order-card/groupShippingRatesByFreeShippingThreshold.js
  js/src/components/shipping-rate-section/minimum-order-card/groupShippingRatesByMethodFreeShippingThreshold.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-card.js
  js/src/hooks/useDebouncedCallbackEffect.js
  js/src/setup-mc/setup-stepper/choose-audience/useAutoClearShippingEffect.js
  js/src/setup-mc/setup-stepper/setup-free-listings/form-content.js
  js/src/setup-mc/setup-stepper/setup-free-listings/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate-section.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/add-rate-button/add-rate-modal/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/add-rate-button/add-rate-modal/useGetRemainingCountryCodes.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/add-rate-button/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/countriesPriceInput.test.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input-form/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input/edit-rate-button/edit-rate-modal/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input/edit-rate-button/edit-rate-modal/index.scss
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input/edit-rate-button/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input/edit-rate-button/index.scss
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/countries-price-input/index.scss
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/index.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/index.scss
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-rate/shipping-rate-setup/useSaveSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useAutoSaveShippingRatesEffect.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useSaveSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useShippingRatesSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useShippingRatesSuggestions.test.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useShippingRatesWithSavedSuggestions.js
  js/src/setup-mc/setup-stepper/setup-free-listings/useShippingRatesWithSavedSuggestions.test.js
Labels: type: enhancement

#1294 Select All Options in Tree Select Component
  js/src/components/tree-select-control/index.js
  js/src/components/tree-select-control/index.scss
  js/src/components/tree-select-control/index.test.js
  js/src/components/tree-select-control/options.js
  js/src/pages/component-test/index.js
Labels: component

#1282 Map Google location IDs to country codes and supported subdivision codes
  src/API/Google/Proxy.php
  src/API/Site/Controllers/MerchantCenter/SupportedCountriesController.php
  src/API/Site/Controllers/MerchantCenter/TargetAudienceController.php
  src/Google/GoogleHelper.php
  src/GoogleHelper.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/MerchantCenter/MerchantCenterService.php
  src/Shipping/ShippingZone.php
  tests/Unit/Google/GoogleHelperTest.php
  tests/Unit/Shipping/ShippingZoneTest.php
Labels: type: enhancement

#1298 Fix the current onboarding step being returned as shipping even after saving rates
  src/MerchantCenter/MerchantCenterService.php
Labels: type: bug

#1297 Shipping rates UI changes: Remove "all countries" label from shipping rate and shipping time
  js/src/components/country-names-plus-more.js
  js/src/components/free-listings/configure-product-listings/country-names.js
  js/src/components/free-listings/configure-product-listings/more.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-form.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/index.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/shipping-rate-input-control-label-text.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/shipping-rate-input-control.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-input-control-label-text.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-input-control.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-input-label-text.js
  js/src/components/shipping-time-input-control-label-text.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time/shipping-time-setup/countries-time-input/index.js
Labels: type: enhancement

#1305 Migrate free shipping threshold settings to the shipping rates table
  src/DB/Migration/Migration20211228T1640692399.php
  src/DB/Query/ShippingRateQuery.php
  src/Internal/DependencyManagement/DBServiceProvider.php
Labels: type: enhancement

#1281 Tree Select Components - Expand/collapse
  js/src/components/tree-select-control/control.js
  js/src/components/tree-select-control/control.test.js
  js/src/components/tree-select-control/index.js
  js/src/components/tree-select-control/index.scss
  js/src/components/tree-select-control/index.test.js
  js/src/components/tree-select-control/list.js
  js/src/components/tree-select-control/options.js
  js/src/components/tree-select-control/options.test.js
  js/src/pages/component-test/index.js
Labels: component

#1341 Get suggested shipping rates for provinces/states and postal codes from WC zones
  src/API/Google/Settings.php
  src/API/Site/Controllers/MerchantCenter/ShippingRateSuggestionsController.php
  src/API/Site/Controllers/ShippingRateSchemaTrait.php
  src/Google/GoogleHelper.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Shipping/Location.php
  src/Shipping/LocationRate.php
  src/Shipping/LocationRatesProcessor.php
  src/Shipping/ShippingRate.php
  src/Shipping/ShippingRateFlat.php
  src/Shipping/ShippingRateFree.php
  src/Shipping/ShippingZone.php
  src/Shipping/ZoneLocationsParser.php
  src/Shipping/ZoneMethodsParser.php
  tests/Unit/Shipping/LocationRatesProcessorTest.php
  tests/Unit/Shipping/ShippingZoneTest.php
  tests/Unit/Shipping/ZoneLocationsParserTest.php
  tests/Unit/Shipping/ZoneMethodsParserTest.php
Labels: type: enhancement

#1359 Add blurb to inform users to connect Google Ads child account and not a parent MCC account
  js/src/setup-ads/ads-stepper/setup-accounts/google-ads-account-card/connect-ads/ads-account-select-control.js
  js/src/setup-ads/ads-stepper/setup-accounts/google-ads-account-card/connect-ads/index.js
  js/src/setup-ads/ads-stepper/setup-accounts/google-ads-account-card/connect-ads/index.scss
  js/src/setup-ads/ads-stepper/setup-accounts/google-ads-account-card/non-connected.js
Labels: priority: high
