Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-07, with the labels that each got.

#1573 Add a script to generate a list of hooks that defined or used in GLA
  README.md
  bin/HooksDocsGenerator.php
  src/Hooks/README.md
Labels: type: enhancement

#1589 Add GH workflow to set PR labels
  .github/workflows/branch-labels.yml
Labels: type: enhancement, changelog: add

#1590 Fix `release.yml` syntax - add quotes.
  .github/release.yml
Labels: type: bug, changelog: none

#1591 Release/2.0.1
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release.yml
  .github/workflows/branch-labels.yml
  README.md
  bin/HooksDocsGenerator.php
  changelog.txt
  composer.json
  google-listings-and-ads.php
  js/src/data/actions.js
  js/src/edit-free-campaign/index.js
  js/src/hooks/useNavigateAwayPromptEffect.js
  js/src/setup-mc/setup-stepper/choose-audience/form-content.js
  js/src/setup-mc/setup-stepper/choose-audience/useAutoSaveTargetAudienceEffect.js
  js/src/setup-mc/setup-stepper/choose-audience/useAutoSaveTargetAudienceEffect.test.js
  package-lock.json
  package.json
  readme.txt
  src/DB/Migration/Migration20220524T1653383133.php
  src/Hooks/README.md
  src/MerchantCenter/MerchantStatuses.php
  src/Polyfills/MBString.php
  src/Polyfills/Normalizer.php
  src/Polyfills/Resources/unidata/canonicalComposition.php
  src/Polyfills/Resources/unidata/canonicalDecomposition.php
  src/Polyfills/Resources/unidata/combiningClass.php
  src/Polyfills/Resources/unidata/compatibilityDecomposition.php
  src/Polyfills/bootstrap.php
Labels: changelog: none

#1595 Disable identifier_exists field
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: bug, changelog: fix

#1597 Fixing change log records for release 2.0.1 and reverting migration file
  changelog.txt
  readme.txt
  src/DB/Migration/Migration20220524T1653383133.php
Labels: changelog: tweak

#1594 Change to use custom actions of github-actions package to annotate errors of eslint and stylelint
  .github/scripts/eslintFormatter.js
  .github/scripts/stylelintFormatter.js
  .github/scripts/utils.js
  .github/workflows/js-css-linting.yml
Labels: changelog: tweak

#1608 Add utilities to remove PHP 8.0 specific code of Symfony polyfills
  bin/SymfonyPolyfillCleanup.php
  composer.json
  composer.lock
  src/Infrastructure/GoogleListingsAndAdsPlugin.php
  src/Polyfills/MBString.php
  src/Polyfills/Normalizer.php
  src/Polyfills/Resources/unidata/canonicalComposition.php
  src/Polyfills/Resources/unidata/canonicalDecomposition.php
  src/Polyfills/Resources/unidata/combiningClass.php
  src/Polyfills/Resources/unidata/compatibilityDecomposition.php
  src/Polyfills/bootstrap.php
Labels: changelog: tweak

#1601 Upgrade Google Ads library to V11
  .github/workflows/php-unit-tests.yml
  README.md
  bin/GoogleAdsCleanupServices.php
  composer.json
  composer.lock
  google-listings-and-ads.php
  readme.txt
  src/API/Google/Ads.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignBudget.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/BillingSetupStatus.php
  src/API/Google/CampaignStatus.php
  src/API/Google/CampaignType.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/Query/AdsConversionActionQuery.php
  src/API/Google/Query/AdsQuery.php
  src/API/Google/Query/AdsReportQuery.php
  src/Google/Ads/GoogleAdsClient.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsConversionActionTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
Labels: changelog: update
