Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-12, with the labels that each got.

#1794 PMax Assets: Add step 2 to the campaign creation page
  js/src/components/adaptive-form/adaptive-form-context.js
  js/src/components/adaptive-form/adaptive-form.js
  js/src/components/adaptive-form/index.js
  js/src/components/paid-ads/ads-campaign.js
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/asset-group-section.scss
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/index.js
  js/src/components/stepper/step-content-footer/index.scss
  js/src/constants.js
  js/src/css/shared/_woocommerce-admin.scss
  js/src/pages/create-paid-ads-campaign/create-paid-ads-campaign-form.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/ads-stepper/index.scss
  js/src/setup-mc/setup-stepper/index.js
  js/src/setup-mc/setup-stepper/index.scss
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
Labels: changelog: update

#1798 Fix certain inbox notifications were shown before setup completed
  src/Ads/AdsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Notes/AfterCampaignMigration.php
  src/Notes/BeforeCampaignMigration.php
  src/Notes/ReconnectWordPress.php
  tests/Unit/Ads/AdsServiceTest.php
  tests/Unit/Notes/AfterCampaignMigrationTest.php
  tests/Unit/Notes/BeforeCampaignMigrationTest.php
  tests/Unit/Notes/ReconnectWordPressTest.php
Labels: type: bug, changelog: fix

#1797 Fetch WP Assets from specific term
  src/Ads/AssetSuggestionsService.php
  src/Proxies/WP.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: type: enhancement, changelog: add

#1799 PMax Assets: Add step 2 to the campaign editing page
  js/src/components/adaptive-form/adaptive-form-context.js
  js/src/components/paid-ads/ads-campaign.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/dashboard/all-programs-table-card/index.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/edit-paid-ads-campaign-form.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/utils/urls.js
Labels: changelog: update

#1803 Internalize campaign creation and editing to `AdsCampaign` to eliminate the associated *FormContent components
  jest.config.js
  js/src/components/paid-ads/ads-campaign.js
  js/src/components/paid-ads/audience-section.js
  js/src/components/paid-ads/audience-section.scss
  js/src/components/paid-ads/budget-section/index.scss
  js/src/components/paid-ads/campaign-preview/campaign-preview-card.js
  js/src/components/paid-ads/campaign-preview/campaign-preview-card.scss
  js/src/components/paid-ads/campaign-preview/index.js
  js/src/components/paid-ads/create-campaign-form-content.js
  js/src/components/paid-ads/edit-paid-ads-campaign-form-content.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/setup-ads/ads-stepper/create-campaign/index.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/setup-ads-form-content.js
  js/src/setup-ads/setup-ads-form.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-setup-sections.js
Labels: changelog: tweak

#1806 Release/2.3.2
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1779 Bump min supported WP version to 5.9 and align all WP and WC packages to WC 6.9
  .externalized.json
  .github/workflows/php-unit-tests.yml
  README.md
  google-listings-and-ads.php
  jest.config.js
  js/src/attribute-mapping/index.scss
  js/src/components/account-card/index.scss
  js/src/components/app-input-control/index.scss
  js/src/components/app-radio-content-control/index.js
  js/src/components/app-text/index.js
  js/src/components/app-text/index.scss
  js/src/components/campaign-conversion-notice/index.js
  js/src/components/campaign-conversion-notice/reports-notice.js
  js/src/components/faqs-panel/index.scss
  js/src/css/abstracts/_variables.scss
  js/src/css/shared/_gutenberg-components.scss
  js/src/dashboard/index.scss
  js/src/dashboard/summary-section/summary-card.js
  js/src/external-components/woocommerce/compare-filter/index.js
  js/src/get-started-page/benefits-card/index.js
  js/src/get-started-page/benefits-card/index.scss
  js/src/get-started-page/customer-quotes-card/index.js
  js/src/get-started-page/customer-quotes-card/index.scss
  js/src/get-started-page/features-card/index.js
  js/src/get-started-page/features-card/index.scss
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-card/index.scss
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/product-feed/issues-table-card/index.js
  js/src/product-feed/issues-table-card/issues-solved.js
  js/src/product-feed/product-feed-table-card/index.js
  js/src/product-feed/product-statistics/index.js
  js/src/product-feed/product-statistics/index.scss
  js/src/product-feed/review-request/review-request-issues.js
  js/src/product-feed/review-request/review-request-notice.js
  js/src/tests/dependencies/automattic/calypso-config.js
  js/src/tests/jest-unit.setup.js
  package-lock.json
  package.json
  readme.txt
  webpack.config.js
Labels: type: technical debt - dependency extraction, changelog: dev

#1751 Tours API Endpoint
  src/API/Site/Controllers/TourController.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Options/OptionsInterface.php
  tests/Unit/API/Site/Controllers/ToursControllerTest.php
Labels: type: enhancement, status: on hold, changelog: add

#1805 PMax Assets: Add the final URL card to the assets section
  js/src/components/account-card/final-url-icon.svg
  js/src/components/account-card/index.js
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/assets-loader.js
  js/src/components/paid-ads/asset-group/assets-loader.scss
  js/src/components/paid-ads/asset-group/final-url-card.js
  js/src/components/paid-ads/asset-group/final-url-card.scss
  js/src/data/types.js
Labels: type: enhancement, changelog: add

#1812 PMax Assets - Posts URLs suggestions - Search by title
  src/Ads/AssetSuggestionsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: type: enhancement, changelog: add

#1804 Resizing Images Assets Pmax assets
  src/Ads/AssetSuggestionsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Proxies/WP.php
  src/Utility/DimensionUtility.php
  src/Utility/ImageUtility.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
  tests/Unit/Utility/DimensionUtilityTest.php
  tests/Unit/Utility/ImageUtilityTest.php
Labels: type: enhancement, changelog: add

#1815 Release/2.3.3
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1818 Specify WP_VERSION for Docker Container
  package.json
Labels: type: technical debt, changelog: none

#1814 Improve image validation error messages
  src/MerchantCenter/MerchantStatuses.php
  src/Product/WCProductAdapter.php
  src/Validator/ImageUrlConstraint.php
  src/Validator/ImageUrlConstraintValidator.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: changelog: tweak

#1824 Release/2.3.4
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
  src/MerchantCenter/MerchantStatuses.php
  src/Product/WCProductAdapter.php
  src/Validator/ImageUrlConstraint.php
  src/Validator/ImageUrlConstraintValidator.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: changelog: none

#1821 Tweak Copy for Attribute Mapping
  js/src/attribute-mapping/attribute-mapping-category-control.js
  js/src/attribute-mapping/attribute-mapping-field-sources-control.js
  js/src/attribute-mapping/attribute-mapping-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-source-type-selector.js
  js/src/attribute-mapping/index.scss
  js/src/attribute-mapping/index.test.js
Labels: changelog: tweak

#1820 PMax Assets - Fetch assets groups
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AssetFieldType.php
  src/API/Google/Query/AdsAssetGroupAssetQuery.php
  src/API/Google/Query/AdsAssetGroupQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/API/Site/Controllers/Ads/AssetSuggestionsController.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Site/Controllers/Ads/AssetGroupControllerTest.php
  tests/Unit/API/Site/Controllers/Ads/AssetSuggestionsControllerTest.php
Labels: type: enhancement, changelog: add

#1826 Simplify report controller parameters
  src/API/Site/Controllers/Ads/ReportsController.php
  src/API/Site/Controllers/BaseReportsController.php
  src/API/Site/Controllers/MerchantCenter/ReportsController.php
Labels: changelog: tweak

#1829 Release 2.3.5
  changelog.txt
  google-listings-and-ads.php
  js/src/attribute-mapping/attribute-mapping-category-control.js
  js/src/attribute-mapping/attribute-mapping-field-sources-control.js
  js/src/attribute-mapping/attribute-mapping-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-source-type-selector.js
  js/src/attribute-mapping/index.scss
  js/src/attribute-mapping/index.test.js
  package-lock.json
  package.json
  readme.txt
  src/API/Site/Controllers/Ads/ReportsController.php
  src/API/Site/Controllers/BaseReportsController.php
  src/API/Site/Controllers/MerchantCenter/ReportsController.php
  src/MerchantCenter/PolicyComplianceCheck.php
Labels: changelog: none

#1828 Tweak Asset Suggestions format response.
  src/Ads/AssetSuggestionsService.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: changelog: tweak

#1819 PMax Assets: Integrate WP Media library to implement the asset images selector
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/images-selector.js
  js/src/components/paid-ads/asset-group/images-selector.scss
  js/src/components/paid-ads/campaign-preview/campaign-preview.scss
  js/src/css/abstracts/_variables.scss
  js/src/css/shared/_gutenberg-components.scss
  js/src/hooks/types.js
  js/src/hooks/useCroppedImageSelector/index.js
  js/src/hooks/useCroppedImageSelector/useCroppedImageSelector.js
  js/src/hooks/useCroppedImageSelector/useCroppedImageSelector.scss
  src/Admin/Admin.php
Labels: type: enhancement, changelog: add
