Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-02, with the labels that each got.

#1221 Spend Match Update - Main Feature PR
  js/src/components/paid-ads/budget-section/free-ad-credit/country-modal/country-amount.js
  js/src/components/paid-ads/budget-section/free-ad-credit/country-modal/index.js
  js/src/components/paid-ads/budget-section/free-ad-credit/index.js
  js/src/dashboard/summary-section/paid-campaign-promotion-card.js
  js/src/get-started-page/faqs.js
  js/src/hooks/useFreeAdCredit.js
  js/src/product-feed/submission-success-guide/index.js
  readme.txt
  src/API/Google/Proxy.php
  src/Ads/AdsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Notes/AbstractSetupCampaign.php
  src/Notes/CompleteSetup.php
  src/Notes/SetupCampaign.php
  src/Notes/SetupCampaignTwoWeeks.php
Labels: priority: high

#1020 Use Ads currency in report pages
  js/src/dashboard/all-programs-table-card/format-amount-with-code.js
  js/src/dashboard/all-programs-table-card/index.js
  js/src/dashboard/summary-section/index.js
  js/src/hooks/useAdsCurrency.js
  js/src/hooks/useAdsCurrency.test.js
  js/src/reports/chart-section.js
  js/src/reports/compare-table-card.js
  js/src/reports/format-amount.js
  js/src/reports/index.js
  js/src/reports/metric-number.js
  js/src/reports/products/index.js
  js/src/reports/programs/index.js
  js/src/reports/summary-section.js
  js/src/utils/formatAmountWithCode.js
Labels: type: technical debt - dependency extraction, type: technical debt - external devX

#1252 Fix the `null.toString()` exception in the `useAdsCurrency` hook
  js/src/hooks/useAdsCurrency.js
Labels: type: bug, priority: high
