Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-05, with the labels that each got.

#1449 Get started page UX improvements: add customer quotes card
  js/src/get-started-page/_shared.scss
  js/src/get-started-page/benefits-card/index.js
  js/src/get-started-page/benefits-card/index.scss
  js/src/get-started-page/customer-quotes-card/img-quote.svg
  js/src/get-started-page/customer-quotes-card/index.js
  js/src/get-started-page/customer-quotes-card/index.scss
  js/src/get-started-page/features-card/index.scss
  js/src/get-started-page/get-started-with-video-card/index.scss
  js/src/get-started-page/index.js
Labels: type: enhancement

#1460 Get started page UX improvements: add get started card
  js/src/css/abstracts/_gla_variables.scss
  js/src/get-started-page/_shared.scss
  js/src/get-started-page/benefits-card/index.scss
  js/src/get-started-page/customer-quotes-card/index.scss
  js/src/get-started-page/features-card/index.scss
  js/src/get-started-page/get-started-card/image.svg
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-card/index.scss
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.scss
  js/src/get-started-page/index.js
  js/src/utils/recordEvent.js
  webpack.config.js
Labels: type: enhancement

#1470 Get started page UX improvements: add FAQs card
  js/src/components/faqs-panel/index.js
  js/src/components/faqs-panel/index.scss
  js/src/get-started-page/faqs.js
  js/src/get-started-page/faqs/index.js
  js/src/get-started-page/faqs/index.scss
  js/src/get-started-page/index.js
Labels: type: enhancement

#1479 UX improvements on get started page
  js/src/components/faqs-panel/index.js
  js/src/components/faqs-panel/index.scss
  js/src/components/wistia-video/index.js
  js/src/components/wistia-video/index.scss
  js/src/css/abstracts/_gla_variables.scss
  js/src/get-started-page/benefits-card/image.png
  js/src/get-started-page/benefits-card/index.js
  js/src/get-started-page/benefits-card/index.scss
  js/src/get-started-page/customer-quotes-card/img-quote.svg
  js/src/get-started-page/customer-quotes-card/index.js
  js/src/get-started-page/customer-quotes-card/index.scss
  js/src/get-started-page/faqs.js
  js/src/get-started-page/faqs/index.js
  js/src/get-started-page/faqs/index.scss
  js/src/get-started-page/features-card/img-connection.svg
  js/src/get-started-page/features-card/img-dashboard.svg
  js/src/get-started-page/features-card/img-free-listings.svg
  js/src/get-started-page/features-card/img-google-ads.svg
  js/src/get-started-page/features-card/img-product-promotion.svg
  js/src/get-started-page/features-card/index.js
  js/src/get-started-page/features-card/index.scss
  js/src/get-started-page/get-started-card/image.svg
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-card/index.scss
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.scss
  js/src/get-started-page/index.js
  js/src/hooks/useScript.js
  js/src/images/google-logo.svg
  js/src/product-feed/submission-success-guide/index.js
  js/src/utils/recordEvent.js
  js/src/utils/urls.js
  tests/e2e/specs/get-started.test.js
  webpack.config.js
Labels: type: enhancement

#1485 Use a shared helper method to get supported countries of a continent for /mc/countries API
  src/API/Site/Controllers/MerchantCenter/SupportedCountriesController.php
  tests/Unit/API/Site/Controllers/MerchantCenter/SupportedCountriesControllerTest.php
Labels: category: refactor

#1501 Enhance event name for documentation link and update tracking document.
  js/src/components/app-documentation-link/index.js
  js/src/components/contact-information/index.js
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  js/src/components/contact-information/store-address-card.js
  js/src/components/different-currency-notice.js
  js/src/components/faqs-panel/index.js
  js/src/components/free-listings/choose-audience/form-content.js
  js/src/components/free-listings/configure-product-listings/shipping-time-section.js
  js/src/components/free-listings/configure-product-listings/tax-rate.js
  js/src/components/google-account-card/connect-google-account-card.js
  js/src/components/google-account-card/connected-google-account-card.js
  js/src/components/google-account-card/request-full-access-google-account-card.js
  js/src/components/google-ads-account-card/authorize-ads.js
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-ads-account-card/terms-modal/index.js
  js/src/components/google-mc-account-card/connected-google-mc-account-card.js
  js/src/components/google-mc-account-card/reclaim-url-card/index.js
  js/src/components/google-mc-account-card/terms-modal/index.js
  js/src/components/shipping-rate-section/shipping-rate-section.js
  js/src/edit-free-campaign/index.js
  js/src/get-started-page/faqs/index.js
  js/src/get-started-page/features-card/index.js
  js/src/get-started-page/unsupported-notices/index.js
  js/src/pages/create-paid-ads-campaign/create-paid-ads-campaign-form.js
  js/src/pages/edit-paid-ads-campaign/edit-paid-ads-campaign-form.js
  js/src/product-feed/issues-table-card/index.js
  js/src/product-feed/product-statistics/product-status-help-popover/index.js
  js/src/product-feed/submission-success-guide/index.js
  js/src/reports/summary-section.js
  js/src/settings/edit-phone-number.js
  js/src/settings/edit-store-address.js
  js/src/setup-ads/ads-stepper/create-campaign/index.js
  js/src/setup-ads/ads-stepper/setup-accounts/free-ad-credit/index.js
  js/src/setup-mc/setup-stepper/choose-audience/form-content.js
  js/src/setup-mc/setup-stepper/setup-accounts/faqs.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time-section.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
  src/Tracking/README.md
Labels: type: enhancement, javascript

#1511 Account Issues - Show the resolution steps in the UI
  js/src/product-feed/issues-table-card/index.scss
  js/src/product-feed/issues-table-card/issues-table-data-headers.js
  js/src/product-feed/issues-table-card/issues-table-data-modal.js
  js/src/product-feed/issues-table-card/issues-table-data-modal.test.js
  js/src/product-feed/issues-table-card/issues-table-data.js
  js/src/product-feed/issues-table-card/issues-table-data.test.js
  js/src/product-feed/issues-table-card/issues-table.js
  js/src/product-feed/issues-table-card/issues-table.test.js
  js/src/tests/mock-issue.js
Labels: javascript

#1536 Add more promotion supported countries
  src/Google/GoogleHelper.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
Labels: type: enhancement, php

#1535 Allow unicode for Manufacturer Part Number (MPN ) value
  src/Product/WCProductAdapter.php
Labels: type: enhancement, php
