Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-10, with the labels that each got.

#1707 Policy Compliance Checks: Remove unused JS hooks
  js/src/hooks/useAllowedCountries.js
  js/src/hooks/usePaymentGateways.js
  js/src/hooks/useRefundReturnPolicyPage.js
  js/src/hooks/useStoreSsl.js
Labels: changelog: dev

#1708 Policy Compliance Checks: Fix typos and the panel title may be covered by dropdown arrow
  js/src/css/shared/_gutenberg-components.scss
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
Labels: changelog: tweak

#1706 Free Listings + Paid Ads: Fetch the number of syncable products for the product feed status section
  js/src/get-started-page/index.js
  js/src/hooks/useSyncableProductsCalculation.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.scss
Labels: changelog: update

#1712 Release 2.1.4
  changelog.txt
  google-listings-and-ads.php
  js/src/components/pre-launch-check-item/index.js
  js/src/components/pre-launch-check-item/index.scss
  js/src/css/shared/_gutenberg-components.scss
  js/src/data/action-types.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/usePolicyCheck.js
  js/src/setup-mc/setup-stepper/store-requirements/index.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.scss
  package-lock.json
  package.json
  readme.txt
  src/API/Site/Controllers/MerchantCenter/PolicyComplianceCheckController.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/MerchantCenter/PolicyComplianceCheck.php
  src/Proxies/WC.php
  tests/Framework/WPRequestUnitTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/PolicyComplianceCheckControllerTest.php
  tests/Unit/MerchantCenter/PolicyComplianceCheckTest.php
Labels: changelog: none

#1711 Attribute Mapping - Tweak Sources & Data Types in backend
  src/API/Site/Controllers/MerchantCenter/AttributeMappingDataController.php
  src/API/Site/Controllers/MerchantCenter/AttributeMappingRulesController.php
  src/DB/Query/AttributeMappingRulesQuery.php
  src/DB/Table/AttributeMappingRulesTable.php
  src/Product/AttributeMappingHelper.php
Labels: type: bug, changelog: fix

#1714 Attribute Mapping - Rule pagination
  src/API/Site/Controllers/MerchantCenter/AttributeMappingRulesController.php
  tests/Unit/API/Site/Controllers/MerchantCenter/AttributeMappingRulesControllerTest.php
Labels: type: enhancement, changelog: add

#1710 Attribute Mapping - CRUD Rules Frontend
  js/src/attribute-mapping/attribute-mapping-category-control.js
  js/src/attribute-mapping/attribute-mapping-delete-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-source-type-selector.js
  js/src/attribute-mapping/attribute-mapping-table-categories.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/attribute-mapping/index.js
  js/src/attribute-mapping/index.test.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/constants.js
  js/src/data/controls.js
  js/src/data/index.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useCategoryTree.js
  js/src/hooks/useMappingRules.js
  src/API/Site/Controllers/MerchantCenter/AttributeMappingRulesController.php
  tests/Unit/API/Site/Controllers/MerchantCenter/AttributeMappingRulesControllerTest.php
Labels: type: enhancement, changelog: add

#1713 Free Listings + Paid Ads: Group variations type for syncable products
  src/API/Site/Controllers/MerchantCenter/SyncableProductsCountController.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/UpdateSyncableProductsCount.php
  src/Product/ProductHelper.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Jobs/UpdateSyncableProductsCountTest.php
  tests/Unit/Product/ProductHelperTest.php
Labels: php, changelog: update

#1720 Change the Stepper in the onboarding flow to only allow going back to the previous steps
  js/src/setup-mc/setup-stepper/index.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
Labels: type: bug, changelog: fix

#1717 Detect the verification status of the phone number to the contact information settings
  js/src/components/contact-information/index.js
  js/src/components/contact-information/phone-number-card/phone-number-card-preview.js
  js/src/components/contact-information/phone-number-card/phone-number-card-preview.scss
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  js/src/data/selectors.js
  js/src/hooks/useGoogleMCPhoneNumber.js
  js/src/setup-mc/setup-stepper/index.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  src/API/Site/Controllers/MerchantCenter/ContactInformationController.php
  src/MerchantCenter/MerchantCenterService.php
  tests/Tools/HelperTrait/MerchantTrait.php
Labels: changelog: update

#1721 Free Listings + Paid Ads: Add ad previews to the post-onboarding ads setup flow
  js/src/components/paid-ads/campaign-preview/campaign-preview.js
  js/src/components/paid-ads/create-campaign-form-content.js
  js/src/setup-ads/ads-stepper/create-campaign/campaign-preview-card.js
  js/src/setup-ads/ads-stepper/create-campaign/campaign-preview-card.scss
  js/src/setup-ads/ads-stepper/create-campaign/index.js
Labels: type: enhancement, changelog: add

#1732 Detect the verification status of the phone number: Follow-up adjustments for PR 1717 code reviews
  js/src/components/contact-information/index.js
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  src/API/Site/Controllers/MerchantCenter/ContactInformationController.php
  src/MerchantCenter/MerchantCenterService.php
Labels: changelog: tweak
