Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-09, with the labels that each got.

#1655 Free Listings + Paid Ads: Add the ads audience and budget sections
  js/src/components/account-card/index.scss
  js/src/components/different-currency-notice.js
  js/src/components/google-ads-account-card/google-ads-account-card.js
  js/src/components/paid-ads/audience-section.js
  js/src/components/paid-ads/budget-section/budget-recommendation/index.js
  js/src/components/paid-ads/budget-section/budget-recommendation/index.scss
  js/src/components/paid-ads/budget-section/index.js
  js/src/constants.js
  js/src/dashboard/summary-section/paid-campaign-promotion-card.js
  js/src/settings/linked-accounts.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/utils/paid-ads/__snapshots__/validateForm.test.js.snap
  js/src/utils/paid-ads/validateForm.js
  js/src/utils/paid-ads/validateForm.test.js
Labels: changelog: none

#1665 Fix an infinite re-rendering loop for the campaign budget input component
  js/src/components/paid-ads/budget-section/index.js
Labels: type: bug, changelog: fix

#1669 Release 2.1.1
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1670 Fix WC 6.7 compatibility issues about navigating away prompt without saving data
  js/src/edit-free-campaign/index.js
  js/src/hooks/useNavigateAwayPromptEffect.js
  js/src/setup-ads/setup-ads-form.js
Labels: type: bug, changelog: fix

#1672 Free Listings + Paid Ads: Fix a compatibility issue with the Form component in WC 6.9
  js/src/components/free-listings/setup-free-listings/index.js
Labels: type: bug, changelog: none

#1673 Release/2.1.2
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1674 Release 2.1.2
  changelog.txt
  google-listings-and-ads.php
  js/src/edit-free-campaign/index.js
  js/src/hooks/useNavigateAwayPromptEffect.js
  js/src/setup-ads/setup-ads-form.js
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1656 Attribute mapping - Endpoints for Sources and Destinations
  src/API/Site/Controllers/MerchantCenter/AttributeMappingController.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Product/AttributeMappingHelper.php
  src/Product/Attributes/Adult.php
  src/Product/Attributes/AgeGroup.php
  src/Product/Attributes/WithMappingInterface.php
  tests/Unit/API/Site/Controllers/MerchantCenter/AttributeMappingControllerTest.php
Labels: type: enhancement, changelog: add

#1664 Attribute Mapping - List Taxonomies and Global Attributes in sources
  src/Product/AttributeMappingHelper.php
  src/Product/Attributes/Color.php
  tests/Unit/API/Site/Controllers/MerchantCenter/AttributeMappingControllerTest.php
Labels: type: enhancement, changelog: add

#1677 Free Listings + Paid Ads: Add the billing setup card and the paid ads completion
  js/src/components/paid-ads/billing-card/billing-card.js
  js/src/components/paid-ads/billing-card/billing-card.scss
  js/src/components/paid-ads/billing-card/billing-setup-card.js
  js/src/components/paid-ads/billing-card/billing-setup-card.scss
  js/src/components/paid-ads/billing-card/fallbackBillingUrl.js
  js/src/components/paid-ads/billing-card/index.js
  js/src/components/paid-ads/billing-card/useAutoCheckBillingStatusEffect.js
  js/src/components/paid-ads/budget-section/index.js
  js/src/components/paid-ads/budget-section/index.scss
  js/src/constants.js
  js/src/data/resolvers.js
  js/src/hooks/useAdsSetupCompleteCallback.js
  js/src/hooks/useGoogleAdsAccountBillingStatus.js
  js/src/setup-ads/ads-stepper/setup-billing/index.js
  js/src/setup-ads/ads-stepper/setup-billing/setup-card/index.js
  js/src/setup-ads/ads-stepper/setup-billing/setup-card/index.scss
  js/src/setup-ads/setup-ads-form.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-setup-sections.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
Labels: changelog: update

#1679 Free Listings + Paid Ads: Update learn more links, FAQs, CSS disclaimer, submission success modal, and title of free listings settings
  js/src/components/faqs-panel/index.scss
  js/src/components/free-listings/configure-product-listings/hero/index.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/components/google-mc-account-card/google-mc-account-card.js
  js/src/components/paid-ads/faqs-section.js
  js/src/data/selectors.js
  js/src/edit-free-campaign/index.js
  js/src/external-components/wordpress/guide/index.js
  js/src/hooks/useGoogleMCAccount.js
  js/src/product-feed/index.test.js
  js/src/product-feed/submission-success-guide/index.js
  js/src/product-feed/submission-success-guide/index.scss
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/setup-stepper/setup-accounts/faqs.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.scss
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.js
  js/src/wcdl/section/index.js
  js/src/wcdl/section/index.scss
Labels: changelog: update

#1681 Free Listings + Paid Ads: Update product feed API to return the bestselling product
  src/API/Site/Controllers/MerchantCenter/ProductFeedController.php
  src/Admin/Admin.php
  src/DB/ProductFeedQueryHelper.php
Labels: php, changelog: update, changelog: none

#1697 Fix Size types ENUM options
  src/Product/Attributes/SizeType.php
Labels: type: bug, changelog: fix

#1683 Free Listings + Paid Ads: Store and restore the states of paid ads setup
  js/src/setup-mc/setup-stepper/setup-paid-ads/clientSession.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-setup-sections.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
Labels: changelog: none

#1689 Free Listings + Paid Ads: Add event tracking
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  src/Tracking/README.md
Labels: changelog: none

#1693 Free Listings + Paid Ads: Do not refresh MC status when user is not onboarded for product feed API
  src/DB/ProductFeedQueryHelper.php
  tests/Unit/DB/ProductFeedQueryHelperTest.php
Labels: changelog: update, changelog: none

#1692 Free Listings + Paid Ads: Use merchant's data to composite the ad previews
  js/src/components/paid-ads/campaign-preview/campaign-preview.js
  js/src/components/paid-ads/campaign-preview/campaign-preview.scss
Labels: changelog: update

#1696 Migrate column data type in MC account Issues table
  src/DB/Table/MerchantIssueTable.php
Labels: type: bug, changelog: fix

#1695 Override Website Claim Lost issue info
  src/MerchantCenter/MerchantStatuses.php
Labels: merchant center, changelog: tweak

#1691 Attribute Mapping - Table Data
  js/src/attribute-mapping/attribute-mapping-table-categories.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/attribute-mapping/index.js
  js/src/attribute-mapping/index.scss
  js/src/attribute-mapping/index.test.js
Labels: type: enhancement, changelog: add

#1680 GLA Attribute Mapping - Add Create Rule Modal
  js/src/attribute-mapping/attribute-mapping-category-control.js
  js/src/attribute-mapping/attribute-mapping-field-sources-control.js
  js/src/attribute-mapping/attribute-mapping-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-source-type-selector.js
  js/src/attribute-mapping/attribute-mapping-table-categories.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/attribute-mapping/index.js
  js/src/attribute-mapping/index.scss
  js/src/attribute-mapping/index.test.js
  js/src/constants.js
  js/src/css/abstracts/_variables.scss
  js/src/hooks/useCategoryTree.js
  js/src/hooks/useMappingAttributes.js
  js/src/hooks/useMappingAttributesSources.js
  js/src/wcdl/subsection/index.js
  js/src/wcdl/subsection/subtitle/index.js
  js/src/wcdl/subsection/subtitle/index.scss
Labels: type: enhancement, changelog: add

#1700 Release 2.1.3
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
  src/DB/Table/MerchantIssueTable.php
  src/MerchantCenter/MerchantStatuses.php
  src/Product/Attributes/SizeType.php
  tests/proxy/index.js
Labels: changelog: none

#1699 Free Listings + Paid Ads: Add two APIs to retrieve the syncable products count and schedule the job to calculate the count
  src/API/Site/Controllers/MerchantCenter/SyncableProductsCountController.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Jobs/AbstractBatchedActionSchedulerJob.php
  src/Jobs/SyncableProductsBatchedActionSchedulerJobTrait.php
  src/Jobs/UpdateAllProducts.php
  src/Jobs/UpdateSyncableProductsCount.php
  src/Options/OptionsInterface.php
  tests/Unit/API/Site/Controllers/MerchantCenter/SyncableProductsCountControllerTest.php
  tests/Unit/Jobs/CleanupSyncedProductsTest.php
  tests/Unit/Jobs/UpdateAllProductsTest.php
  tests/Unit/Jobs/UpdateSyncableProductsCountTest.php
Labels: type: enhancement, php, changelog: add, changelog: none

#1687 Attribute Mapping - Add logic for Saving Rules in Database with API
  src/API/Site/Controllers/MerchantCenter/AttributeMappingDataController.php
  src/API/Site/Controllers/MerchantCenter/AttributeMappingRulesController.php
  src/DB/Query/AttributeMappingRulesQuery.php
  src/DB/Table/AttributeMappingRulesTable.php
  src/DB/TableManager.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/DBServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Product/AttributeMappingHelper.php
  src/Product/Attributes/Color.php
  tests/Unit/API/Site/Controllers/MerchantCenter/AttributeMappingDataControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/AttributeMappingRulesControllerTest.php
Labels: type: enhancement, changelog: add

#1703 Attribute Mapping - Integrate Modal API (Frontend)
  js/src/attribute-mapping/attribute-mapping-field-sources-control.js
  js/src/attribute-mapping/attribute-mapping-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-source-type-selector.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/attribute-mapping/index.test.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useAppSelectDispatch.js
  js/src/hooks/useMappingAttributes.js
  js/src/hooks/useMappingAttributesSources.js
Labels: type: enhancement, changelog: add
