Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-04, with the labels that each got.

#1389 Change shipping time options based on shipping rate options
  js/src/components/free-listings/configure-product-listings/shipping-time-section.js
  js/src/components/shipping-rate-section/shipping-rate-section.js
  js/src/edit-free-campaign/setup-free-listings/form-content.js
  js/src/setup-mc/setup-stepper/setup-free-listings/form-content.js
  js/src/setup-mc/setup-stepper/setup-free-listings/shipping-time-section.js
Labels: type: bug, priority: critical

#1386 Only sync shipping rates if shipping time is set to `flat`
  src/API/Google/Settings.php
Labels: type: bug

#1406 Setup MC - Set initial value 'flat' for shipping time option
  js/src/setup-mc/setup-stepper/setup-free-listings/index.js
Labels: priority: critical

#1423 Apply migrations by the order of their applicable versions
  src/DB/Migration/Migrator.php
Labels: type: enhancement

#1409 Edit Free Listings - Remove corresponding shipping rate and shipping time when target audience is changed
  js/src/edit-free-campaign/index.js
  js/src/hooks/useSaveShippingTimes.js
  js/src/utils/getDeletedShippingTimes.js
  js/src/utils/getDeletedShippingTimes.test.js
  js/src/utils/getDifferentShippingTimes.js
  js/src/utils/getDifferentShippingTimes.test.js
Labels: status: blocked

#1432 Get started page UX improvements: add get started with video card
  js/src/components/wistia-video/index.js
  js/src/components/wistia-video/index.scss
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.scss
  js/src/get-started-page/index.js
  js/src/hooks/useScript.js
  js/src/images/google-logo.svg
  js/src/product-feed/submission-success-guide/index.js
  js/src/utils/urls.js
Labels: type: enhancement

#1438 Get started page UX improvements: add benefits card
  js/src/get-started-page/benefits-card/image.png
  js/src/get-started-page/benefits-card/index.js
  js/src/get-started-page/benefits-card/index.scss
  js/src/get-started-page/index.js
  tests/e2e/specs/get-started.test.js
  webpack.config.js
Labels: type: enhancement

#1424 Refactor and simplify `EstimatedShippingRatesCard`
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/add-rate-modal.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/edit-rate-modal.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/getHandlers.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/getHandlers.test.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/groupShippingRatesByMethodCurrencyRate.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/groupShippingRatesByMethodCurrencyRate.test.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/add-rate-form-modal.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/edit-rate-form-modal.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/index.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/rate-form-modal.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/validate.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/validate.test.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/shipping-rate-input-control.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/shipping-rate-input-control.scss
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/typedefs.js
Labels: type: technical debt

#1451 Adding update all product test to catch the bug when scheduled job wa…
  src/Jobs/AbstractBatchedActionSchedulerJob.php
  src/Jobs/Update/PluginUpdate.php
  src/Jobs/UpdateAllProducts.php
  src/Product/FilteredProductList.php
  src/Product/ProductRepository.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Jobs/UpdateAllProductsTest.php
  tests/Unit/Product/ProductRepositoryTest.php
Labels: priority: high
