Repository woocommerce/google-listings-and-ads, pull requests merged in 2022-11, with the labels that each got.

#1719 Attribute Mapping - Category Tree API
  js/src/attribute-mapping/attribute-mapping-category-control.js
  js/src/attribute-mapping/attribute-mapping-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-table-categories.js
  js/src/attribute-mapping/index.scss
  js/src/attribute-mapping/index.test.js
  js/src/constants.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useCategories.js
  js/src/hooks/useCategoryTree.js
  src/API/Site/Controllers/MerchantCenter/AttributeMappingCategoriesController.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
Labels: type: enhancement, changelog: add

#1743 Add a hint for troubleshooting E2E on Linux.
  README.md
Labels: changelog: none

#1636 E2E Testing: Reduce the false positive rate and adjust the running events on GitHub Actions
  .github/workflows/e2e-tests.yml
  README.md
  js/src/gtag-events/index.js
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/utils/cart.js
Labels: changelog: dev

#1727 Attribute Mapping - Mapping function
  src/Integration/YoastWooCommerceSeo.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Product/AttributeMapping/AttributeMappingHelper.php
  src/Product/AttributeMapping/Traits/IsFieldTrait.php
  src/Product/BatchProductHelper.php
  src/Product/ProductFactory.php
  src/Product/ProductSyncer.php
  src/Product/WCProductAdapter.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Product/BatchProductHelperTest.php
  tests/Unit/Product/ProductFactoryTest.php
  tests/Unit/Product/ProductSyncerTest.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: enhancement, changelog: add

#1733 Attribute Mapping - Sync Frontend
  js/src/attribute-mapping/attribute-mapping-sync.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/attribute-mapping/index.scss
  js/src/attribute-mapping/index.test.js
  js/src/hooks/usePolling.js
  js/src/product-feed/product-statistics/status-box/sync-status.js
  js/src/utils/date.js
Labels: type: enhancement, changelog: add

#1731 Attribute Mapping - Syncer
  js/src/attribute-mapping/attribute-mapping-sync.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/attribute-mapping/index.scss
  js/src/attribute-mapping/index.test.js
  js/src/hooks/usePolling.js
  js/src/product-feed/product-statistics/status-box/sync-status.js
  js/src/utils/date.js
  src/API/Site/Controllers/AttributeMapping/AttributeMappingDataController.php
  src/API/Site/Controllers/AttributeMapping/AttributeMappingRulesController.php
  src/API/Site/Controllers/AttributeMapping/AttributeMappingSyncerController.php
  src/Event/StartProductSync.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Jobs/UpdateAllProducts.php
  src/Options/OptionsInterface.php
  tests/Unit/API/Site/Controllers/AttributeMapping/AttributeMappingDataControllerTest.php
  tests/Unit/API/Site/Controllers/AttributeMapping/AttributeMappingRulesControllerTest.php
  tests/Unit/API/Site/Controllers/AttributeMapping/AttributeMappingSyncerControllerTest.php
  tests/Unit/Jobs/UpdateAllProductsTest.php
Labels: type: enhancement, changelog: add

#1759 WC 7.1 Compatibility: Fix Form's onChange is called unexpected times which leads to infinite requesting state updates
  js/src/components/adaptive-form/adaptive-form.js
  js/src/components/adaptive-form/index.js
  js/src/components/free-listings/setup-free-listings/index.js
Labels: type: bug, changelog: fix

#1762 Import from an externalized package if explicitly asked for
  .externalized.json
  jest.config.js
  js/src/components/app-tooltip/index.js
  js/src/components/google-ads-account-card/connected-google-ads-account-card.js
  js/src/components/help-popover/index.js
  js/src/components/paid-ads/billing-card/billing-setup-card.js
  js/src/jsconfig.json
  package-lock.json
  package.json
  webpack.config.js
Labels: changelog: dev

#1739 WP 6.1 Compatibility: Fix the giant icons in the `DatePicker` component
  js/src/components/app-modal/index.js
  js/src/components/withAdminPageShell.js
  js/src/css/shared/_gutenberg-components.scss
  js/src/index.js
  package.json
Labels: type: bug, changelog: fix

#1740 Move the order of GLA below the Coupons in the Marketing menu of WC admin page
  src/Menu/Dashboard.php
  src/Menu/GetStarted.php
  src/Menu/MenuFixesTrait.php
Labels: type: bug, changelog: fix

#1766 Remove a semicolon that should not be rendered from `withAdminPageShell`
  js/src/components/withAdminPageShell.js
Labels: changelog: tweak

#1771 Release/2.2.1
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1773 Remove custom implementation of `<input type="number">`
  js/src/custom-inputs/index.js
  js/src/custom-inputs/integer/index.js
  views/inputs/integer.php
Labels: type: enhancement, type: technical debt, category: accessibility, changelog: update

#1768 Fix Yoast global identifiers for variable products
  src/Integration/YoastWooCommerceSeo.php
  tests/Unit/Integration/YoastWooCommerceSeoTest.php
Labels: type: bug, changelog: fix

#1769 Attribute Mapping - UX and Text tweaks
  js/src/attribute-mapping/attribute-mapping-description.js
  js/src/attribute-mapping/attribute-mapping-source-type-selector.js
  js/src/attribute-mapping/attribute-mapping-sync.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/attribute-mapping/index.js
  js/src/attribute-mapping/index.test.js
  js/src/components/help-popover/index.js
  js/src/components/navigation-classic/main-tab-nav.js
Labels: changelog: tweak

#1775 Bump min supported WC version to 6.9 and update few DEWP & dev dependencies
  README.md
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: dev

#1767 Remove unused GRPC packages
  bin/cleanup-vendor-files.sh
  composer.json
  composer.lock
Labels: changelog: tweak

#1774 Add a script to list woo/DEWPed versions
  README.md
  Working with DEWP.md
  bin/list-woo-dewped.mjs
  package.json
Labels: type: technical debt - dependency extraction, changelog: dev

#1777 Attribute Mapping - Add tracking
  js/src/attribute-mapping/attribute-mapping-delete-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/components/adaptive-form/adaptive-form.js
  js/src/hooks/useCategories.js
  js/src/product-feed/submission-success-guide/index.js
  js/src/utils/recordEvent.js
  src/API/Site/Controllers/MerchantCenter/AttributeMappingCategoriesController.php
  src/Tracking/README.md
Labels: type: enhancement, changelog: add

#1778 Attribute Mapping - Add Inbox Notification
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Notes/AttributeMappingNewFeature.php
  src/PluginHelper.php
  tests/Unit/Notes/AttributeMappingNewFeatureTest.php
Labels: type: enhancement, changelog: add

#1728 Fix incorrect product statistics count
  src/Jobs/DeleteProducts.php
  src/MerchantCenter/MerchantStatuses.php
  src/Product/ProductHelper.php
  src/Product/ProductRepository.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/ProductRepositoryTest.php
Labels: changelog: update

#1784 PMax-Asset: Final URL Suggestions Endpoint
  src/API/Site/Controllers/Assets/AssetSuggestionsController.php
  src/Ads/AssetSuggestionsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Proxies/WP.php
  tests/Unit/API/Site/Controllers/Assets/AssetSuggestionsControllerTest.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: type: enhancement, changelog: add

#1793 Delete products in GMC when force delete a product or change catalog visibility to hidden
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Jobs/DeleteProducts.php
  src/Product/BatchProductHelper.php
  src/Product/ProductRepository.php
  src/Product/ProductSyncer.php
  tests/Unit/Product/ProductRepositoryTest.php
  tests/Unit/Product/ProductSyncerTest.php
Labels: type: bug, php, changelog: fix

#1792 Bump WC/WP Components: Fix AppRadioContentControl
  js/src/components/app-radio-content-control/index.js
Labels: changelog: dev, changelog: none

#1791 Bump WC/WP Components: Fix Component Card CSS
  js/src/components/account-card/index.scss
  js/src/components/app-input-control/index.scss
  js/src/dashboard/index.scss
  js/src/get-started-page/benefits-card/index.scss
  js/src/get-started-page/customer-quotes-card/index.scss
  js/src/get-started-page/features-card/index.scss
  js/src/get-started-page/get-started-card/index.scss
  js/src/product-feed/product-statistics/index.scss
Labels: changelog: dev, changelog: none

#1795 Fetch WP Assets from specific post.
  src/API/Site/Controllers/Assets/AssetSuggestionsController.php
  src/Ads/AssetSuggestionsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Proxies/WP.php
  src/Utility/ArrayUtil.php
  tests/Unit/API/Site/Controllers/Assets/AssetSuggestionsControllerTest.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: type: enhancement, changelog: add

#1790 Bump WC/WP Components: Component Text fix
  js/src/components/app-text/index.js
  js/src/components/app-text/index.scss
  js/src/components/campaign-conversion-notice/index.js
  js/src/components/campaign-conversion-notice/reports-notice.js
  js/src/css/abstracts/_variables.scss
  js/src/dashboard/summary-section/summary-card.js
  js/src/external-components/woocommerce/compare-filter/index.js
  js/src/get-started-page/benefits-card/index.js
  js/src/get-started-page/customer-quotes-card/index.js
  js/src/get-started-page/features-card/index.js
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/product-feed/issues-table-card/index.js
  js/src/product-feed/issues-table-card/issues-solved.js
  js/src/product-feed/product-feed-table-card/index.js
  js/src/product-feed/product-statistics/index.js
  js/src/product-feed/review-request/review-request-issues.js
  js/src/product-feed/review-request/review-request-notice.js
Labels: changelog: dev, changelog: none
