Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-11, with the labels that each got.

#2144 Update docs domain name to Woo.com
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  google-listings-and-ads.php
  js/src/components/contact-information/index.js
  js/src/components/google-account-card/connect-google-account-card.js
  js/src/components/google-account-card/read-more-link.js
  js/src/components/google-account-card/request-full-access-google-account-card.js
  js/src/components/help-icon-button.js
  js/src/get-started-page/faqs/index.js
  js/src/get-started-page/features-card/index.js
  js/src/settings/edit-phone-number.js
  js/src/settings/edit-store-address.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
  package.json
  readme.txt
  src/Integration/WooCommercePreOrders.php
  src/Menu/MenuFixesTrait.php
  src/MerchantCenter/MerchantStatuses.php
  src/MultichannelMarketing/GLAChannel.php
  src/Notes/LeaveReviewActionTrait.php
  src/Notes/SetupCampaign.php
  src/PluginHelper.php
  src/Tracking/README.md
  tests/e2e/specs/setup-mc/step-3-confirm-store-requirements.test.js
Labels: changelog: update

#2145 Add the missing functions required for the WPCOM OAuth flow.
  src/Integration/JetpackWPCOM.php
  src/Internal/DependencyManagement/IntegrationServiceProvider.php
Labels: type: enhancement, changelog: add

#2150 Update phpunit polyfills to 1.1 for WP 6.4
  composer.json
  composer.lock
Labels: changelog: tweak

#2155 Remove unused flush_rewrite_rules
  src/Infrastructure/GoogleListingsAndAdsPlugin.php
Labels: changelog: tweak

#2156 Add node ^18 and npm ^9 as supported engines for dependabot
  README.md
  package.json
Labels: changelog: dev

#2052 Add filter to be able to build custom shipping method rate handers.
  src/Shipping/ZoneMethodsParser.php
Labels: changelog: add

#2152 Enable filtering of WC REST API responses based on the gla_syncable query parameter
  src/Integration/WPCOMProxy.php
  src/Internal/DependencyManagement/IntegrationServiceProvider.php
  tests/Unit/Integration/WPCOMProxyTest.php
Labels: type: enhancement, changelog: add

#2161 Fix E2E gtag events for a blockified confirmation page.
  tests/e2e/utils/customer.js
Labels: type: bug, changelog: fix

#2153 Tweak Budget recommendations logic
  data/budget-recommendations.csv
  js/src/components/paid-ads/budget-section/budget-recommendation/index.js
  src/API/Site/Controllers/Ads/BudgetRecommendationController.php
  src/DB/Migration/Migration20231109T1653383133.php
  src/DB/Table.php
  src/DB/Table/BudgetRecommendationTable.php
  src/DB/TableInterface.php
  src/Internal/DependencyManagement/DBServiceProvider.php
  tests/Unit/API/Site/Controllers/Ads/BudgetRecommendationControllerTest.php
Labels: changelog: tweak
