Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-01, with the labels that each got.

#1835 i18n for View Reports button
  js/src/dashboard/index.js
Labels: changelog: fix

#1839 Compatibility between CES and WC7.3
  js/src/components/customer-effort-score-prompt/index.js
  js/src/css/shared/_woocommerce-admin.scss
  js/src/dashboard/index.js
  js/src/product-feed/index.js
Labels: type: bug, changelog: fix

#1834 Use AppButton with extracted Button component
  js/src/components/app-button/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/add-time-button/add-time-modal/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/add-time-button/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/edit-time-modal/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/index.js
  js/src/components/google-ads-account-card/create-account.js
  js/src/components/google-mc-account-card/create-account-button.js
  js/src/components/google-mc-account-card/disabled-card.js
  js/src/components/pre-launch-check-item/index.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/add-rate-form-modal.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/edit-rate-form-modal.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/rate-form-modals/rate-form-modal.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-form-modals/add-minimum-order-form-modal.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-form-modals/edit-minimum-order-form-modal.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-form-modals/minimum-order-form-modal.js
  js/src/components/tree-select-control/tags.js
  js/src/css/shared/_gutenberg-components.scss
  js/src/dashboard/all-programs-table-card/edit-program-button/edit-program-prompt-modal/index.js
  js/src/dashboard/all-programs-table-card/edit-program-button/index.js
  js/src/dashboard/all-programs-table-card/program-toggle/pause-program-modal/index.js
  js/src/dashboard/all-programs-table-card/remove-program-button/index.js
  js/src/dashboard/all-programs-table-card/remove-program-button/remove-program-modal/index.js
  js/src/dashboard/campaign-creation-success-guide/index.js
  js/src/dashboard/index.js
  js/src/external-components/woocommerce/compare-filter/index.js
  js/src/external-components/woocommerce/filter-picker/index.js
  js/src/external-components/wordpress/guide/finish-button.js
  js/src/external-components/wordpress/guide/index.js
  js/src/external-components/wordpress/guide/page-control.js
  js/src/product-feed/product-feed-table-card/edit-visibility-action.js
  js/src/product-feed/review-request/review-request-issues.js
  js/src/product-feed/submission-success-guide/index.js
  js/src/reports/compare-table-card.js
  js/src/settings/disconnect-modal/confirm-modal.js
  js/src/settings/linked-accounts.js
  js/src/setup-ads/ads-stepper/setup-accounts/index.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
Labels: changelog: dev

#1845 Release/2.3.6
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1844 Prevent the "import/no-duplicates" warning for the externalization process
  .eslintrc.js
Labels: changelog: dev

#1840 Tweak response asset group
  src/API/Google/AdsAssetGroupAsset.php
Labels: changelog: tweak

#1837 Fetch assets from other Asset Groups using the final url
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/Query/Query.php
  src/Ads/AssetSuggestionsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: type: enhancement, changelog: add

#1832 Update Assets Groups
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/CallToActionType.php
  src/API/Google/Query/Query.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/Ads/AssetSuggestionsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/StatusMapping.php
  src/Proxies/WP.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
  tests/Unit/API/Site/Controllers/Ads/AssetGroupControllerTest.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: type: enhancement, changelog: add

#1847 PMax - Assets for non static homepage
  src/API/Site/Controllers/Ads/AssetSuggestionsController.php
  src/Ads/AssetSuggestionsService.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: type: enhancement, changelog: add

#1850 Preselect first existing merchant account during onboarding
  js/src/components/merchant-center-select-control/index.js
  js/src/components/merchant-center-select-control/index.test.js
Labels: changelog: tweak

#1857 Release 2.3.7
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1858 Release 2.3.7
  .eslintrc.js
  changelog.txt
  google-listings-and-ads.php
  js/src/components/merchant-center-select-control/index.js
  js/src/components/merchant-center-select-control/index.test.js
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1851 Add Endpoint- Create Asset Group
  src/API/Google/AdsAssetGroup.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Site/Controllers/Ads/AssetGroupControllerTest.php
Labels: type: enhancement, changelog: add

#1853 PMax Assets: AssetField for constructing the layout for editing images and texts
  js/src/components/help-popover/index.js
  js/src/components/help-popover/index.scss
  js/src/components/paid-ads/asset-group/add-asset-item-button.js
  js/src/components/paid-ads/asset-group/add-asset-item-button.scss
  js/src/components/paid-ads/asset-group/asset-field.js
  js/src/components/paid-ads/asset-group/asset-field.scss
  js/src/components/paid-ads/asset-group/asset-field.test.js
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/images-selector.js
  js/src/components/paid-ads/asset-group/images-selector.scss
  js/src/wcdl/section/index.js
  js/src/wcdl/section/index.scss
Labels: type: enhancement, changelog: add

#1861 Fix table footer rendering a zero when no pagination is needed
  js/src/product-feed/product-feed-table-card/index.js
Labels: type: bug, changelog: fix

#1860 PMax - Suggest HTML inserted images
  src/Ads/AssetSuggestionsService.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: changelog: tweak

#1865 Release 2.3.8
  changelog.txt
  google-listings-and-ads.php
  js/src/product-feed/product-feed-table-card/index.js
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1864 Batch assets creation
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
Labels: changelog: update

#1859 Fix namespace for additional vendor packages
  bin/prefix-vendor-namespace.php
  src/API/Google/Merchant.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/MerchantReport.php
  src/API/Google/Query/MerchantQuery.php
  src/API/Google/Settings.php
  src/API/Google/SiteVerification.php
  src/API/Site/Controllers/MerchantCenter/ContactInformationController.php
  src/Coupon/CouponSyncer.php
  src/Coupon/WCCouponAdapter.php
  src/Google/BatchProductEntry.php
  src/Google/DeleteCouponEntry.php
  src/Google/GoogleProductService.php
  src/Google/GooglePromotionService.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Jobs/DeleteCoupon.php
  src/MerchantCenter/ContactInformation.php
  src/MerchantCenter/MerchantCenterService.php
  src/MerchantCenter/MerchantStatuses.php
  src/MerchantCenter/PhoneVerification.php
  src/Product/BatchProductHelper.php
  src/Product/ProductHelper.php
  src/Product/WCProductAdapter.php
  src/Shipping/GoogleAdapter/AbstractRateGroupAdapter.php
  src/Shipping/GoogleAdapter/AbstractShippingSettingsAdapter.php
  src/Shipping/GoogleAdapter/DBShippingSettingsAdapter.php
  src/Shipping/GoogleAdapter/PostcodesRateGroupAdapter.php
  src/Shipping/GoogleAdapter/StatesRateGroupAdapter.php
  src/Shipping/GoogleAdapter/WCShippingSettingsAdapter.php
  src/Utility/AddressUtility.php
  src/Validator/GooglePriceConstraintValidator.php
  tests/Tools/HelperTrait/CouponTrait.php
  tests/Tools/HelperTrait/MerchantTrait.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/API/Google/MerchantMetricsTest.php
  tests/Unit/API/Google/MerchantTest.php
  tests/Unit/API/Google/SiteVerificationTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/RequestReviewControllerTest.php
  tests/Unit/Coupon/CouponSyncerTest.php
  tests/Unit/Coupon/WCCouponAdapterTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
  tests/Unit/MerchantCenter/PhoneVerificationTest.php
  tests/Unit/Product/ProductSyncerTest.php
  tests/Unit/Product/WCProductAdapterTest.php
  tests/Unit/Shipping/GoogleAdapter/PostcodesRateGroupAdapterTest.php
  tests/Unit/Shipping/GoogleAdapter/StatesRateGroupAdapterTest.php
  tests/Unit/Shipping/GoogleAdapter/WCShippingSettingsAdapterTest.php
  tests/Unit/Utility/AddressUtilityTest.php
Labels: type: bug, changelog: fix

#1854 PMax Assets: TextsEditor for managing the asset texts
  js/src/components/app-input-control/index.js
  js/src/components/app-input-control/index.scss
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/texts-editor.js
  js/src/components/paid-ads/asset-group/texts-editor.scss
  js/src/components/paid-ads/asset-group/texts-editor.test.js
  js/src/utils/getCharacterCounter.js
  js/src/utils/getCharacterCounter.test.js
Labels: type: enhancement, changelog: add

#1862 PMax Assets: Preprocessing for the assets form
  js/src/components/paid-ads/__snapshots__/validateCampaign.test.js.snap
  js/src/components/paid-ads/ads-campaign.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/images-selector.js
  js/src/components/paid-ads/asset-group/images-selector.test.js
  js/src/components/paid-ads/asset-group/texts-editor.js
  js/src/components/paid-ads/asset-group/texts-editor.test.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/validateCampaign.js
  js/src/components/paid-ads/validateCampaign.test.js
  js/src/components/types.js
  js/src/hooks/useCroppedImageSelector/useCroppedImageSelector.test.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/setup-ads/setup-ads-form.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-setup-sections.js
  js/src/utils/paid-ads/__snapshots__/validateForm.test.js.snap
Labels: type: enhancement, changelog: tweak

#1863 PMax Assets: Assets form for managing asset group
  js/src/components/adaptive-form/adaptive-form.js
  js/src/components/paid-ads/__snapshots__/validateAssetGroup.test.js.snap
  js/src/components/paid-ads/ads-campaign.js
  js/src/components/paid-ads/asset-group/asset-field.js
  js/src/components/paid-ads/asset-group/asset-field.test.js
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/asset-group/asset-group-card.scss
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-specs.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/validateAssetGroup.js
  js/src/components/paid-ads/validateAssetGroup.test.js
  js/src/components/types.js
  js/src/setup-ads/setup-ads-form.js
Labels: type: enhancement, changelog: add
