Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-12, with the labels that each got.

#2167 Add (budget and audiences) tracking for Onboarding completed with Ads
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  src/Tracking/README.md
Labels: type: enhancement, changelog: tweak

#2180 Change to require Google Ads connection during the onboarding
  js/src/components/paid-ads/campaign-preview/mockup-search.js
  js/src/hooks/useGoogleAdsAccount.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-setup-sections.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  src/Tracking/README.md
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/page.js
  tests/e2e/utils/pages/setup-ads/setup-ads-accounts.js
  tests/e2e/utils/pages/setup-ads/setup-budget.js
  tests/e2e/utils/pages/setup-mc/step-4-complete-campaign.js
Labels: changelog: update

#2183 Include PHP 8.3 in tested versions for PHPunit
  .github/workflows/php-unit-tests.yml
Labels: changelog: tweak

#2184 Fix item price in purchase event
  src/Google/GlobalSiteTag.php
Labels: type: bug, changelog: fix

#2189 Update link for developer.woo.com
  src/Menu/MenuFixesTrait.php
Labels: changelog: dev

#2151 Product Block Editor: Add the fundamental support and map `Text` and `Integer` attribute inputs to currently available generic blocks
  src/Admin/Input/Checkbox.php
  src/Admin/Input/Decimal.php
  src/Admin/Input/Input.php
  src/Admin/Input/InputInterface.php
  src/Admin/Input/Integer.php
  src/Admin/Input/SelectWithTextInput.php
  src/Admin/Input/Text.php
  src/Admin/Product/Attributes/AttributesBlock.php
  src/Admin/Product/Attributes/AttributesForm.php
  src/Admin/Product/Attributes/AttributesTab.php
  src/Admin/Product/Attributes/AttributesTrait.php
  src/Admin/Product/Attributes/Input/MultipackInput.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  tests/Unit/Admin/Input/InputCollectionTest.php
  tests/Unit/Admin/Input/InputTest.php
  tests/Unit/Admin/Product/Attributes/AttributesBlockTest.php
  tests/Unit/Admin/Product/Attributes/AttributesFormTest.php
  tests/Unit/Admin/Product/Attributes/Input/AttributeInputCollectionTest.php
Labels: type: enhancement, changelog: add

#2164 Product Block Editor: Add the fundamental setup for the custom product blocks and map `Select` and `BooleanSelect` inputs to the custom select field block
  .eslintrc.js
  .externalized.json
  js/src/blocks/README.md
  js/src/blocks/components/index.js
  js/src/blocks/components/label.js
  js/src/blocks/index.js
  js/src/blocks/product-select-field/block.json
  js/src/blocks/product-select-field/edit.js
  package-lock.json
  package.json
  src/Admin/Input/Select.php
  src/Admin/Product/Attributes/AttributesBlock.php
  src/Assets/BaseAsset.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  tests/Unit/Admin/Input/InputCollectionTest.php
  tests/Unit/Admin/Product/Attributes/AttributesBlockTest.php
  tests/Unit/Admin/Product/Attributes/Input/AttributeInputCollectionTest.php
  tests/Unit/Assets/ScriptAssetTest.php
  tests/data/blocks.js
  tests/data/existing-block/block.json
  webpack.config.js
Labels: type: enhancement, changelog: add

#2190 API Pull - Notify when product changes
  src/Google/NotificationsService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Product/SyncerHooks.php
  tests/Unit/Google/NotificationsServiceTest.php
  tests/Unit/Product/SyncerHooksTest.php
Labels: type: enhancement, changelog: add
