Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-04, with the labels that each got.

#1939 Fix the fatal errors caused by adding any US Armed Forces location to WC Shipping setting
  src/Shipping/ZoneLocationsParser.php
  tests/Unit/Shipping/ZoneLocationsParserTest.php
Labels: type: bug, changelog: fix

#1926 Add redirects between dashboard and start
  src/Admin/Redirect.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Menu/Dashboard.php
  src/Menu/GetStarted.php
  tests/Unit/Admin/RedirectsTest.php
Labels: changelog: tweak

#1940 Prevent creating assets for non PMax campaigns
  js/src/constants.js
  js/src/dashboard/all-programs-table-card/edit-program-button/index.js
  js/src/dashboard/all-programs-table-card/index.js
  js/src/dashboard/all-programs-table-card/index.test.js
  js/src/pages/edit-paid-ads-campaign/index.js
Labels: type: bug, changelog: fix

#1941 Report the Ads account currency in Woo marketing dashboard
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/MultichannelMarketing/GLAChannel.php
  tests/Unit/MultichannelMarketing/GLAChannelTest.php
Labels: type: bug, changelog: fix

#1950 [SEMGREP] - Prevent Semgrep warnings in add_query vars and in Scripts loader
  src/API/Site/Controllers/Jetpack/AccountController.php
  src/Assets/ScriptWithBuiltDependenciesAsset.php
Labels: changelog: dev

#1952 Prefix Psr Container Package
  bin/prefix-vendor-namespace.php
  composer.json
  composer.lock
  google-listings-and-ads.php
  src/API/Google/Middleware.php
  src/API/Google/Settings.php
  src/API/Site/Controllers/BaseReportsController.php
  src/API/Site/Controllers/MerchantCenter/ShippingTimeController.php
  src/API/Site/RESTControllers.php
  src/Ads/AccountService.php
  src/ConnectionTest.php
  src/Container.php
  src/Infrastructure/GoogleListingsAndAdsPlugin.php
  src/Internal/ContainerAwareTrait.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Internal/Interfaces/ContainerAwareInterface.php
  src/MerchantCenter/AccountService.php
  src/Tracking/EventTracking.php
  tests/Framework/ContainerAwareUnitTest.php
  tests/Unit/MerchantCenter/ValidateAddressTest.php
Labels: type: bug, changelog: fix
