Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-06, with the labels that each got.

#1970 Update Google API Client to 2.15 and Google Ads API to V13
  bin/GoogleAdsCleanupServices.php
  composer.json
  composer.lock
  src/API/Google/Ads.php
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignBudget.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/AssetFieldType.php
  src/API/Google/BillingSetupStatus.php
  src/API/Google/CallToActionType.php
  src/API/Google/CampaignStatus.php
  src/API/Google/CampaignType.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/Query/AdsQuery.php
  src/API/Google/Query/AdsReportQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/Google/Ads/GoogleAdsClient.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsConversionActionTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
Labels: changelog: update

#1974 Release/2.4.7 - Merge release branch into trunk
  .github/workflows/php-unit-tests.yml
  bin/GoogleAdsCleanupServices.php
  changelog.txt
  composer.json
  composer.lock
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
  src/API/Google/Ads.php
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignBudget.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/AssetFieldType.php
  src/API/Google/BillingSetupStatus.php
  src/API/Google/CallToActionType.php
  src/API/Google/CampaignStatus.php
  src/API/Google/CampaignType.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/Query/AdsQuery.php
  src/API/Google/Query/AdsReportQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/Google/Ads/GoogleAdsClient.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  src/Hooks/README.md
  src/Integration/WooCommerceProductBundles.php
  src/Product/WCProductAdapter.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsConversionActionTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: changelog: none

#1977 Prefix Psr Http Message Package
  bin/prefix-vendor-namespace.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  tests/Tools/HelperTrait/GuzzleClientTrait.php
Labels: type: bug, changelog: fix

#1978 Release/2.4.8 - Merge release branch into trunk
  bin/prefix-vendor-namespace.php
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  tests/Tools/HelperTrait/GuzzleClientTrait.php
Labels: changelog: none

#1980 Prefix psr/http-client package
  bin/prefix-vendor-namespace.php
  src/API/Google/ApiExceptionTrait.php
  src/API/Google/Connection.php
  src/API/Google/Middleware.php
Labels: type: bug, changelog: fix

#1984 Release/2.4.10
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1985 Release/2.4.10
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1987 Fix the parent options being rendered as the selected tags in the TreeSelectControl
  js/src/components/tree-select-control/index.js
  js/src/components/tree-select-control/index.test.js
Labels: type: bug, changelog: fix

#1982 Add prepare release workflow
  .github/workflows/prepare-release.yml
Labels: changelog: none

#1989 Enable unit testing for PHP 8.1
  .github/workflows/php-unit-tests.yml
Labels: changelog: dev

#1990 Add Empty Data placeholder in Attribute Mapping Table
  js/src/attribute-mapping/attribute-mapping-table.js
Labels: changelog: tweak

#1988 Add a step to publish the latest extension build for the `develop` branch
  .github/workflows/build.yml
  README.md
Labels: changelog: dev

#1995 Remove an unused hook `useCallbackOnceEffect`
  js/src/hooks/useCallbackOnceEffect.js
  js/src/hooks/useCallbackOnceEffect.test.js
Labels: changelog: dev

#1994 Avoid continuing to sync settings with GMC after shipping time API failed
  js/src/data/actions.js
  js/src/hooks/useSaveShippingRates.js
  js/src/hooks/useSaveShippingTimes.js
Labels: type: bug, changelog: fix

#1996 Show API error messages when errors occur in the code of wp-data store and simplify some error messages
  js/src/data/actions.js
  js/src/data/resolvers.js
  js/src/utils/handleError.js
  js/src/utils/handleError.test.js
Labels: changelog: tweak

#2000 Replace undefined $border-width-focus var
  js/src/components/app-tab-nav/index.scss
Labels: type: bug, changelog: fix

#2001 Set Node/npm Engines
  .npmrc
  package.json
Labels: changelog: dev

#2003 Add the built-in WP REST API validation to `CountryCodeTrait` to avoid errors when clearing all audience countries in the onboarding flow
  src/API/Site/Controllers/Ads/BudgetRecommendationController.php
  src/API/Site/Controllers/Ads/CampaignController.php
  src/API/Site/Controllers/CountryCodeTrait.php
  tests/Unit/API/Site/Controllers/Ads/BudgetRecommendationControllerTest.php
  tests/Unit/API/Site/Controllers/Ads/CampaignControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeBatchControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/TargetAudienceControllerTest.php
Labels: type: bug, changelog: fix
