Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-10, with the labels that each got.

#2105 E2E tests: Onboarding Step 4 - Complete your campaign
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/customer.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/page.js
  tests/e2e/utils/pages/setup-ads/setup-ads-accounts.js
  tests/e2e/utils/pages/setup-ads/setup-budget.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
  tests/e2e/utils/pages/setup-mc/step-2-product-listings.js
  tests/e2e/utils/pages/setup-mc/step-4-complete-campaign.js
Labels: changelog: dev

#2121 Add E2E tests for Setup Google Ads - Step 2
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/dashboard/edit-free-listings.test.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/mock-requests.js
Labels: type: enhancement, changelog: dev

#2122 Fix E2E tests - Track gtag event on specific page
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/utils/track-event.js
Labels: type: bug, changelog: fix

#2126 Fix the auto-refresh processing of billing status in the ads onboarding flow
  js/src/components/adaptive-form/adaptive-form.js
  js/src/components/adaptive-form/adaptive-form.test.js
Labels: type: bug, changelog: fix

#2127 Fix the issue that may create two campaigns after completing ads onboarding
  js/src/components/paid-ads/billing-card/billing-setup-card.test.js
  js/src/components/paid-ads/billing-card/useAutoCheckBillingStatusEffect.js
Labels: type: bug, changelog: fix

#2133 Declare Compatibility for cart_checkout_blocks
  google-listings-and-ads.php
Labels: changelog: tweak

#2135 Add correct Destinations for Supported Countries in Coupons
  src/Coupon/WCCouponAdapter.php
  src/Google/GoogleHelper.php
  tests/Unit/Coupon/WCCouponAdapterTest.php
Labels: changelog: tweak

#2137 Add tracking for campaign count
  src/API/Google/AdsCampaign.php
  src/API/Google/MerchantMetrics.php
  src/Ads/AccountService.php
  src/Options/TransientsInterface.php
  src/Tracking/TrackerSnapshot.php
  tests/Unit/API/Google/AdsCampaignTest.php
  tests/Unit/Ads/AccountServiceTest.php
Labels: changelog: tweak

#2140 Record tracking events for moving steps on the campaign creation and editing pages
  js/src/constants.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/utils/recordEvent.js
  src/Tracking/README.md
Labels: type: enhancement, changelog: add
