Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-05, with the labels that each got.

#1956 Release 2.4.4
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1958 Fix the problem of missing spaces between the Card layouts on the Get Started page
  js/src/get-started-page/index.scss
Labels: type: bug, changelog: fix

#1927 Fix attributes in variants for attribute mapping
  src/Product/WCProductAdapter.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Product/AttributeMapping/AttributeMappingHelperTest.php
  tests/Unit/Product/AttributeMapping/AttributeMappingWCProductAdapterTest.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: bug, impact: high, changelog: fix

#1960 Release/2.4.5
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1961 Release/2.4.5
  changelog.txt
  google-listings-and-ads.php
  js/src/get-started-page/index.scss
  package-lock.json
  package.json
  readme.txt
  src/Product/WCProductAdapter.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Product/AttributeMapping/AttributeMappingHelperTest.php
  tests/Unit/Product/AttributeMapping/AttributeMappingWCProductAdapterTest.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: changelog: none

#1964 Update the token in backlog-automation.yml to the PAT of `botwoo` account
  .github/workflows/backlog-automation.yml
Labels: changelog: dev

#1962 Filters for manually mapping product IDs
  src/Product/ProductHelper.php
  src/Product/WCProductAdapter.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: enhancement, changelog: add

#1967 Adapt the `is_virtual` property value for Product Bundles to avoid applying incorrect shipping rates in products sync
  src/Hooks/README.md
  src/Integration/WooCommerceProductBundles.php
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: bug, changelog: fix

#1968 Fix the coverage report of PHP unit tests not being performed in GitHub Actions
  .github/workflows/php-unit-tests.yml
Labels: changelog: dev
