Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-07, with the labels that each got.

#2004 Add PHP tests for `CountryCodeTrait` and two related API controllers
  tests/Unit/API/Site/Controllers/CountryCodeTraitTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeBatchControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/TargetAudienceControllerTest.php
Labels: changelog: dev

#2008 Add client name and version as request headers
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/PluginHelper.php
  tests/Unit/API/ClientTest.php
Labels: type: enhancement, changelog: add

#2009 Update Asset Groups Texts
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/faqs-section.js
  js/src/dashboard/all-programs-table-card/campaign-assets-tour.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
Labels: changelog: tweak

#2007 Adjust the infrastructure to uniform the error messages returned from Google Shopping Content service
  src/API/Google/Ads.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/Connection.php
  src/API/Google/ExceptionTrait.php
  src/API/Google/Merchant.php
  src/API/Google/Middleware.php
  src/Exception/MerchantApiException.php
  src/MerchantCenter/ContactInformation.php
  src/MerchantCenter/MerchantCenterService.php
  tests/Tools/HelperTrait/MerchantTrait.php
  tests/Unit/API/Google/MerchantTest.php
  tests/Unit/MerchantCenter/ContactInformationTest.php
Labels: changelog: tweak

#2012 Provide more detailed error reasons when unable to complete site verification
  src/API/Google/SiteVerification.php
  tests/Unit/API/Google/SiteVerificationTest.php
Labels: changelog: tweak

#2011 Add Tip component when assets are imported
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/asset-group-section.scss
  js/src/components/paid-ads/asset-group/asset-group-section.test.js
  js/src/components/paid-ads/campaign-assets-form.js
Labels: type: enhancement, changelog: tweak

#2015 Apply `AdaptiveForm` and its abilities to steps 2 and 3 of the onboarding flow for higher code consistent
  js/src/components/free-listings/choose-audience-section/choose-audience-section.js
  js/src/components/free-listings/configure-product-listings/shipping-time-section.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-form.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/index.js
  js/src/components/free-listings/configure-product-listings/tax-rate.js
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/components/pre-launch-check-item/index.js
  js/src/components/shipping-rate-section/flat-shipping-rates-input-cards.js
  js/src/components/shipping-rate-section/shipping-rate-section.js
  js/src/setup-mc/setup-stepper/store-requirements/index.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
Labels: changelog: dev

#2022 PHP 8.2 Deprecation Messages
  .github/workflows/php-unit-tests.yml
  src/Admin/MetaBox/ChannelVisibilityMetaBox.php
  src/Admin/MetaBox/CouponChannelVisibilityMetaBox.php
  src/Admin/Product/Attributes/AttributesTab.php
  src/Proxies/WC.php
  tests/Unit/API/Site/Controllers/CountryCodeTraitTest.php
Labels: type: bug, changelog: fix

#2023 Add automerge-released-trunk workflow
  .github/workflows/post-release-automerge.yml
Labels: changelog: dev

#2019 Show validation errors on step 2 of the onboarding flow when unable to continue
  js/src/components/app-input-number-control/index.js
  js/src/components/app-input-number-control/index.test.js
  js/src/components/free-listings/choose-audience-section/choose-audience-section.js
  js/src/components/free-listings/configure-product-listings/__snapshots__/checkErrors.test.js.snap
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
  js/src/components/free-listings/configure-product-listings/shipping-time-section.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/index.scss
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/index.scss
  js/src/components/free-listings/configure-product-listings/tax-rate.js
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/asset-group/asset-group-card.scss
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js
  js/src/components/shipping-rate-section/flat-shipping-rates-input-cards.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-card.js
  js/src/components/shipping-rate-section/offer-free-shipping-card.js
  js/src/components/validation-errors/index.js
  js/src/components/validation-errors/validation-errors.js
  js/src/components/validation-errors/validation-errors.scss
  js/src/components/validation-errors/validation-errors.test.js
Labels: changelog: update

#2025 Show validation errors on step 3 of the onboarding flow when unable to continue
  js/src/components/contact-information/__snapshots__/mapStoreAddressErrors.test.js.snap
  js/src/components/contact-information/index.js
  js/src/components/contact-information/mapStoreAddressErrors.js
  js/src/components/contact-information/mapStoreAddressErrors.test.js
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  js/src/components/contact-information/phone-number-card/phone-number-card.scss
  js/src/components/contact-information/store-address-card.js
  js/src/hooks/types.js
  js/src/hooks/useStoreAddress.js
  js/src/settings/edit-store-address.js
  js/src/setup-mc/setup-stepper/store-requirements/index.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/checkErrors.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/checkErrors.test.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
  src/Tracking/README.md
Labels: changelog: update

#2027 Add JavaScript tests for the `PhoneNumberCard` component
  js/src/components/contact-information/phone-number-card/phone-number-card.test.js
Labels: changelog: dev
