Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-08, with the labels that each got.

#2031 Add JavaScript tests for the `EditPhoneNumberContent` and `VerifyPhoneNumberContent` components
  js/src/components/contact-information/phone-number-card/edit-phone-number-content.test.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.test.js
Labels: changelog: dev

#2039 WP 6.3 Compatibility: Fix the errors of "setImmediate is not defined"
  js/src/components/adaptive-form/adaptive-form.js
  js/src/components/adaptive-form/adaptive-form.test.js
  js/src/hooks/useCroppedImageSelector/useCroppedImageSelector.js
Labels: type: bug, priority: critical, changelog: fix

#2033 Make the gtag-events.js work with the Fast Refresh development mode
  src/Admin/Admin.php
  src/Google/GlobalSiteTag.php
Labels: changelog: dev

#2050 Fix e2e tests
  tests/e2e/docker/initialize.sh
Labels: type: bug, changelog: dev

#2047 Use `merge-trunk-develop-pr` action
  .github/workflows/post-release-automerge.yml
  .github/workflows/post-release-merge.yml
Labels: changelog: dev

#2036 Externalize `Flex`, `Card` and their associated group components imported from `@wordpress/components`
  js/src/attribute-mapping/attribute-mapping-sync.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/components/account-card/index.js
  js/src/components/connected-icon-label/index.js
  js/src/components/contact-information/phone-number-card/edit-phone-number-content.js
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  js/src/components/contact-information/phone-number-card/verification-code-control.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.js
  js/src/components/contact-information/store-address-card.js
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-mc-account-card/connect-mc/index.js
  js/src/components/google-mc-account-card/reclaim-url-card/index.js
  js/src/components/google-mc-account-card/switch-url-card/index.js
  js/src/components/paid-ads/billing-card/billing-card.js
  js/src/components/paid-ads/campaign-preview/campaign-preview-card.js
  js/src/components/paid-ads/campaign-preview/mockup-search.js
  js/src/components/tree-select-control/options.js
  js/src/dashboard/summary-section/summary-card.js
  js/src/external-components/woocommerce/compare-filter/index.js
  js/src/get-started-page/benefits-card/index.js
  js/src/get-started-page/customer-quotes-card/index.js
  js/src/get-started-page/features-card/index.js
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/product-feed/issues-table-card/index.js
  js/src/product-feed/issues-table-card/issues-table.js
  js/src/product-feed/product-feed-table-card/index.js
  js/src/product-feed/product-statistics/index.js
  js/src/product-feed/product-statistics/status-box/status.js
  js/src/product-feed/review-request/review-request-notice.js
  js/src/settings/edit-store-address.js
  js/src/settings/linked-accounts.js
  js/src/settings/reconnect-google-account/disconnect-google-account-card.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/wcdl/section/card/body/index.js
  js/src/wcdl/section/card/footer/index.js
  js/src/wcdl/section/card/index.js
Labels: changelog: dev

#2037 Externalize `Dashicon`, `Icon`, `Notice` and `Tip` components imported from `@wordpress/components`
  .externalized.json
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.js
  js/src/components/different-currency-notice.js
  js/src/components/dismissible-notice/index.js
  js/src/components/dismissible-notice/index.test.js
  js/src/components/google-mc-account-card/reclaim-url-card/index.js
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/budget-section/budget-recommendation/index.js
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/get-started-page/unsupported-notices/index.js
  js/src/product-feed/issues-table-card/issues-solved.js
  js/src/product-feed/product-feed-table-card/edit-visibility-action.js
  js/src/product-feed/product-feed-table-card/index.scss
  js/src/product-feed/review-request/review-request-modal.js
  js/src/reports/programs/campaign-name-cell.scss
  js/src/settings/reconnect-google-account/disconnect-google-account-card.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.scss
  webpack.config.js
Labels: changelog: dev

#2042 Externalize `NavigableMenu`, `Dropdown` and `Modal` components imported from `@wordpress/components`
  js/src/components/app-modal/index.js
  js/src/components/app-sub-nav/index.js
  js/src/components/app-tab-nav/index.js
  js/src/css/shared/_gutenberg-components.scss
  js/src/external-components/woocommerce/filter-picker/index.js
  js/src/external-components/wordpress/guide/index.js
Labels: changelog: dev

#2046 Fetch WC L-1 versions
  .github/workflows/php-unit-tests.yml
Labels: changelog: dev

#2054 Externalize all `*Control` components imported from `@wordpress/components`
  .externalized.json
  js/src/components/app-input-control/index.js
  js/src/components/app-radio-content-control/index.js
  js/src/components/app-radio-content-control/index.scss
  js/src/components/app-select-control/index.js
  js/src/components/app-standalone-toggle-control/index.js
  js/src/components/app-standalone-toggle-control/index.scss
  js/src/components/contact-information/phone-number-card/edit-phone-number-content.js
  js/src/components/free-listings/choose-audience-section/choose-audience-section.js
  js/src/components/google-ads-account-card/terms-modal/index.js
  js/src/components/google-mc-account-card/terms-modal/index.js
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/audience-section.js
  js/src/components/paid-ads/audience-section.scss
  js/src/components/pre-launch-check-item/index.js
  js/src/css/shared/_gutenberg-components.scss
  js/src/product-feed/product-feed-table-card/index.js
  js/src/product-feed/review-request/review-request-modal.js
  js/src/reports/compare-table-card.js
  js/src/settings/disconnect-modal/confirm-modal.js
Labels: changelog: dev

#2056 Externalize all `@wordpress` packages via DEWP
  .eslintrc.js
  .externalized.json
  js/src/components/app-button/index.js
  js/src/components/app-radio-content-control/index.scss
  js/src/components/app-standalone-toggle-control/index.scss
  js/src/components/app-tooltip/index.js
  js/src/components/dismissible-notice/index.js
  js/src/components/dismissible-notice/index.test.js
  js/src/components/faqs-panel/index.js
  js/src/components/google-ads-account-card/connected-google-ads-account-card.js
  js/src/components/help-popover/index.js
  js/src/components/paid-ads/asset-group/final-url-card.js
  js/src/components/paid-ads/assetSpecs.js
  js/src/components/paid-ads/audience-section.scss
  js/src/components/paid-ads/billing-card/billing-setup-card.js
  js/src/components/pre-launch-check-item/index.js
  js/src/css/shared/_gutenberg-components.scss
  js/src/external-components/woocommerce/compare-filter/index.js
  js/src/external-components/woocommerce/filter-picker/index.js
  js/src/external-components/wordpress/guide/finish-button.js
  js/src/external-components/wordpress/guide/index.js
  js/src/external-components/wordpress/guide/page-control.js
  js/src/get-started-page/customer-quotes-card/index.js
  js/src/get-started-page/features-card/index.js
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/product-feed/product-feed-table-card/edit-visibility-action.js
  js/src/product-feed/product-feed-table-card/index.scss
  js/src/product-feed/product-statistics/index.js
  js/src/reports/programs/campaign-name-cell.scss
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.scss
  package.json
  webpack.config.js
Labels: changelog: dev

#2060 Add action for Hook Documentation Generation
  .github/workflows/php-hook-documentation.yml
  src/Hooks/README.md
Labels: changelog: dev

#2061 Update Google Ads API to V14 and Content API packages
  bin/GoogleAdsCleanupServices.php
  bin/prefix-vendor-namespace.php
  composer.json
  composer.lock
  src/API/Google/Ads.php
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignBudget.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/AssetFieldType.php
  src/API/Google/BillingSetupStatus.php
  src/API/Google/CallToActionType.php
  src/API/Google/CampaignStatus.php
  src/API/Google/CampaignType.php
  src/API/Google/ExceptionTrait.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/Query/AdsQuery.php
  src/API/Google/Query/AdsReportQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/Google/Ads/GoogleAdsClient.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsConversionActionTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
Labels: changelog: update

#2059 Apply consistent admin theme colors to common UI components
  js/src/components/pre-launch-check-item/index.scss
  js/src/components/stepper/top-bar/index.js
  js/src/components/stepper/top-bar/index.scss
  js/src/external-components/wordpress/guide/icons.js
  js/src/external-components/wordpress/guide/index.js
  js/src/external-components/wordpress/guide/index.scss
  js/src/external-components/wordpress/guide/page-control.js
  js/src/get-started-page/unsupported-notices/index.js
  js/src/get-started-page/unsupported-notices/index.scss
Labels: changelog: tweak

#2065 Remove HookDocsGenerator legacy file
  bin/HooksDocsGenerator.php
  package.json
Labels: changelog: dev

#2069 Override vulnerability packages: `xmlhttprequest-ssl` and `ws`
  .nvmrc
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.js
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/components/google-account-card/connect-google-account-card.js
  js/src/components/google-account-card/useSwitchGoogleAccount.js
  js/src/components/google-ads-account-card/create-account.js
  js/src/components/google-mc-account-card/connected-google-mc-account-card.js
  js/src/components/google-mc-account-card/create-account.js
  js/src/components/google-mc-account-card/google-mc-account-card.js
  js/src/components/google-mc-account-card/reclaim-url-card/index.js
  js/src/components/google-mc-account-card/switch-url-card/index.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/billing-card/billing-card.js
  js/src/components/paid-ads/validateAssetGroup.test.js
  js/src/components/shipping-rate-section/estimated-shipping-rates-card/estimated-shipping-rates-card.js
  js/src/components/shipping-rate-section/minimum-order-card/groupShippingRatesByCurrencyFreeShippingThreshold.test.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-card.js
  js/src/dashboard/all-programs-table-card/index.js
  js/src/dashboard/app-date-range-filter-picker/getDateQuery.js
  js/src/edit-free-campaign/index.js
  js/src/external-components/woocommerce/filter-picker/index.js
  js/src/external-components/woocommerce/filters/index.js
  js/src/hooks/useCategories.js
  js/src/hooks/useExistingGoogleAdsAccounts.js
  js/src/hooks/useGoogleAccount.js
  js/src/hooks/useGoogleMCAccount.js
  js/src/hooks/useJetpackAccount.js
  js/src/hooks/useMCIssuesTotals.js
  js/src/hooks/useTargetAudienceFinalCountryCodes.js
  js/src/product-feed/product-feed-table-card/index.js
  js/src/product-feed/review-request/index.js
  js/src/reports/products/products-report-filters.js
  js/src/reports/programs/index.js
  js/src/reports/programs/programs-report-filters.js
  js/src/reports/utils.test.js
  js/src/settings/disconnect-modal/confirm-modal.js
  js/src/setup-ads/ads-stepper/setup-billing/billing-saved-card/index.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
  js/src/setup-mc/setup-stepper/useTargetAudienceWithSuggestions.js
  package-lock.json
  package.json
Labels: changelog: dev

#2073 Update trigger method in Hooks Generator Workflow
  .github/workflows/php-hook-documentation.yml
Labels: changelog: dev

#2074 Fix/attributes taonomy parent
  src/Product/WCProductAdapter.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/Product/AttributeMapping/AttributeMappingWCProductAdapterTest.php
Labels: type: bug, changelog: fix

#2077 Clean up remaining WC < 6.8 workarounds
  js/src/dashboard/all-programs-table-card/index.js
  js/src/hooks/useNavigateAwayPromptEffect.js
Labels: changelog: dev
