Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-09, with the labels that each got.

#2072 Externalize all `@woocommerce` packages via DEWP and remove the selective bundling implementation
  .externalized.json
  Working with DEWP.md
  jest.config.js
  js/src/jsconfig.json
  package-lock.json
  package.json
  webpack.config.js
Labels: changelog: dev

#2082 Update DEWP-related tools and docs
  Working with DEWP.md
  bin/list-woo-dewped.mjs
  package.json
Labels: changelog: dev

#2081 E2E tests: Onboarding Step 1 - Set up accounts - Connect Merchant Center account
  tests/e2e/global-setup.js
  tests/e2e/specs/dashboard/edit-free-listings.test.js
  tests/e2e/specs/get-started.test.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/utils/constants.js
  tests/e2e/utils/customer.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/dashboard.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
Labels: changelog: dev

#2087 WooCommerce Subscriptions compatibility: Fix the visible issue of the product data tab and meta box for some unsupported product types
  .eslintrc.js
  .externalized.json
  js/src/constants.js
  js/src/product-attributes/custom-inputs.js
  js/src/product-attributes/index.js
  js/src/product-attributes/select-with-text-input/index.js
  src/Admin/Admin.php
  src/Admin/MetaBox/ChannelVisibilityMetaBox.php
  src/Admin/Product/Attributes/AttributesTab.php
  src/Assets/AssetsHandler.php
  src/Assets/AssetsHandlerInterface.php
  src/Google/GlobalSiteTag.php
  src/Infrastructure/GoogleListingsAndAdsPlugin.php
  src/Integration/WooCommerceSubscriptions.php
  src/Internal/DependencyManagement/IntegrationServiceProvider.php
  src/Product/ProductSyncer.php
  webpack.config.js
Labels: type: bug, changelog: fix

#2093 Fix undesired margin in Paid Campaign Creation Success modal
  js/src/dashboard/campaign-creation-success-guide/index.scss
Labels: type: bug, changelog: fix

#2096 [WC 8.1] - Fix Selector and Target for Add To Cart
  js/src/dashboard/campaign-creation-success-guide/index.scss
  js/src/gtag-events/index.js
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/utils/customer.js
Labels: type: bug, changelog: fix

#2088 E2E tests: Onboarding Step 2 - Configure product listings
  tests/e2e/global-setup.js
  tests/e2e/specs/get-started.test.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/utils/constants.js
  tests/e2e/utils/customer.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
  tests/e2e/utils/pages/setup-mc/step-2-product-listings.js
Labels: changelog: dev

#2092 E2E tests: Onboarding Step 3 - Confirm store requirements
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/specs/setup-mc/step-3-confirm-store-requirements.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-mc/step-3-confirm-store-requirements.js
Labels: changelog: dev

#2097 E2E - Ads Paid Campaign Step 1 - Connect Ads Account
  tests/e2e/specs/add-paid-campaigns/step-1-accounts.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/dashboard.js
  tests/e2e/utils/pages/setup-ads/setup-ads-accounts.js
Labels: changelog: dev

#2099 Performance issue: Move GoogleAdsFailures::init to error_handler middleware
  src/Google/Ads/GoogleAdsClient.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
Labels: type: bug, changelog: fix

#2106 Add section to privacy policy guide
  src/Admin/Admin.php
Labels: type: enhancement, changelog: add

#2107 Add UTM parameters to documentation link
  src/PluginHelper.php
Labels: changelog: tweak

#2112 Ignore the directory of E2E test results to avoid eslint getting stuck
  .eslintignore
Labels: changelog: dev

#2108 Adjust the conditions for loading assets and configure lazy loading and code splitting
  js/src/index.js
  package-lock.json
  package.json
  src/Admin/Admin.php
  webpack.config.js
Labels: changelog: dev

#2111 Add missing tracking to onboarding when changing steps and reduce their confusing properties
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/top-bar/index.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/top-bar/index.js
  js/src/utils/recordEvent.js
  src/Tracking/README.md
Labels: type: enhancement, changelog: add

#2116 Fix a few E2E tests that may fail due to network time lag or no fallback requests
  tests/e2e/specs/setup-mc/step-3-confirm-store-requirements.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-mc/step-3-confirm-store-requirements.js
Labels: changelog: dev

#2117 Update the `caniuse-lite` package to the latest
  package-lock.json
Labels: changelog: dev

#2110 Remove AttributeMapping new feature inbox notification
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Notes/AttributeMappingNewFeature.php
  src/PluginHelper.php
  tests/Unit/Notes/AttributeMappingNewFeatureTest.php
Labels: type: bug, changelog: fix
