Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-03, with the labels that each got.

#1911 PMax Assets: Adjust the tip of the disabled "Add image" buttons
  js/src/components/paid-ads/__snapshots__/assetSpecs.test.js.snap
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/asset-group/images-selector.scss
  js/src/components/paid-ads/assetSpecs.js
  js/src/components/paid-ads/assetSpecs.test.js
Labels: changelog: tweak

#1913 PMax Assets - Update Error message for Duplicated images
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
Labels: changelog: tweak

#1914 Fix the blank Product Feed page after completing the onboarding flow
  js/src/external-components/wordpress/guide/index.js
Labels: type: bug, changelog: fix

#1918 Release/2.4.0
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AssetFieldType.php
  src/API/Google/CallToActionType.php
  src/API/Site/Controllers/Ads/AssetSuggestionsController.php
  src/Ads/AssetSuggestionsService.php
  src/Proxies/WP.php
  src/Utility/ArrayUtil.php
  src/Utility/DimensionUtility.php
  src/Utility/ImageUtility.php
Labels: changelog: none

#1923 Release 2.4.1 - WC & WP compatibility bump
  .github/workflows/php-unit-tests.yml
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
Labels: changelog: none

#1925 Leverage project write access for Dependabot.
  .github/workflows/backlog-automation.yml
Labels: type: bug, changelog: none

#1915 Add PHP Code coverage report as a GitHub action
  .codecov.yml
  .github/workflows/php-unit-tests.yml
  .gitignore
  phpunit.xml.dist
Labels: type: enhancement, changelog: dev

#1934 Use willReturnOnConsecutiveCalls instead of `at` for Unit Tests
  tests/Unit/MultichannelMarketing/GLAChannelTest.php
Labels: changelog: dev
