Repository woocommerce/google-listings-and-ads, pull requests merged in 2023-02, with the labels that each got.

#1867 Update phpunit to version 9.5
  .github/workflows/php-unit-tests.yml
  README.md
  composer.json
  composer.lock
Labels: changelog: update

#1866 Validate PHP Architecture 64 bits (Show notice)
  README.md
  google-listings-and-ads.php
  readme.txt
  src/Exception/InvalidVersion.php
  src/Internal/Requirements/VersionValidator.php
Labels: changelog: tweak

#1868 PMax Assets - Add portrait marketing images
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/Ads/AssetSuggestionsService.php
  tests/Unit/API/Site/Controllers/Ads/AssetGroupControllerTest.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: type: enhancement, changelog: add

#1870 PMax Assets - Fix issue when updating asset groups with empty paths
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
Labels: type: bug, changelog: fix

#1869 Pmax Assets - Override landscape logo
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
Labels: type: enhancement, changelog: add

#1877 PMax Assets: Stay on the same step after refreshing the campaign editing page
  js/src/dashboard/all-programs-table-card/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
Labels: type: bug, changelog: fix

#1878 PMax Assets - Tweak asset suggestions for the latests posts
  src/API/Google/AdsAssetGroupAsset.php
  src/Ads/AssetSuggestionsService.php
  tests/Unit/Ads/AssetSuggestionsServiceTest.php
Labels: changelog: tweak

#1872 PMax Assets: Preprocessing for API integrations
  js/src/components/paid-ads/__snapshots__/validateAssetGroup.test.js.snap
  js/src/components/paid-ads/ads-campaign.js
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/assets-loader.js
  js/src/components/paid-ads/asset-group/final-url-card.js
  js/src/components/paid-ads/assetSpecs.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/validateAssetGroup.js
  js/src/components/paid-ads/validateAssetGroup.test.js
  js/src/constants.js
  js/src/data/types.js
  src/API/Google/AdsAssetGroup.php
Labels: type: enhancement, changelog: add

#1873 PMax Assets: Support the portrait marketing images
  js/src/components/paid-ads/asset-group/images-selector.scss
  js/src/components/paid-ads/assetSpecs.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/validateAssetGroup.test.js
  js/src/constants.js
  js/src/data/types.js
Labels: changelog: update

#1886 Remove unnecessary filter param from woocommerce_loop_add_to_cart_link
  src/Google/GlobalSiteTag.php
Labels: changelog: tweak

#1890 Release/2.3.9
  bin/prefix-vendor-namespace.php
  changelog.txt
  google-listings-and-ads.php
  package-lock.json
  package.json
  readme.txt
  src/Exception/InvalidVersion.php
  src/Internal/Requirements/VersionValidator.php
Labels: changelog: none

#1874 PMax Assets: Integrate with APIs to load and save assets
  js/src/components/adaptive-form/adaptive-form.js
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/convertToAssetGroupUpdateBody.js
  js/src/components/paid-ads/convertToAssetGroupUpdateBody.test.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/constants.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/data/types.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
Labels: type: enhancement, changelog: add

#1884 PMax Assets: Add event tracking
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/assets-loader.js
  js/src/components/paid-ads/asset-group/final-url-card.js
  js/src/hooks/useCroppedImageSelector/useCroppedImageSelector.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/utils/recordEvent.js
Labels: type: enhancement, changelog: add

#1889 Remove PMax Migration Banners
  js/src/components/campaign-conversion-notice/conversion-statuses.js
  js/src/components/campaign-conversion-notice/index.js
  js/src/components/campaign-conversion-notice/index.scss
  js/src/components/campaign-conversion-notice/index.test.js
  js/src/components/campaign-conversion-notice/reports-notice.js
  js/src/components/campaign-conversion-notice/reports-notice.scss
  js/src/components/campaign-conversion-notice/reports-notice.test.js
  js/src/constants.js
  js/src/dashboard/index.js
  js/src/reports/programs/index.js
  js/src/utils/getConversionCampaignStatusNotice.js
  js/src/utils/getConversionCampaignStatusNotice.test.js
Labels: changelog: tweak

#1881 PMax Assets: Add FAQs for the assets
  js/src/components/faqs-panel/index.js
  js/src/components/faqs-panel/index.scss
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/faqs-section.js
  js/src/components/pre-launch-check-item/index.js
  js/src/css/shared/_gutenberg-components.scss
Labels: type: enhancement, changelog: add

#1893 Add "Working with DEWP.md" to exclude list
  composer.json
Labels: changelog: tweak

#1896 PMax Assets - Update Google Ads library v12
  .github/workflows/php-unit-tests.yml
  README.md
  bin/GoogleAdsCleanupServices.php
  bin/prefix-vendor-namespace.php
  changelog.txt
  composer.json
  composer.lock
  google-listings-and-ads.php
  js/src/components/campaign-conversion-notice/conversion-statuses.js
  js/src/components/campaign-conversion-notice/index.js
  js/src/components/campaign-conversion-notice/index.scss
  js/src/components/campaign-conversion-notice/index.test.js
  js/src/components/campaign-conversion-notice/reports-notice.js
  js/src/components/campaign-conversion-notice/reports-notice.scss
  js/src/components/campaign-conversion-notice/reports-notice.test.js
  js/src/constants.js
  js/src/dashboard/index.js
  js/src/reports/programs/index.js
  js/src/utils/getConversionCampaignStatusNotice.js
  js/src/utils/getConversionCampaignStatusNotice.test.js
  package-lock.json
  package.json
  readme.txt
  src/API/Google/Ads.php
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignBudget.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/AssetFieldType.php
  src/API/Google/BillingSetupStatus.php
  src/API/Google/CallToActionType.php
  src/API/Google/CampaignStatus.php
  src/API/Google/CampaignType.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/Query/AdsQuery.php
  src/API/Google/Query/AdsReportQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/Exception/InvalidVersion.php
  src/Google/Ads/GoogleAdsClient.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  src/Google/GlobalSiteTag.php
  src/Internal/Requirements/VersionValidator.php
  src/MerchantCenter/AccountService.php
  src/Shipping/LocationRate.php
  src/Shipping/ShippingRate.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsConversionActionTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
Labels: changelog: update

#1895 PMax Assets - Change asset group operations orders
  .github/workflows/php-unit-tests.yml
  README.md
  bin/GoogleAdsCleanupServices.php
  bin/prefix-vendor-namespace.php
  changelog.txt
  composer.json
  composer.lock
  google-listings-and-ads.php
  js/src/components/campaign-conversion-notice/conversion-statuses.js
  js/src/components/campaign-conversion-notice/index.js
  js/src/components/campaign-conversion-notice/index.scss
  js/src/components/campaign-conversion-notice/index.test.js
  js/src/components/campaign-conversion-notice/reports-notice.js
  js/src/components/campaign-conversion-notice/reports-notice.scss
  js/src/components/campaign-conversion-notice/reports-notice.test.js
  js/src/constants.js
  js/src/dashboard/index.js
  js/src/reports/programs/index.js
  js/src/utils/getConversionCampaignStatusNotice.js
  js/src/utils/getConversionCampaignStatusNotice.test.js
  package-lock.json
  package.json
  readme.txt
  src/API/Google/Ads.php
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignBudget.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/AssetFieldType.php
  src/API/Google/BillingSetupStatus.php
  src/API/Google/CallToActionType.php
  src/API/Google/CampaignStatus.php
  src/API/Google/CampaignType.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/Query/AdsQuery.php
  src/API/Google/Query/AdsReportQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/Exception/InvalidVersion.php
  src/Google/Ads/GoogleAdsClient.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  src/Google/GlobalSiteTag.php
  src/Internal/Requirements/VersionValidator.php
  src/MerchantCenter/AccountService.php
  src/Shipping/LocationRate.php
  src/Shipping/ShippingRate.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsConversionActionTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
Labels: type: bug, changelog: fix

#1882 PMax Assets: Tweak copy and add the optional labels
  js/src/components/paid-ads/__snapshots__/validateAssetGroup.test.js.snap
  js/src/components/paid-ads/asset-group/asset-field.js
  js/src/components/paid-ads/asset-group/asset-field.scss
  js/src/components/paid-ads/asset-group/asset-field.test.js
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/assets-loader.js
  js/src/components/paid-ads/asset-group/faqs-section.js
  js/src/components/paid-ads/asset-group/final-url-card.js
  js/src/components/paid-ads/assetSpecs.js
Labels: changelog: tweak

#1885 Add all new issues & PRs to Automata's project board.
  .github/workflows/backlog-automation.yml
Labels: type: enhancement, changelog: none

#1879 Add the tours to wp-data and the `useTour` hook
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/controls.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useTour.js
  js/src/hooks/useTour.test.js
Labels: type: enhancement, changelog: add

#1894 PMax Assets: Change the max number of image assets to be the shared max across the same group
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/asset-group/images-selector.js
  js/src/components/paid-ads/asset-group/images-selector.scss
  js/src/components/paid-ads/asset-group/images-selector.test.js
  js/src/components/paid-ads/assetSpecs.js
  js/src/components/paid-ads/assetSpecs.test.js
  js/src/css/abstracts/_variables.scss
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.scss
Labels: changelog: tweak

#1901 UX enhancement: Make the popover of the tooltip can be closed properly
  js/src/components/app-tooltip/index.js
  js/src/components/app-tooltip/index.scss
Labels: changelog: tweak

#1903 PMax Assets: Prevent the edited asset values from being reset after toggling asset fields
  js/src/components/paid-ads/asset-group/asset-field.js
  js/src/components/paid-ads/asset-group/asset-field.scss
  js/src/components/paid-ads/asset-group/asset-field.test.js
Labels: changelog: dev

#1905 Update maximum payload size in the test proxy
  tests/proxy/index.js
Labels: changelog: tweak

#1906 PMax Assets: Add a workaround to reset the selection area of jQuery plugin `imgAreaSelect`
  .eslintrc.js
  js/src/hooks/useCroppedImageSelector/useCroppedImageSelector.js
Labels: changelog: dev

#1907 PMax Assets: Prevent the edited asset values from being reset after switching between steps
  js/src/components/paid-ads/asset-group/asset-group-card.js
Labels: changelog: dev

#1908 PMax Assets: Support editing the Business name asset
  js/src/components/app-button/index.scss
  js/src/components/paid-ads/__snapshots__/validateAssetGroup.test.js.snap
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/asset-group/texts-editor.js
  js/src/components/paid-ads/asset-group/texts-editor.test.js
  js/src/components/paid-ads/assetSpecs.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/validateAssetGroup.js
  js/src/components/paid-ads/validateAssetGroup.test.js
Labels: changelog: update

#1909 PMax Assets: Prevent the button styles in `ImagesSelector` from overriding by AutomateWoo
  js/src/components/paid-ads/asset-group/images-selector.scss
Labels: changelog: tweak

#1904 Add feature flag for Multichannel Marketing Integration
  src/MultichannelMarketing/MarketingChannelRegistrar.php
Labels: changelog: none
