Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-03, with the labels that each got.

#2286 Avoid the test-data plugin occasionally missing in the E2E test environment
  .wp-env.json
  tests/e2e/bin/test-env-setup.sh
  tests/e2e/test-data/test-data.php
Labels: changelog: dev

#2287 Add support for Google Analytics for WooCommerce version 2.0.0
  src/Google/GlobalSiteTag.php
  src/Proxies/GoogleGtagJs.php
Labels: changelog: update

#2290 Add gtag consent mode v0 support
  README.md
  docs/gtag-consent-mode.md
  src/Google/GlobalSiteTag.php
  src/Proxies/GoogleGtagJs.php
Labels: type: enhancement, changelog: add

#2273 API PULL - Refactor Notification Jobs
  src/Google/NotificationsService.php
  src/Jobs/Notifications/AbstractItemNotificationJob.php
  src/Jobs/Notifications/AbstractNotificationJob.php
  src/Jobs/Notifications/CouponNotificationJob.php
  src/Jobs/Notifications/ProductNotificationJob.php
  src/Jobs/Notifications/SettingsNotificationJob.php
  src/Jobs/Notifications/ShippingNotificationJob.php
  src/Product/SyncerHooks.php
  tests/Unit/Google/NotificationsServiceTest.php
  tests/Unit/Jobs/AbstractItemNotificationJobTest.php
  tests/Unit/Jobs/AbstractNotificationJobTest.php
  tests/Unit/Jobs/CouponNotificationJobTest.php
  tests/Unit/Jobs/ProductNotificationJobTest.php
  tests/Unit/Jobs/SettingsNotificationJobTest.php
  tests/Unit/Jobs/ShippingNotificationJobTest.php
  tests/Unit/Product/SyncerHooksTest.php
Labels: changelog: tweak

#2277 Refactor product issues
  src/API/Google/MerchantReport.php
  src/DB/Table/MerchantIssueTable.php
  src/Jobs/UpdateMerchantProductStatuses.php
  src/MerchantCenter/MerchantStatuses.php
  tests/Unit/API/Google/MerchantReportTest.php
  tests/Unit/Jobs/UpdateMerchantProductStatusesTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: type: enhancement, changelog: add

#2296 WordPress 6.4 Compatibility: Fix the problem that the modal closed event is not sent when clicking on its overlay
  js/src/product-feed/submission-success-guide/index.js
Labels: type: bug, changelog: fix

#2302 Fix - Handle null value for getAdsLinks response
  src/API/Google/Merchant.php
Labels: type: bug, changelog: fix

#2294 Grant consent before checking the gtag events
  .wp-env.json
  tests/e2e/test-snippets/test-snippets.php
  tests/e2e/utils/track-event.js
Labels: type: bug, changelog: dev

#2298 Refactor Account and Presync issues
  src/API/Site/Controllers/MerchantCenter/IssuesController.php
  src/DB/ProductFeedQueryHelper.php
  src/Jobs/UpdateMerchantProductStatuses.php
  src/MerchantCenter/MerchantStatuses.php
  src/Product/ProductHelper.php
  tests/Unit/DB/ProductFeedQueryHelperTest.php
  tests/Unit/Jobs/UpdateMerchantProductStatusesTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: type: enhancement, changelog: add

#2312 Remove esc_js from add_inline_event_script
  src/Google/GlobalSiteTag.php
Labels: type: bug, changelog: fix

#2307 Fix undefined index for offers_free_shipping and free_shipping_threshold options
  src/API/Google/Settings.php
Labels: type: bug, changelog: fix

#2301 Fix exception when response.json() fails
  js/src/hooks/useApiFetchCallback.js
Labels: type: bug, changelog: fix

#2310 Update version of bcmath_compat and phpseclib packages
  composer.lock
Labels: changelog: update

#2314 Add require plugins header
  google-listings-and-ads.php
Labels: type: enhancement, changelog: add

#2291 API Pull - Add an API to return Google WPCOM App auth URL
  src/API/Site/Controllers/RestAPI/AuthController.php
  src/API/WP/NotificationsService.php
  src/API/WP/OAuthService.php
  src/ConnectionTest.php
  src/Coupon/SyncerHooks.php
  src/HelperTraits/Utilities.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Jobs/Notifications/AbstractNotificationJob.php
  src/Jobs/Notifications/CouponNotificationJob.php
  src/Jobs/Notifications/ProductNotificationJob.php
  src/Product/SyncerHooks.php
  src/Settings/SyncerHooks.php
  src/Shipping/SyncerHooks.php
  tests/Unit/API/Site/Controllers/RestAPI/AuthControllerTest.php
  tests/Unit/API/WP/NotificationsServiceTest.php
  tests/Unit/API/WP/OAuthServiceTest.php
  tests/Unit/Coupon/SyncerHooksTest.php
  tests/Unit/Jobs/AbstractItemNotificationJobTest.php
  tests/Unit/Jobs/AbstractNotificationJobTest.php
  tests/Unit/Product/SyncerHooksTest.php
  tests/Unit/Settings/SyncerHooksTest.php
  tests/Unit/Shipping/SyncerHooksTest.php
Labels: type: enhancement, changelog: add

#2319 Set woocommerce_gla_wcs_url to api.woocommerce.com
  src/PluginHelper.php
Labels: changelog: update

#2306 Refactor Product issues and fix issues when getting stats for a fresh MC account
  src/API/Google/MerchantReport.php
  src/DB/Table/MerchantIssueTable.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/AbstractProductSyncerBatchedJob.php
  src/Jobs/DeleteAllProducts.php
  src/Jobs/UpdateAllProducts.php
  src/Jobs/UpdateMerchantProductStatuses.php
  src/MerchantCenter/MerchantStatuses.php
  src/Notes/SetupCouponSharing.php
  src/Product/ProductRepository.php
  tests/Unit/DB/Table/MerchantIssueTableTest.php
  tests/Unit/Jobs/CleanupSyncedProductsTest.php
  tests/Unit/Jobs/DeleteAllProductsTest.php
  tests/Unit/Jobs/UpdateAllProductsTest.php
  tests/Unit/Jobs/UpdateMerchantProductStatusesTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: changelog: fix

#2297 Update is_gtag_page to support Google Analytics for WooCommerce version 2.0.0+
  src/Google/GlobalSiteTag.php
  src/Proxies/GoogleGtagJs.php
Labels: changelog: tweak

#2318 Update UI to handle Fetching Product Status with Action Scheduler Jobs
  js/src/data/actions.js
  js/src/hooks/useMCProductStatistics.js
  js/src/hooks/useMCProductStatistics.test.js
  js/src/product-feed/index.js
  js/src/product-feed/index.test.js
  js/src/product-feed/product-feed-table-card/index.js
  js/src/product-feed/product-statistics/index.js
  js/src/product-feed/product-statistics/index.scss
  js/src/product-feed/product-statistics/index.test.js
  js/src/product-feed/product-statistics/status-box/sync-status.js
  js/src/product-feed/useProductFeedPrefetch.js
  src/MerchantCenter/MerchantStatuses.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: changelog: update

#2320 Fix onboarding flow skipping to step 2
  src/Ads/AdsService.php
  src/MerchantCenter/MerchantCenterService.php
  tests/Unit/Ads/AdsServiceTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
Labels: changelog: tweak

#2325 API PULL - Add Notices inside GMC Card in Settings
  js/src/components/app-notice/index.js
  js/src/components/app-notice/index.scss
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/google-mc-account-card/connected-google-mc-account-card.js
  js/src/components/google-mc-account-card/google-mc-account-card.js
  src/API/Site/Controllers/DisconnectController.php
  src/API/Site/Controllers/RestAPI/AuthController.php
  src/ConnectionTest.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/MerchantCenter/AccountService.php
  tests/Unit/API/Site/Controllers/RestAPI/AuthControllerTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: type: enhancement, changelog: add

#2258 (R2.1f) Google tag enhanced conversion
  src/Google/GlobalSiteTag.php
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/test-data/test-data.php
  tests/e2e/utils/api.js
  tests/e2e/utils/track-event.js
Labels: changelog: update

#2327 Add E2E tests for the integration in Product Block Editor
  package-lock.json
  package.json
  tests/e2e/bin/test-env-setup.sh
  tests/e2e/config/default.json
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/specs/product-editor/block-integration.test.js
  tests/e2e/test-snippets/test-snippets.php
  tests/e2e/utils/api.js
  tests/e2e/utils/product-editor.js
Labels: changelog: dev

#2329 API PULL - Overview Stats - delete stale mc statuses
  src/DB/ProductMetaQueryHelper.php
  src/MerchantCenter/MerchantStatuses.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: type: enhancement, changelog: add

#2324 Display error message if update_merchant_product_statuses job throws an error
  js/src/hooks/useMCProductStatistics.js
  js/src/hooks/useMCProductStatistics.test.js
  js/src/product-feed/product-statistics/index.js
  js/src/product-feed/product-statistics/index.scss
  js/src/product-feed/product-statistics/index.test.js
  js/src/product-feed/product-statistics/status-box/sync-product-statistics.js
  src/DB/ProductMetaQueryHelper.php
  src/Jobs/UpdateMerchantProductStatuses.php
  src/MerchantCenter/MerchantStatuses.php
  tests/Unit/Jobs/UpdateMerchantProductStatusesTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: type: enhancement, changelog: add

#2326 API PULL - Block syncing when notifications are enabled
  package-lock.json
  src/API/WP/NotificationsService.php
  src/Coupon/CouponSyncer.php
  src/Coupon/SyncerHooks.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/AbstractCouponSyncerJob.php
  src/Jobs/AbstractProductSyncerBatchedJob.php
  src/Jobs/AbstractProductSyncerJob.php
  src/Jobs/ProductSyncerJobInterface.php
  src/MerchantCenter/MerchantCenterService.php
  src/Options/Options.php
  src/Options/OptionsInterface.php
  src/Product/ProductSyncer.php
  src/Product/SyncerHooks.php
  tests/Unit/Coupon/CouponSyncerTest.php
  tests/Unit/Coupon/SyncerHooksTest.php
  tests/Unit/Jobs/UpdateAllProductsTest.php
  tests/Unit/Jobs/UpdateProductsTest.php
  tests/Unit/Product/ProductSyncerTest.php
  tests/Unit/Product/SyncerHooksTest.php
Labels: type: enhancement, changelog: add

#2331 Update test proxy port
  tests/proxy/config.js
  tests/proxy/proxy.md
Labels: changelog: dev

#2338 API Pull - Update metadata for Coupons and Product after being notified.
  src/Coupon/CouponHelper.php
  src/Jobs/Notifications/AbstractItemNotificationJob.php
  src/Jobs/Notifications/CouponNotificationJob.php
  src/Jobs/Notifications/HelperNotificationInterface.php
  src/Jobs/Notifications/ProductNotificationJob.php
  src/Product/ProductHelper.php
  tests/Unit/Jobs/AbstractItemNotificationJobTest.php
Labels: type: enhancement, changelog: add
