Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-02, with the labels that each got.

#2231 Prevent Google API requests when disconnected
  src/Notes/ReviewAfterConversions.php
  src/Notes/SetupCouponSharing.php
  tests/Unit/Notes/ReviewAfterConversionsTest.php
  tests/Unit/Notes/SetupCouponSharingTest.php
Labels: type: bug, changelog: fix

#2233 Only sync selected categories as product type
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: bug, changelog: fix

#2221 Add Connection test for Api Pull Notification request
  src/ConnectionTest.php
Labels: type: enhancement, changelog: add

#2232 API PULL - Check notification statuses on processing
  src/Jobs/Notifications/ProductNotificationJob.php
  src/Product/ProductHelper.php
  tests/Unit/Jobs/ProductNotificationJobTest.php
Labels: changelog: tweak

#2238 Upload coverage report for JS unit tests to codecov
  .github/workflows/js-unit-tests.yml
  .github/workflows/php-unit-tests.yml
Labels: changelog: dev

#2114 Add QIT workflow
  .github/workflows/build.yml
  .github/workflows/run-qit.yml
Labels: changelog: dev

#2241 Fix the mismatched npm integrity checksum for `woocommerce-grow-jsdoc` and remove the use of storybook
  .gitattributes
  .github/workflows/storybook-workflow.yml
  .gitignore
  README.md
  js/src/components/tree-select-control/stories/index.js
  package-lock.json
  package.json
  storybook/main.js
  storybook/preview.js
  storybook/style.scss
Labels: changelog: dev

#2237 Product Block Editor: Add a custom block for prompting user to complete onboarding
  js/src/blocks/index.js
  js/src/blocks/product-onboarding-prompt/block.json
  js/src/blocks/product-onboarding-prompt/edit.js
  js/src/blocks/product-onboarding-prompt/editor.module.scss
  src/Admin/Product/ChannelVisibilityBlock.php
  src/Admin/ProductBlocksService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  tests/Unit/Admin/Product/ChannelVisibilityBlockTest.php
  tests/Unit/Admin/ProductBlocksServiceTest.php
Labels: type: enhancement, changelog: add

#2252 Add Shipping notifications
  src/ConnectionTest.php
  src/Google/NotificationsService.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/Notifications/ProductNotificationJob.php
  src/Jobs/Notifications/ShippingNotificationJob.php
  src/Shipping/SyncerHooks.php
  tests/Unit/Google/NotificationsServiceTest.php
  tests/Unit/Jobs/ProductNotificationJobTest.php
  tests/Unit/Jobs/ShippingNotificationJobTest.php
  tests/Unit/Shipping/SyncerHooksTest.php
Labels: type: enhancement, changelog: add

#2260 Prevent find_by_ids executing if no arguments are supplied
  src/Product/ProductRepository.php
  tests/Unit/Product/ProductRepositoryTest.php
Labels: type: bug, changelog: fix

#2249 Product Block Editor: Make it compatible with WooCommerce 8.6
  js/src/blocks/README.md
  src/Admin/Product/ChannelVisibilityBlock.php
  src/Admin/ProductBlocksService.php
  tests/Unit/Admin/ProductBlocksServiceTest.php
Labels: changelog: tweak

#2257 MC Product Statuses: Replace WP functions with WC functions
  src/API/Google/MerchantReport.php
  src/MerchantCenter/MerchantStatuses.php
  src/Product/ProductRepository.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
  tests/proxy/handler.js
Labels: type: enhancement, changelog: add

#2267 API PULL - Fix Notifications Body Encoding
  src/Google/NotificationsService.php
  tests/Unit/Google/NotificationsServiceTest.php
Labels: type: bug, changelog: fix

#2269 Product Block Editor: Declare feature compatibility
  google-listings-and-ads.php
Labels: changelog: tweak

#2213 Product Block Editor: Support the new product editor
  .eslintrc.js
  .externalized.json
  google-listings-and-ads.php
  js/src/blocks/README.md
  js/src/blocks/index.js
  js/src/blocks/product-channel-visibility/block.json
  js/src/blocks/product-channel-visibility/edit.js
  js/src/blocks/product-channel-visibility/editor.module.scss
  js/src/blocks/product-date-time-field/block.json
  js/src/blocks/product-date-time-field/edit.js
  js/src/blocks/product-date-time-field/editor.module.scss
  js/src/blocks/product-onboarding-prompt/block.json
  js/src/blocks/product-onboarding-prompt/edit.js
  js/src/blocks/product-onboarding-prompt/editor.module.scss
  js/src/blocks/product-select-field/block.json
  js/src/blocks/product-select-field/edit.js
  js/src/blocks/product-select-with-text-field/block.json
  js/src/blocks/product-select-with-text-field/edit.js
  js/src/blocks/types.js
  package-lock.json
  package.json
  src/Admin/Input/Checkbox.php
  src/Admin/Input/DateTime.php
  src/Admin/Input/Decimal.php
  src/Admin/Input/Input.php
  src/Admin/Input/InputInterface.php
  src/Admin/Input/Integer.php
  src/Admin/Input/Select.php
  src/Admin/Input/SelectWithTextInput.php
  src/Admin/Input/Text.php
  src/Admin/Product/Attributes/AttributesForm.php
  src/Admin/Product/Attributes/AttributesTab.php
  src/Admin/Product/Attributes/AttributesTrait.php
  src/Admin/Product/Attributes/Input/MultipackInput.php
  src/Admin/Product/ChannelVisibilityBlock.php
  src/Admin/ProductBlocksService.php
  src/Assets/BaseAsset.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Product/ProductHelper.php
  src/Value/ChannelVisibility.php
  tests/Unit/Admin/Input/InputCollectionTest.php
  tests/Unit/Admin/Input/InputTest.php
  tests/Unit/Admin/Product/Attributes/AttributesFormTest.php
  tests/Unit/Admin/Product/Attributes/Input/AttributeInputCollectionTest.php
  tests/Unit/Admin/Product/ChannelVisibilityBlockTest.php
  tests/Unit/Admin/ProductBlocksServiceTest.php
  tests/Unit/Assets/ScriptAssetTest.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Value/ChannelVisibilityTest.php
  tests/data/blocks.css
  tests/data/blocks.js
  tests/data/existing-block/block.json
  views/meta-box/channel_visibility.php
  webpack.config.js
Labels: changelog: add

#2266 401 handling for connected Ads accounts
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  tests/Unit/API/ClientTest.php
  tests/Unit/API/Site/Controllers/Ads/AccountControllerTest.php
Labels: type: bug, changelog: fix

#2272 Fix the compatibility issue in starting E2E test environment due to the default charset change in MariaDB v11.3.1
  package-lock.json
  package.json
Labels: changelog: dev

#2263 Fix Issue with intermediate parents status
  src/MerchantCenter/MerchantStatuses.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: type: bug, changelog: fix

#2271 Product Statuses - Handle failure of the Update Product Statuses Job
  src/API/Site/Controllers/MerchantCenter/ProductStatisticsController.php
  src/Jobs/UpdateMerchantProductStatuses.php
  src/MerchantCenter/MerchantStatuses.php
  tests/Unit/Jobs/UpdateMerchantProductStatusesTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: type: enhancement, changelog: add

#2275 R1.3: Add Google Ads account acceptance modal.
  js/src/components/google-ads-account-card/account-switch.js
  js/src/components/google-ads-account-card/claim-account-modal/index.js
  js/src/components/google-ads-account-card/claim-account-modal/index.scss
  js/src/components/google-ads-account-card/claim-account.js
  js/src/components/google-ads-account-card/claim-pending.js
  js/src/components/google-ads-account-card/connected-google-ads-account-card.js
  js/src/components/google-ads-account-card/create-account.js
  js/src/components/google-ads-account-card/google-ads-account-card.js
  js/src/components/paid-ads/billing-card/billing-setup-card.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/hooks/useAutoCheckAdsAccountStatus.js
  js/src/hooks/useGoogleAdsAccount.js
  js/src/hooks/useShowAdsClaimAccountModal.js
  js/src/utils/getWindowFeatures.js
Labels: changelog: add

#2278 API PULL - Add Coupons Notification
  src/Coupon/CouponHelper.php
  src/Coupon/CouponMetaHandler.php
  src/Coupon/SyncerHooks.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/Notifications/CouponNotificationJob.php
  src/Product/ProductHelper.php
  src/Product/SyncerHooks.php
  tests/Unit/Coupon/SyncerHooksTest.php
  tests/Unit/Jobs/CouponNotificationJobTest.php
  tests/bootstrap.php
Labels: type: enhancement, changelog: add

#2281 API PULL - Unsync product when delete Notification happens
  src/Jobs/Notifications/ProductNotificationJob.php
  tests/Unit/Jobs/ProductNotificationJobTest.php
Labels: changelog: tweak
