Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-01, with the labels that each got.

#2179 Product Block Editor: Preprocessing for adding the channel visibility
  js/src/blocks/README.md
  src/Admin/Input/Input.php
  src/Admin/ProductBlocksService.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  tests/Unit/Admin/Product/Attributes/AttributesBlockTest.php
  tests/Unit/Admin/ProductBlocksServiceTest.php
Labels: changelog: tweak

#2194 Update google/apiclient for PHP 8.3 compatibility
  composer.lock
Labels: changelog: update

#2193 Product Block Editor: Convert `Label` component and custom block registration to use the newly added APIs in Woo 8.5
  js/src/blocks/README.md
  js/src/blocks/components/index.js
  js/src/blocks/components/label.js
  js/src/blocks/product-date-time-field/block.json
  js/src/blocks/product-select-field/block.json
  js/src/blocks/product-select-field/edit.js
  js/src/blocks/product-select-with-text-field/block.json
  js/src/blocks/product-select-with-text-field/edit.js
  src/Admin/ProductBlocksService.php
  tests/Unit/Admin/ProductBlocksServiceTest.php
Labels: changelog: tweak

#2198 Include connected accounts in tracks from the backend.
  src/Tracking/Tracks.php
Labels: type: enhancement, changelog: add

#2206 WP 6.4 Compatibility: Fix the inappropriate Popover width
  js/src/components/help-popover/index.js
  js/src/product-feed/product-statistics/product-status-help-popover/index.scss
Labels: type: bug, changelog: fix

#2207 Add tracking for completed events
  src/API/Google/AdsCampaign.php
  src/API/Google/Settings.php
  src/API/Site/Controllers/Ads/CampaignController.php
  src/API/Site/Controllers/Ads/SetupCompleteController.php
  src/API/Site/Controllers/MerchantCenter/SettingsSyncController.php
  src/Exception/WPErrorTrait.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Tracking/EventTracking.php
  src/Tracking/Events/GenericEvents.php
  src/Tracking/README.md
  tests/Tools/HelperTrait/TrackingTrait.php
  tests/Tools/HelperTrait/WPHookTrait.php
  tests/Tools/WPHookMock.php
  tests/Unit/API/Google/AdsCampaignTest.php
  tests/Unit/API/Site/Controllers/Ads/CampaignControllerTest.php
  tests/Unit/API/Site/Controllers/Ads/SetupCompleteControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/SettingsSyncControllerTest.php
Labels: type: enhancement, changelog: add

#2199 Add plugin version, Google Merchant Center account ID, and Google Ads account ID to all frontend tracking events
  jest.config.js
  js/src/attribute-mapping/attribute-mapping-delete-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-rule-modal.js
  js/src/attribute-mapping/attribute-mapping-table.js
  js/src/attribute-mapping/index.test.js
  js/src/components/app-button/index.js
  js/src/components/app-table-card/index.js
  js/src/components/contact-information/store-address-card.js
  js/src/components/contact-information/usePhoneNumberCheckTrackEventEffect.js
  js/src/components/customer-effort-score-prompt/index.js
  js/src/components/edit-product-link/index.js
  js/src/components/faqs-panel/index.js
  js/src/components/help-popover/index.js
  js/src/components/paid-ads/add-paid-campaign-button.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/pre-launch-check-item/index.js
  js/src/components/trackable-link/index.js
  js/src/dashboard/all-programs-table-card/edit-program-button/edit-program-prompt-modal/index.js
  js/src/dashboard/app-date-range-filter-picker/index.js
  js/src/dashboard/campaign-creation-success-guide/index.js
  js/src/dashboard/index.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/index.js
  js/src/data/reducer.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/data/types.js
  js/src/edit-free-campaign/index.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/product-feed/issues-table-card/issues-table-data-modal.test.js
  js/src/product-feed/issues-table-card/issues-table-data.test.js
  js/src/product-feed/issues-table-card/issues-table.js
  js/src/product-feed/product-feed-table-card/index.js
  js/src/product-feed/review-request/index.js
  js/src/product-feed/review-request/index.test.js
  js/src/product-feed/review-request/review-request-issues.js
  js/src/product-feed/review-request/review-request-modal.js
  js/src/product-feed/review-request/review-request-modal.test.js
  js/src/product-feed/submission-success-guide/index.js
  js/src/reports/products/products-report-filters.js
  js/src/reports/programs/programs-report-filters.js
  js/src/reports/summary-section.js
  js/src/settings/linked-accounts.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/setup-ads-form.js
  js/src/setup-ads/top-bar/index.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/top-bar/index.js
  js/src/utils/tracks.js
  js/src/utils/tracks.test.js
  src/Admin/Admin.php
  src/Tracking/README.md
Labels: type: enhancement, changelog: add

#2200 Add plugin version, Google Merchant Center account ID, and Google Ads account ID to frontend pageview tracking events
  jest.config.js
  js/src/index.js
  js/src/index.test.js
  js/src/tests/jest-unit.setup.js
  js/src/utils/tracks.js
  src/Tracking/README.md
Labels: type: enhancement, changelog: add

#2201 Send the related tracking event with the account ID to be connected when connecting to an existing Google Merchant Center or Google Ads account
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-mc-account-card/connect-mc/index.js
  src/Tracking/README.md
Labels: type: enhancement, changelog: add

#2217 Generate coverage report with xdebug
  .codecov.yml
  .github/workflows/php-unit-tests.yml
Labels: type: bug, changelog: fix

#2219 Product Block Editor: Validate integer input for the Multipack attribute
  src/Admin/Input/Integer.php
  src/Admin/Product/Attributes/Input/MultipackInput.php
  tests/Unit/Admin/Input/InputCollectionTest.php
  tests/Unit/Admin/Product/Attributes/Input/AttributeInputCollectionTest.php
Labels: changelog: tweak

#2202 Scheduled notifications using meta handler
  src/Google/NotificationsService.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/Notifications/ProductNotificationJob.php
  src/Product/ProductHelper.php
  src/Product/ProductMetaHandler.php
  src/Product/SyncerHooks.php
  src/Value/NotificationStatus.php
  tests/Unit/Google/NotificationsServiceTest.php
  tests/Unit/Jobs/ProductNotificationJobTest.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/SyncerHooksTest.php
Labels: type: enhancement, changelog: add

#2223 Update tests for conversion tracking without a merchant account
  src/Ads/AccountService.php
  src/MerchantCenter/AccountService.php
  src/Options/AdsAccountState.php
  src/Options/MerchantAccountState.php
  tests/Unit/Ads/AccountServiceTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-ads/setup-ads-accounts.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
Labels: changelog: update

#2228 API PULL - Fix PHPCS and remove wrong obsolete code
  src/Google/NotificationsService.php
  src/Infrastructure/GoogleListingsAndAdsPlugin.php
  src/Product/ProductHelper.php
  tests/Unit/Google/NotificationsServiceTest.php
  tests/Unit/Jobs/ProductNotificationJobTest.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/SyncerHooksTest.php
Labels: type: bug, changelog: fix
