Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-07, with the labels that each got.

#2414 Add Rebranding Tour
  js/src/attribute-mapping/index.js
  js/src/attribute-mapping/index.test.js
  js/src/components/tours/campaign-assets-tour.js
  js/src/components/tours/campaign-assets-tour.scss
  js/src/components/tours/rebrading-tour.scss
  js/src/components/tours/rebranding-tour.js
  js/src/dashboard/all-programs-table-card/index.js
  js/src/dashboard/all-programs-table-card/index.test.js
  js/src/dashboard/index.js
  js/src/dashboard/index.test.js
  js/src/product-feed/index.js
  js/src/product-feed/index.test.js
  js/src/reports/products/index.js
  js/src/reports/programs/index.js
  js/src/settings/index.js
Labels: changelog: tweak

#2449 [API Pull] Handle exception when deactivating the plugin and the WPCOM token does not exist.
  src/API/WP/OAuthService.php
  src/ConnectionTest.php
  tests/Unit/API/WP/OAuthServiceTest.php
Labels: changelog: tweak

#2448 [API Pull] Enable notifications by default
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/google-mc-account-card/connected-google-mc-account-card.js
  src/API/WP/NotificationsService.php
  src/ConnectionTest.php
  src/MerchantCenter/AccountService.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: changelog: tweak

#2455 [API Pull] Ensure empty GLA attributes are returned as an object instead of an empty array in the responses.
  src/Integration/WPCOMProxy.php
  tests/Unit/Integration/WPCOMProxyTest.php
Labels: changelog: tweak

#2450 [API Pull] Tweak Variations Notifications
  src/Jobs/Notifications/AbstractItemNotificationJob.php
  src/Jobs/Notifications/ProductNotificationJob.php
  src/Product/ProductHelper.php
  src/Product/SyncerHooks.php
  tests/Unit/Jobs/ProductNotificationJobTest.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/SyncerHooksTest.php
Labels: changelog: tweak

#2452 [API Pull] Add Track Events to the Auth API responses
  src/API/WP/OAuthService.php
  src/MerchantCenter/AccountService.php
  tests/Unit/API/WP/OAuthServiceTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: type: enhancement, changelog: add

#2464 [API PULL] Disable create and update notifications for variations
  src/Product/ProductHelper.php
  src/Product/SyncerHooks.php
  tests/Unit/Product/ProductHelperTest.php
  tests/Unit/Product/SyncerHooksTest.php
Labels: changelog: tweak

#2471 Make campaign preview card responsive
  js/src/components/paid-ads/budget-section/index.js
  js/src/components/paid-ads/campaign-preview/campaign-preview-card.js
Labels: type: bug, changelog: fix

#2474 [API PULL] Add E2E tests for Notifications Grant Access
  tests/e2e/specs/notifications.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/settings.js
Labels: changelog: dev

#2477 [API PULL] E2E TESTS for Notifications schedule
  tests/e2e/specs/notifications/notifications-banner.test.js
  tests/e2e/specs/notifications/notifications-schedule.test.js
  tests/e2e/test-data/test-data.php
  tests/e2e/utils/api.js
  tests/e2e/utils/product-editor.js
Labels: changelog: dev

#2482 [API PULL] Adding more tests for Notifications
  tests/e2e/specs/notifications/notifications-schedule.test.js
  tests/e2e/utils/product-editor.js
Labels: changelog: dev
