Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-11, with the labels that each got.

#2661 2602: Simplify address syncing in settings and remove phone info
  js/src/components/account-card/index.js
  js/src/components/contact-information/contact-information-preview-card.js
  js/src/components/contact-information/contact-information-preview-card.scss
  js/src/components/contact-information/index.js
  js/src/components/contact-information/phone-number-card/constants.js
  js/src/components/contact-information/phone-number-card/edit-phone-number-content.js
  js/src/components/contact-information/phone-number-card/edit-phone-number-content.test.js
  js/src/components/contact-information/phone-number-card/index.js
  js/src/components/contact-information/phone-number-card/phone-number-card-preview.js
  js/src/components/contact-information/phone-number-card/phone-number-card-preview.scss
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  js/src/components/contact-information/phone-number-card/phone-number-card.scss
  js/src/components/contact-information/phone-number-card/phone-number-card.test.js
  js/src/components/contact-information/phone-number-card/verification-code-control.js
  js/src/components/contact-information/phone-number-card/verification-code-control.scss
  js/src/components/contact-information/phone-number-card/verification-code-control.test.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.test.js
  js/src/components/contact-information/store-address-card.js
  js/src/components/contact-information/store-address-card.scss
  js/src/components/contact-information/usePhoneNumberCheckTrackEventEffect.js
  js/src/components/google-combo-account-card/connected-google-combo-account-card.js
  js/src/components/google-combo-account-card/sync-store-address/empty-store-address-card.js
  js/src/components/google-combo-account-card/sync-store-address/index.js
  js/src/components/google-combo-account-card/sync-store-address/sync-store-address.js
  js/src/hooks/useCountryCallingCodeOptions.js
  js/src/hooks/useStoreAddressSynced.js
  js/src/settings/edit-phone-number.js
  js/src/settings/edit-store-address.js
  js/src/settings/index.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
  js/src/utils/urls.js
Labels: changelog: update

#2639 Connect MC Account within combo card
  js/src/components/google-combo-account-card/account-details.js
  js/src/components/google-combo-account-card/connect-ads/connect-ads.js
  js/src/components/google-combo-account-card/connect-google-combo-account-card.js
  js/src/components/google-combo-account-card/connected-google-combo-account-card.js
  js/src/components/google-mc-account-card/connect-mc/actions.js
  js/src/components/google-mc-account-card/connect-mc/index.js
  js/src/components/google-mc-account-card/connect-mc/index.scss
  js/src/components/google-mc-account-card/connect-mc/merchant-center-select.js
  js/src/components/google-mc-account-card/create-account-card.js
  js/src/components/google-mc-account-card/create-account.js
  js/src/components/google-mc-account-card/disabled-card.js
  js/src/components/google-mc-account-card/disconnect-account-button.js
  js/src/components/google-mc-account-card/google-mc-account-card.js
  js/src/components/google-mc-account-card/index.js
  js/src/components/google-mc-account-card/merchant-center-account-info-card.js
  js/src/components/google-mc-account-card/non-connected.js
  js/src/hooks/useAutoCreateAdsMCAccounts.js
  js/src/hooks/useAutoCreateAdsMCAccounts.test.js
  js/src/hooks/useConnectMCAccount.js
  js/src/settings/linked-accounts.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
Labels: changelog: update

#2656 [GTIN] Migration notice
  js/src/components/gtin-migration-banner/gtin-migration-banner.js
  js/src/components/gtin-migration-banner/index.js
  js/src/components/gtin-migration-banner/index.scss
  js/src/components/main-tab-nav/main-tab-nav.js
  js/src/dashboard/index.test.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useGTINMigrationStatus.js
  src/API/Site/Controllers/GTINMigrationController.php
  src/Admin/Product/Attributes/Input/GTINInput.php
  src/ConnectionTest.php
  src/HelperTraits/GTINMigrationUtilities.php
  src/Jobs/MigrateGTIN.php
  src/Options/OptionsInterface.php
Labels: type: enhancement, changelog: add

#2662 [GTIN] Add WP CLI command for migration
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Utility/WPCLIMigrationGTIN.php
Labels: type: enhancement, changelog: add

#2667 WordPress 6.7 Compatibility: Avoid errors in the database where a TEXT type can't have a default value
  src/DB/Table/AttributeMappingRulesTable.php
Labels: changelog: tweak

#2668 WordPress 6.7 Compatibility: Fix the issue that E2E test can't log in to wp-admin
  tests/e2e/global-setup.js
Labels: changelog: dev

#2670 WordPress 6.7 Compatibility: Avoid block toolbar appearing when interacting custom product blocks
  js/src/blocks/product-channel-visibility/block.json
  js/src/blocks/product-date-time-field/block.json
  js/src/blocks/product-onboarding-prompt/block.json
  js/src/blocks/product-select-field/block.json
  js/src/blocks/product-select-with-text-field/block.json
Labels: type: bug, changelog: fix

#2671 WordPress 6.7 Compatibility: Adjust the radio control layout to align well with the extended content
  js/src/components/app-radio-content-control/index.scss
Labels: changelog: tweak

#2673 Remove vendor files that prints php information `phpinfo()`
  bin/cleanup-vendor-files.sh
Labels: type: bug, changelog: fix, sirt

#2644 Onboarding: Claim New Ads Accounts in the Google Combo Accounts Card
  js/src/components/google-ads-account-card/claim-account-button.js
  js/src/components/google-ads-account-card/claim-account-button.test.js
  js/src/components/google-ads-account-card/google-ads-account-card.js
  js/src/components/google-combo-account-card/claim-ads-account/claim-ads-account.js
  js/src/components/google-combo-account-card/claim-ads-account/claim-ads-account.scss
  js/src/components/google-combo-account-card/claim-ads-account/index.js
  js/src/components/google-combo-account-card/connected-ads-account-detail.js
  js/src/components/google-combo-account-card/connected-ads-account-detail.scss
  js/src/components/google-combo-account-card/connected-google-combo-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/utils/showAdsConversionNotice.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
Labels: changelog: update

#2653 Sync MC address during onboarding.
  js/src/components/account-card/index.js
  js/src/components/contact-information/contact-information-preview.js
  js/src/components/contact-information/index.js
  js/src/components/contact-information/phone-number-card/constants.js
  js/src/components/contact-information/phone-number-card/edit-phone-number-content.js
  js/src/components/contact-information/phone-number-card/edit-phone-number-content.test.js
  js/src/components/contact-information/phone-number-card/index.js
  js/src/components/contact-information/phone-number-card/phone-number-card-preview.js
  js/src/components/contact-information/phone-number-card/phone-number-card-preview.scss
  js/src/components/contact-information/phone-number-card/phone-number-card.js
  js/src/components/contact-information/phone-number-card/phone-number-card.scss
  js/src/components/contact-information/phone-number-card/phone-number-card.test.js
  js/src/components/contact-information/phone-number-card/verification-code-control.js
  js/src/components/contact-information/phone-number-card/verification-code-control.scss
  js/src/components/contact-information/phone-number-card/verification-code-control.test.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.test.js
  js/src/components/contact-information/store-address-card.js
  js/src/components/contact-information/usePhoneNumberCheckTrackEventEffect.js
  js/src/components/google-combo-account-card/connected-google-combo-account-card.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/hooks/useCountryCallingCodeOptions.js
  js/src/hooks/useGoogleMCPhoneNumber.js
  js/src/hooks/useStoreAddressReady.js
  js/src/settings/edit-phone-number.js
  js/src/settings/edit-store-address.js
  js/src/settings/index.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.test.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
  js/src/setup-mc/setup-stepper/stepNameKeyMap.js
  js/src/setup-mc/setup-stepper/store-requirements/index.js
  js/src/utils/urls.js
  package-lock.json
  package.json
  src/MerchantCenter/MerchantCenterService.php
  tests/Tools/HelperTrait/MerchantTrait.php
  tests/Unit/MerchantCenter/ContactInformationTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/specs/setup-mc/step-3-complete-campaign.test.js
  tests/e2e/specs/setup-mc/step-3-confirm-store-requirements.test.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
  tests/e2e/utils/pages/setup-mc/step-2-product-listings.js
  tests/e2e/utils/pages/setup-mc/step-3-complete-campaign.js
  tests/e2e/utils/pages/setup-mc/step-3-confirm-store-requirements.js
Labels: changelog: update

#2666 Refactor & fix undesired exceptions in AS Jobs
  src/HelperTraits/GTINMigrationUtilities.php
  src/Jobs/MigrateGTIN.php
  src/Utility/WPCLIMigrationGTIN.php
Labels: type: bug, changelog: fix

#2678 [GTIN] Adjust plugin version for hidding GTIN
  src/HelperTraits/GTINMigrationUtilities.php
Labels: changelog: tweak

#2660 Consolidate accounts onboarding: Add edit mode to the combo card to enable it to disconnect accounts
  js/src/components/ads-account-select-control/index.js
  js/src/components/google-account-card/connected-google-account-card.js
  js/src/components/google-account-card/switch-account-button.js
  js/src/components/google-account-card/useSwitchGoogleAccount.js
  js/src/components/google-combo-account-card/claim-ads-account/claim-ads-account.js
  js/src/components/google-combo-account-card/connect-ads/connect-ads-footer.js
  js/src/components/google-combo-account-card/connect-ads/connect-existing-account.js
  js/src/components/google-combo-account-card/connect-ads/upserting-account.js
  js/src/components/google-combo-account-card/connected-google-combo-account-card.js
  js/src/components/google-combo-account-card/connected-google-combo-account-card.scss
  js/src/components/google-mc-account-card/connect-mc/actions.js
  js/src/components/google-mc-account-card/connect-mc/index.js
  js/src/components/google-mc-account-card/creating-card.js
  js/src/components/google-mc-account-card/reclaim-url-card/index.js
  js/src/hooks/useGoogleMCAccount.js
  tests/e2e/global-setup.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
Labels: changelog: update

#2683 Improve post-onboarding: Update the budget recommendation text for campaign creation
  js/src/components/paid-ads/budget-section/budget-recommendation/index.js
Labels: changelog: none

#2635 Feature: Improve post-onboarding
  js/src/components/free-ad-credit/index.scss
  js/src/components/paid-ads/add-paid-campaign-button.js
  js/src/components/paid-ads/ads-campaign/ads-campaign.js
  js/src/components/paid-ads/ads-campaign/paid-ads-features-section.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/budget-section/budget-recommendation/index.js
  js/src/dashboard/all-programs-table-card/edit-program-button/edit-program-prompt-modal/index.js
  js/src/dashboard/all-programs-table-card/program-toggle/pause-program-modal/index.js
  js/src/dashboard/all-programs-table-card/remove-program-button/remove-program-modal/index.js
  js/src/dashboard/campaign-creation-success-guide/index.js
  js/src/dashboard/index.scss
  js/src/dashboard/index.test.js
  js/src/dashboard/summary-section/index.js
  js/src/dashboard/summary-section/paid-campaign-promotion-card.js
  js/src/dashboard/summary-section/paid-features/free-ad-credit.js
  js/src/dashboard/summary-section/paid-features/index.js
  js/src/dashboard/summary-section/paid-features/index.scss
  js/src/dashboard/summary-section/summary-section.test.js
  js/src/get-started-page/faqs/index.js
  js/src/get-started-page/features-card/index.js
  js/src/hooks/useFreeAdCredit.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/product-feed/product-statistics/create-campaign-notice/index.js
  js/src/product-feed/product-statistics/create-campaign-notice/index.scss
  js/src/product-feed/product-statistics/index.js
  js/src/product-feed/submission-success-guide/index.js
  js/src/reports/index.js
  js/src/reports/metric-number.js
  js/src/reports/products/filter-config.js
  js/src/settings/disconnect-modal/confirm-modal.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/ads-stepper/setup-accounts/index.js
  js/src/setup-ads/ads-stepper/setup-paid-ads.js
  js/src/setup-ads/top-bar/index.js
  js/src/setup-mc/setup-stepper/skip-button.js
  src/Notes/CompleteSetup.php
  src/Notes/SetupCampaignTwoWeeks.php
  src/Tracking/README.md
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/dashboard/paid-features.test.js
  tests/e2e/specs/product-feed/product-feed-campaign-notice.test.js
  tests/e2e/specs/setup-mc/step-3-complete-campaign.test.js
  tests/e2e/test-data/test-data.php
  tests/e2e/utils/api.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/dashboard.js
  tests/e2e/utils/pages/product-feed.js
  tests/e2e/utils/pages/setup-ads/setup-budget.js
  tests/e2e/utils/pages/setup-mc/step-3-complete-campaign.js
Labels: changelog: none

#2677 [GTIN] Add Migration support for YOAST SEO
  src/HelperTraits/GTINMigrationUtilities.php
  src/Integration/YoastWooCommerceSeo.php
  src/Jobs/MigrateGTIN.php
  src/Utility/WPCLIMigrationGTIN.php
Labels: type: enhancement, changelog: add

#2679 [GTIN] Adding more tests for GTIN migration
  src/Jobs/MigrateGTIN.php
  tests/Unit/Admin/Product/Attributes/Input/AttributeInputCollectionTest.php
  tests/Unit/Jobs/MigrateGTINTest.php
Labels: changelog: dev

#2685 [GTIN] Hide / disable GTIN also when YOAST is active.
  src/Admin/Input/Input.php
  src/Admin/Input/SelectWithTextInput.php
  src/Admin/Product/Attributes/AttributesForm.php
Labels: changelog: tweak

#2684 Support core gtin field
  js/src/components/gtin-migration-banner/gtin-migration-banner.js
  js/src/components/gtin-migration-banner/index.js
  js/src/components/gtin-migration-banner/index.scss
  js/src/components/main-tab-nav/main-tab-nav.js
  js/src/dashboard/index.test.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useGTINMigrationStatus.js
  src/API/Site/Controllers/GTINMigrationController.php
  src/Admin/Input/Input.php
  src/Admin/Input/SelectWithTextInput.php
  src/Admin/Product/Attributes/AttributesForm.php
  src/Admin/Product/Attributes/Input/GTINInput.php
  src/ConnectionTest.php
  src/HelperTraits/GTINMigrationUtilities.php
  src/Integration/YoastWooCommerceSeo.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Internal/InstallTimestamp.php
  src/Jobs/MigrateGTIN.php
  src/Options/OptionsInterface.php
  src/Product/WCProductAdapter.php
  src/Utility/WPCLIMigrationGTIN.php
  tests/Unit/Admin/Input/InputTest.php
  tests/Unit/Admin/Product/Attributes/Input/AttributeInputCollectionTest.php
  tests/Unit/Jobs/MigrateGTINTest.php
  tests/Unit/Product/Attributes/GtinMappingTest.php
Labels: type: enhancement, changelog: add

#2688 Consolidate accounts onboarding: Prevent Google Ads account setup from trying to connect to an unclaimed and disconnected account ID
  js/src/components/google-ads-account-card/disconnect-account.js
  js/src/components/google-ads-account-card/disconnect-account.test.js
  js/src/components/google-combo-account-card/connect-ads/connect-existing-account-actions.js
  js/src/components/google-combo-account-card/connect-ads/connect-existing-account.js
Labels: changelog: none

#2695 Add margins for Notices
  js/src/css/shared/_woocommerce-admin.scss
Labels: type: bug, changelog: fix

#2686 Add free shipping order value condition for shipping phase 1
  js/src/components/adaptive-form/adaptive-form-context.js
  js/src/components/adaptive-form/index.js
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/order-value-condition-section/index.js
  js/src/components/order-value-condition-section/minimum-order-card/calculateValueFromGroupChange.js
  js/src/components/order-value-condition-section/minimum-order-card/calculateValueFromGroupChange.test.js
  js/src/components/order-value-condition-section/minimum-order-card/groupShippingRatesByCurrencyFreeShippingThreshold.js
  js/src/components/order-value-condition-section/minimum-order-card/groupShippingRatesByCurrencyFreeShippingThreshold.test.js
  js/src/components/order-value-condition-section/minimum-order-card/index.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-card.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-card.scss
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-card.test.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-form-modals/add-minimum-order-form-modal.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-form-modals/edit-minimum-order-form-modal.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-form-modals/index.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-form-modals/minimum-order-form-modal.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-form-modals/validateMinimumOrder.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-form-modals/validateMinimumOrder.test.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-input-control-label-text.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-input-control.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-input-control.scss
  js/src/components/order-value-condition-section/minimum-order-card/typedefs.js
  js/src/components/order-value-condition-section/offer-free-shipping-checkbox.js
  js/src/components/order-value-condition-section/order-value-condition-section.js
  js/src/components/shipping-rate-section/flat-shipping-rates-input-cards.js
  js/src/components/shipping-rate-section/offer-free-shipping-card.js
  js/src/utils/getOfferFreeShippingInitialValue.js
Labels: type: enhancement, changelog: add
