Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-09, with the labels that each got.

#2531 2488: Move FAQs panel after CTAs
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/paid-ads/ads-campaign.js
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/faqs-panel.js
  js/src/components/paid-ads/faqs-panel.js
  js/src/components/stepper/step-content-actions/index.js
  js/src/components/stepper/step-content-actions/index.scss
  js/src/components/stepper/step-content-footer/index.js
  js/src/components/vertical-gap-layout/index.js
  js/src/components/vertical-gap-layout/index.scss
  js/src/setup-ads/ads-stepper/setup-accounts/index.js
  js/src/setup-ads/ads-stepper/setup-billing/index.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/setup-mc/setup-stepper/store-requirements/index.js
Labels: changelog: tweak

#2573 Fix issue with syncing shipping rates with more than two decimals
  src/Shipping/ShippingRate.php
  tests/Unit/Shipping/ZoneMethodsParserTest.php
Labels: type: bug, changelog: fix

#2526 Adjust auto-sync shipping option
  js/src/components/shipping-rate-section/shipping-rate-section.js
  js/src/components/shipping-rate-section/shipping-rate-section.test.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  src/API/Site/Controllers/MerchantCenter/SettingsController.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Shipping/ShippingZone.php
  tests/Unit/API/Site/Controllers/MerchantCenter/SettingsControllerTest.php
  tests/Unit/Shipping/ShippingZoneTest.php
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/utils/pages/edit-free-listings.js
  tests/e2e/utils/pages/setup-mc/step-2-product-listings.js
Labels: changelog: tweak

#2564 2537: Swap performance cards.
  js/src/dashboard/summary-section/index.js
Labels: changelog: tweak

#2574 Remove Woo Navigation integration
  jest.config.js
  js/src/attribute-mapping/index.js
  js/src/components/main-tab-nav/index.js
  js/src/components/main-tab-nav/main-tab-nav.js
  js/src/components/navigation-classic/index.js
  js/src/css/shared/_woocommerce-admin.scss
  js/src/dashboard/index.js
  js/src/dashboard/index.test.js
  js/src/hooks/useLayout.js
  js/src/hooks/useMenuEffect.js
  js/src/index.js
  js/src/product-feed/index.js
  js/src/product-feed/index.test.js
  js/src/reports/products/index.js
  js/src/reports/programs/index.js
  js/src/reports/reports-navigation.js
  js/src/settings/index.js
  js/src/settings/reconnect-google-account/reconnect-google-account.js
  js/src/settings/reconnect-wpcom-account/reconnect-wpcom-account.js
  js/src/settings/reconnectionLock.js
  js/src/settings/reconnectionLock.scss
  js/src/utils/isWCNavigationEnabled.js
  src/Menu/Dashboard.php
  src/Menu/GetStarted.php
  src/Menu/WooAdminNavigationTrait.php
Labels: changelog: breaking

#2547 Use remote-site-status to check the WPCOM Auth status
  src/API/WP/NotificationsService.php
  src/ConnectionTest.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/MerchantCenter/AccountService.php
  src/Options/TransientsInterface.php
  src/Settings/SyncerHooks.php
  tests/Unit/API/WP/NotificationsServiceTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: changelog: tweak

#2576 Log Exception if an asset is enqueued before being registered
  src/Assets/BaseAsset.php
  tests/Unit/Assets/ScriptAssetTest.php
Labels: type: bug, changelog: fix

#2588 Set WPCOM_API_STATUS transient for E2E tests
  tests/e2e/test-data/test-data.php
Labels: type: bug, changelog: none

#2532 2492: Remove PreLaunchChecklist component
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/components/pre-launch-check-item/index.js
  js/src/components/pre-launch-check-item/index.scss
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/usePolicyCheck.js
  js/src/setup-mc/setup-stepper/store-requirements/index.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/checkErrors.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/checkErrors.test.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
  src/API/Site/Controllers/MerchantCenter/SettingsController.php
  src/MerchantCenter/MerchantCenterService.php
  src/Value/MerchantCenterSettings.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/Unit/Product/AttributeMapping/AttributeMappingWCProductAdapterTest.php
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/specs/setup-mc/step-3-confirm-store-requirements.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-mc/step-2-product-listings.js
  tests/e2e/utils/pages/setup-mc/step-3-confirm-store-requirements.js
Labels: changelog: update

#2563 2504: Add skip paid ads confirmation modal.
  js/src/setup-mc/setup-stepper/setup-paid-ads/constants.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/skip-paid-ads-confirmation-modal.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/pages/setup-mc/step-4-complete-campaign.js
Labels: type: enhancement, changelog: add

#2585 Removes initial cards as part of refactoring
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
Labels: changelog: none

#2533 2500: Show paid campaign setup fields during onboarding flow
  js/src/setup-mc/setup-stepper/setup-paid-ads/clientSession.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/pages/setup-mc/step-4-complete-campaign.js
Labels: changelog: tweak

#2590 Update the shipping time controllers to handle the maximum shipping time
  src/API/Site/Controllers/MerchantCenter/ShippingTimeBatchController.php
  src/API/Site/Controllers/MerchantCenter/ShippingTimeController.php
  src/DB/Table/ShippingTimeTable.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeBatchControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeControllerTest.php
Labels: changelog: update

#2542 Hide Tax UI during onboarding & keep in edit campaign
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/utils/pages/setup-mc/step-2-product-listings.js
Labels: changelog: update

#2594 Update UI to support minimum and maximum shipping times.
  js/src/components/free-listings/configure-product-listings/__snapshots__/checkErrors.test.js.snap
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/add-time-button/add-time-modal/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-form.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/edit-time-modal/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/index.scss
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/index.test.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/getCountriesTimeArray.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/time-stepper/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/time-stepper/index.scss
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/time-stepper/index.test.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/css/abstracts/_variables.scss
  js/src/data/actions.js
  js/src/hooks/useSaveShippingTimes.js
  js/src/utils/getShippingTimeMapKey.js
  src/API/Site/Controllers/MerchantCenter/ShippingTimeController.php
Labels: type: enhancement, changelog: add

#2558 2499: Add coupon banner
  js/src/components/free-ad-credit/country-modal/country-amount.js
  js/src/components/free-ad-credit/country-modal/index.js
  js/src/components/free-ad-credit/country-modal/index.scss
  js/src/components/free-ad-credit/index.js
  js/src/components/free-ad-credit/index.scss
  js/src/setup-ads/ads-stepper/setup-accounts/index.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-ads/setup-ads-accounts.js
Labels: changelog: tweak

#2621 Prioritise core WooCommerce GTIN field in product adapter
  src/Product/WCProductAdapter.php
  tests/Unit/Product/Attributes/GtinMappingTest.php
Labels: changelog: update

#2609 Update Add/Edit Shipping Time Modals to support minimum and maximum shipping times stepper
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/add-time-button/add-time-modal/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/add-time-button/add-time-modal/index.scss
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/add-time-button/add-time-modal/index.test.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/edit-time-modal/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/edit-time-modal/index.test.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/edit-time-button/index.scss
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/index.scss
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/countries-time-input/index.test.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/min-max-inputs/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/time-stepper/index.js
  js/src/components/free-listings/configure-product-listings/shipping-time/shipping-time-setup/time-stepper/index.test.js
  js/src/utils/validateShippingTimeGroup.js
Labels: changelog: update

#2619 Adjust e2e tests for minimum and maximum shipping times
  tests/e2e/specs/dashboard/edit-free-listings.test.js
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/utils/pages/edit-free-listings.js
  tests/e2e/utils/pages/setup-mc/step-2-product-listings.js
Labels: changelog: tweak

#2625 PHP Units tests: Symlink WC instead of moving the WC folder
  bin/install-wp-tests.sh
Labels: changelog: dev

#2624 [API PULL] Tweak WP Proxy Response to force the types of the price fields
  src/Integration/WPCOMProxy.php
  tests/Unit/Integration/WPCOMProxyTest.php
Labels: type: bug, changelog: fix
