Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-05, with the labels that each got.

#2389 Convert `lbs` to `lb` when mapping WC products to Google products
  src/Product/WCProductAdapter.php
  tests/Unit/Product/WCProductAdapterTest.php
Labels: type: bug, changelog: fix

#2394 Avoid running untrusted input as shell commands in the GitHub Actions
  .github/workflows/build.yml
  .github/workflows/php-hook-documentation.yml
Labels: changelog: dev

#2395 Fix failing E2E tests
  tests/e2e/utils/customer.js
  tests/e2e/utils/pages/setup-mc/step-3-confirm-store-requirements.js
Labels: type: bug, changelog: fix

#2397 Avoid running malicious inputs as shell commands in the GitHub Actions
  .github/workflows/e2e-tests.yml
  .github/workflows/php-unit-tests.yml
Labels: changelog: dev

#2396 Rename `redirect_url` to `store_url` in the state parameter
  src/API/WP/OAuthService.php
  tests/Unit/API/WP/OAuthServiceTest.php
Labels: changelog: tweak

#2399 Avoid running malicious inputs as shell commands in the GitHub Actions
  .github/workflows/e2e-tests.yml
  .github/workflows/php-unit-tests.yml
Labels: changelog: dev

#2393 Fix E2E test when using RC
  .wp-env.json
  tests/e2e/bin/test-env-setup.sh
Labels: type: bug, changelog: dev

#2386 Update Google API v16
  bin/GoogleAdsCleanupServices.php
  composer.json
  composer.lock
  src/API/Google/Ads.php
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignBudget.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/AssetFieldType.php
  src/API/Google/BillingSetupStatus.php
  src/API/Google/CallToActionType.php
  src/API/Google/CampaignStatus.php
  src/API/Google/CampaignType.php
  src/API/Google/ExceptionTrait.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/Query/AdsCampaignQuery.php
  src/API/Google/Query/AdsProductLinkInvitationQuery.php
  src/API/Google/Query/AdsQuery.php
  src/API/Google/Query/AdsReportQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/Google/Ads/GoogleAdsClient.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsConversionActionTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
  tests/bootstrap.php
Labels: changelog: update

#2400 Prevent PHP Warning when Statistics is null
  src/MerchantCenter/MerchantCenterService.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
Labels: type: bug, changelog: fix

#2403 Add info about Google Ads API Client Library Legacy
  README.md
Labels: changelog: dev

#2404 Upgrade the workflows in GitHub Actions to use Node.js v20
  .github/workflows/backlog-automation.yml
  .github/workflows/branch-labels.yml
  .github/workflows/build.yml
  .github/workflows/e2e-tests.yml
  .github/workflows/js-css-linting.yml
  .github/workflows/js-unit-tests.yml
  .github/workflows/php-coding-standards.yml
  .github/workflows/php-hook-documentation.yml
  .github/workflows/php-unit-tests.yml
  .github/workflows/post-release-merge.yml
  .github/workflows/prepare-release.yml
  .github/workflows/run-qit.yml
Labels: changelog: dev

#2411 Implement RequestReview in the Merchant class
  src/API/Google/Merchant.php
  src/API/Google/Middleware.php
  src/API/Site/Controllers/MerchantCenter/RequestReviewController.php
  src/Google/RequestReviewStatuses.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  tests/Tools/HelperTrait/GuzzleClientTrait.php
  tests/Unit/API/Google/MerchantTest.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/RequestReviewControllerTest.php
Labels: changelog: update

#2412 Avoid a possible error when linking accounts due to the delay between Google APIs.
  src/API/Google/Ads.php
  tests/Unit/API/Google/AdsTest.php
Labels: changelog: tweak

#2413 Simplify and enhance the loading state control during the Google Ads account creation and claiming
  js/src/components/google-ads-account-card/claim-account-button.js
  js/src/components/google-ads-account-card/claim-account/index.js
  js/src/components/google-ads-account-card/create-account-button.js
  js/src/components/google-ads-account-card/create-account.js
  js/src/hooks/useUpsertAdsAccount.js
Labels: changelog: tweak
