Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-08, with the labels that each got.

#2485 Enable labeling of Ads campaigns
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignLabel.php
  src/API/Google/Query/AdsCampaignLabelQuery.php
  src/API/Site/Controllers/Ads/CampaignController.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsCampaignLabelTest.php
  tests/Unit/API/Google/AdsCampaignTest.php
Labels: type: enhancement, changelog: add

#2486 Update doc links references to google-for-woocommerce
  README.md
  js/src/components/contact-information/index.js
  js/src/components/google-account-card/connect-google-account-card.js
  js/src/components/google-account-card/read-more-link.js
  js/src/components/google-account-card/request-full-access-google-account-card.js
  js/src/components/help-icon-button.js
  js/src/get-started-page/faqs/index.js
  js/src/get-started-page/features-card/index.js
  js/src/settings/edit-phone-number.js
  js/src/settings/edit-store-address.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
  src/MerchantCenter/MerchantStatuses.php
  src/Notes/SetupCampaign.php
  src/PluginHelper.php
  src/Tracking/README.md
  tests/e2e/specs/setup-mc/step-3-confirm-store-requirements.test.js
Labels: changelog: tweak

#2472 Enable page size in campaigns endpoint
  src/API/Google/AdsCampaign.php
  src/API/Google/Query/AdsCampaignQuery.php
  src/API/Google/Query/AdsQuery.php
  src/API/Site/Controllers/Ads/CampaignController.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsCampaignTest.php
  tests/Unit/API/Site/Controllers/Ads/CampaignControllerTest.php
Labels: changelog: update

#2498 Update get started page
  js/src/css/abstracts/_variables.scss
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-with-hero-card/hero.png
  js/src/get-started-page/get-started-with-hero-card/index.js
  js/src/get-started-page/get-started-with-hero-card/index.scss
  js/src/get-started-page/index.js
Labels: changelog: tweak

#2510 Fix broken unit tests with WooCommerce `9.2.0-rc.1`
  tests/e2e/specs/get-started.test.js
  tests/e2e/utils/customer.js
Labels: type: bug, changelog: fix

#2497 Upgrade Readme FAQ and remove video for wporg
  readme.txt
Labels: changelog: tweak

#2512 Update WPORG header image
  wordpress_org_assets/banner-1544x500.png
  wordpress_org_assets/banner-772x250.png
Labels: changelog: tweak

#2508 Tweak FAQS for Getting started page
  js/src/get-started-page/faqs/index.js
  js/src/get-started-page/faqs/index.scss
  src/Tracking/README.md
Labels: changelog: tweak

#2518 Fix Error when google mc account is undefined
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/enable-new-product-sync-notice.test.js
Labels: type: bug, changelog: fix

#2511 Update Block validation to support error context
  js/src/blocks/product-date-time-field/edit.js
  src/Admin/Input/Integer.php
  tests/Unit/Admin/Input/InputCollectionTest.php
  tests/Unit/Admin/Product/Attributes/Input/AttributeInputCollectionTest.php
  tests/e2e/specs/product-editor/block-integration.test.js
  tests/e2e/utils/product-editor.js
Labels: type: bug, changelog: fix

#2520 Add Shipping Max time column in gla_shipping_times Table
  src/DB/Migration/Migration20240813T1653383133.php
  src/DB/Table/ShippingTimeTable.php
  src/Internal/DependencyManagement/DBServiceProvider.php
Labels: type: enhancement, changelog: add

#2528 Make the value entering of the billing state field in e2e test compatible with WC < 9.2
  tests/e2e/utils/customer.js
Labels: changelog: dev

#2505 Display body message if error status is 406 during account creation
  js/src/hooks/useUpsertAdsAccount.js
Labels: changelog: tweak

#2519 Set empty props as objects in WPCOM Proxy responses
  src/Integration/WPCOMProxy.php
  tests/Unit/Integration/WPCOMProxyTest.php
Labels: type: bug, changelog: fix

#2546 Prevent E2E tests from failing randomly due to getting product block attribute locators before they are rendered
  tests/e2e/utils/product-editor.js
Labels: changelog: dev

#2545 Upgrade readme details
  readme.txt
Labels: changelog: tweak

#2550 Tweak Connect Test Page errors when WPCOM token is not connected.
  src/ConnectionTest.php
Labels: changelog: tweak

#2516 Hides jetpack during onboarding if already connected
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
Labels: changelog: update

#2543 Set default tax_rate to destination
  src/API/Site/Controllers/MerchantCenter/SettingsController.php
  tests/Unit/API/Site/Controllers/MerchantCenter/SettingsControllerTest.php
Labels: changelog: tweak

#2522 Hide the language setting during onboarding
  js/src/components/free-listings/choose-audience-section/choose-audience-section.js
  js/src/components/free-listings/choose-audience-section/choose-audience-section.scss
  src/Tracking/README.md
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/utils/pages/setup-mc/step-2-product-listings.js
Labels: changelog: update

#2544 Migrate jest tests to use Node.js 20 and make components compatible with upgraded packages
  jest.config.js
  js/src/attribute-mapping/index.test.js
  js/src/components/adaptive-form/adaptive-form.test.js
  js/src/components/app-input-number-control/index.test.js
  js/src/components/app-tooltip/index.js
  js/src/components/contact-information/__snapshots__/mapStoreAddressErrors.test.js.snap
  js/src/components/contact-information/phone-number-card/edit-phone-number-content.test.js
  js/src/components/contact-information/phone-number-card/phone-number-card.test.js
  js/src/components/contact-information/phone-number-card/verification-code-control.js
  js/src/components/contact-information/phone-number-card/verification-code-control.test.js
  js/src/components/contact-information/phone-number-card/verify-phone-number-content.test.js
  js/src/components/google-ads-account-card/claim-account-button.test.js
  js/src/components/google-ads-account-card/connect-ads/index.test.js
  js/src/components/google-ads-account-card/disconnect-account.test.js
  js/src/components/google-ads-account-card/terms-modal/index.test.js
  js/src/components/paid-ads/__snapshots__/validateAssetGroup.test.js.snap
  js/src/components/paid-ads/asset-group/asset-field.test.js
  js/src/components/paid-ads/asset-group/images-selector.js
  js/src/components/paid-ads/asset-group/images-selector.test.js
  js/src/components/paid-ads/asset-group/texts-editor.test.js
  js/src/components/paid-ads/audienceSection.test.js
  js/src/components/paid-ads/billing-card/billing-setup-card.test.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/campaign-assets-form.test.js
  js/src/components/paid-ads/convertToAssetGroupUpdateBody.test.js
  js/src/components/shipping-rate-section/minimum-order-card/calculateValueFromGroupChange.test.js
  js/src/components/shipping-rate-section/minimum-order-card/minimum-order-card.test.js
  js/src/components/tree-select-control/control.test.js
  js/src/dashboard/index.test.js
  js/src/data/utils.js
  js/src/product-feed/product-feed-table-card/edit-visibility-action.js
  js/src/product-feed/product-statistics/index.test.js
  js/src/reports/programs/campaign-name-cell.js
  js/src/reports/programs/campaign-name-cell.test.js
  js/src/setup-ads/ads-stepper/index.test.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.test.js
  js/src/tests/dependencies/automattic/components.js
  js/src/tests/dependencies/woocommerce/settings.js
  js/src/tests/expectComponentToRecordEventWithFilteredProperties.js
  js/src/utils/structuredClone.js
Labels: changelog: tweak

#2557 Update 'Linked accounts' to include Google Ads
  js/src/settings/linked-accounts-section-wrapper.js
Labels: changelog: tweak

#2561 Align namespaces for unit tests
  tests/Unit/API/Site/Controllers/MerchantCenter/SettingsSyncControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeBatchControllerTest.php
  tests/Unit/Assets/ScriptAssetTest.php
  tests/Unit/DB/Table/BudgetRecommendationTableTest.php
  tests/Unit/DB/Table/MerchantIssueTableTest.php
  tests/Unit/Google/GoogleHelperTest.php
  tests/Unit/Integration/WPCOMProxyTest.php
  tests/Unit/Product/Attributes/AbstractAttributeTest.php
  tests/Unit/Product/Attributes/AttributeManagerTest.php
  tests/Unit/Product/ProductRepositoryTest.php
  tests/Unit/TaskList/CompleteSetupTaskTest.php
  tests/Unit/View/PHPViewFactoryTest.php
  tests/Unit/View/PHPViewTest.php
Labels: changelog: dev

#2527 Fix issue with comma separators for Shipping Rates
  src/PluginHelper.php
  src/Shipping/ZoneMethodsParser.php
  tests/Unit/Plugin/PluginHelperTraitTest.php
  tests/Unit/Shipping/ZoneMethodsParserTest.php
Labels: type: bug, changelog: fix

#2560 Return settings prop as object in the REST API
  src/Integration/WPCOMProxy.php
  tests/Unit/Integration/WPCOMProxyTest.php
Labels: type: bug, changelog: fix
