Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-04, with the labels that each got.

#2311 API Pull - Grant access to google WPCOM app in settings page
  js/src/components/app-notice/index.js
  js/src/components/app-notice/index.scss
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/google-mc-account-card/connected-google-mc-account-card.js
  js/src/components/google-mc-account-card/google-mc-account-card.js
  js/src/constants.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.test.js
  js/src/settings/index.js
  src/API/Site/Controllers/DisconnectController.php
  src/API/Site/Controllers/RestAPI/AuthController.php
  src/API/WP/NotificationsService.php
  src/API/WP/OAuthService.php
  src/ConnectionTest.php
  src/Coupon/CouponSyncer.php
  src/Coupon/SyncerHooks.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Jobs/AbstractCouponSyncerJob.php
  src/Jobs/AbstractProductSyncerBatchedJob.php
  src/Jobs/AbstractProductSyncerJob.php
  src/Jobs/ProductSyncerJobInterface.php
  src/MerchantCenter/AccountService.php
  src/MerchantCenter/MerchantCenterService.php
  src/Options/Options.php
  src/Options/OptionsInterface.php
  src/Product/ProductSyncer.php
  src/Product/SyncerHooks.php
  tests/Unit/API/Site/Controllers/RestAPI/AuthControllerTest.php
  tests/Unit/Coupon/CouponSyncerTest.php
  tests/Unit/Coupon/SyncerHooksTest.php
  tests/Unit/Jobs/UpdateAllProductsTest.php
  tests/Unit/Jobs/UpdateProductsTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/Product/ProductSyncerTest.php
  tests/Unit/Product/SyncerHooksTest.php
Labels: type: enhancement, changelog: add

#2342 Add target audiences and shipping times in the settings/general endpoint.
  src/DB/Query/ShippingTimeQuery.php
  src/Integration/WPCOMProxy.php
  src/Internal/DependencyManagement/IntegrationServiceProvider.php
  tests/Unit/Integration/WPCOMProxyTest.php
Labels: type: enhancement, changelog: add

#2339 API PULL - Add confirmation modal for disabling the feature
  js/src/components/google-mc-account-card/connected-google-mc-account-card.js
  js/src/settings/disconnect-modal/confirm-modal.js
  js/src/settings/disconnect-modal/constants.js
Labels: type: enhancement, changelog: add

#2340 API PULL - Add a filter for enabling the feature
  js/src/components/google-mc-account-card/connected-google-mc-account-card.js
  js/src/constants.js
  src/API/WP/NotificationsService.php
  src/Coupon/SyncerHooks.php
  src/Jobs/Notifications/AbstractNotificationJob.php
  src/MerchantCenter/AccountService.php
  src/MerchantCenter/MerchantCenterService.php
  src/Options/Options.php
  src/Options/OptionsInterface.php
  src/Product/SyncerHooks.php
  src/Settings/SyncerHooks.php
  src/Shipping/SyncerHooks.php
  tests/Unit/Coupon/SyncerHooksTest.php
  tests/Unit/Jobs/AbstractItemNotificationJobTest.php
  tests/Unit/Jobs/AbstractNotificationJobTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/Product/SyncerHooksTest.php
  tests/Unit/Settings/SyncerHooksTest.php
  tests/Unit/Shipping/SyncerHooksTest.php
Labels: type: enhancement, changelog: add

#2336 API PULL - Validate MC connection in notifications
  src/API/WP/NotificationsService.php
  src/ConnectionTest.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Jobs/Notifications/AbstractNotificationJob.php
  src/Jobs/Notifications/CouponNotificationJob.php
  src/Jobs/Notifications/ProductNotificationJob.php
  tests/Unit/API/WP/NotificationsServiceTest.php
  tests/Unit/Jobs/AbstractNotificationJobTest.php
Labels: type: enhancement, changelog: add

#2350 Add snippet to bypass plugin dependency to fix e2e tests
  tests/e2e/test-snippets/test-snippets.php
Labels: type: bug, changelog: fix

#2346 API PULL - Fix fatal when sending notifications in Connection test
  src/ConnectionTest.php
Labels: type: bug, changelog: fix

#2344 Add support for program types when requesting a review
  js/src/product-feed/review-request/review-request-notice.js
  src/API/Google/Middleware.php
  src/Google/RequestReviewStatuses.php
  tests/Unit/API/Site/Controllers/MerchantCenter/RequestReviewControllerTest.php
Labels: type: bug, changelog: fix

#2362 Update e2e test environment to install WooCommerce earlier
  .wp-env.json
  tests/e2e/bin/test-env-setup.sh
  tests/e2e/test-snippets/test-snippets.php
Labels: changelog: update, changelog: none

#2354 API PULL - Add offer id product deletion notification
  src/API/WP/NotificationsService.php
  src/Jobs/Notifications/AbstractItemNotificationJob.php
  src/Jobs/Notifications/ProductNotificationJob.php
  tests/Unit/Jobs/ProductNotificationJobTest.php
Labels: changelog: tweak

#2360 The Product Block Editor feature should be disabled after an E2E test run
  tests/e2e/specs/product-editor/block-integration.test.js
Labels: changelog: dev

#2367 Exclude dev-related files from the build bundle
  .gitattributes
Labels: changelog: dev

#2366 Expose attribute mapping rule values using WCProductAdapter
  src/Integration/WPCOMProxy.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/IntegrationServiceProvider.php
  src/Product/Attributes/AttributeManager.php
  tests/Unit/Integration/WPCOMProxyTest.php
  tests/Unit/Product/Attributes/AttributeManagerTest.php
Labels: changelog: update

#2377 Update tags in readme.txt
  readme.txt
Labels: changelog: tweak

#2371 Update `woocommerce-grow-jsdoc` to use `jsdoc` v4
  package-lock.json
  package.json
  src/Tracking/README.md
Labels: changelog: dev

#2375 Remove deprecated event properties marked as removable after Q1 2024 from the onboarding event tracking
  js/src/components/paid-ads/billing-card/billing-setup-card.test.js
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-with-video-card/index.js
  js/src/product-feed/index.test.js
  js/src/product-feed/review-request/index.test.js
  js/src/product-feed/review-request/review-request-modal.test.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/ads-stepper/index.test.js
  js/src/setup-ads/top-bar/index.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.test.js
  js/src/setup-mc/top-bar/index.js
  js/src/tests/jest-unit.setup.js
  js/src/utils/tracks.js
  src/Tracking/README.md
Labels: changelog: tweak

#2378 Fix typo of documentation
  src/Product/WCProductAdapter.php
Labels: changelog: none

#2270 R-1.3 Add Google Ads invite acceptance flow
  js/src/components/google-ads-account-card/claim-account-button.js
  js/src/components/google-ads-account-card/claim-account-modal.js
  js/src/components/google-ads-account-card/claim-account/index.js
  js/src/components/google-ads-account-card/claim-account/index.scss
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-ads-account-card/connected-google-ads-account-card.js
  js/src/components/google-ads-account-card/create-account.js
  js/src/components/google-ads-account-card/disabled-card.js
  js/src/components/google-ads-account-card/disconnect-account.js
  js/src/components/google-ads-account-card/google-ads-account-card.js
  js/src/components/google-ads-account-card/google-ads-account-card.test.js
  js/src/components/google-ads-account-card/non-connected.js
  js/src/components/google-mc-account-card/google-mc-account-card.js
  js/src/components/paid-ads/billing-card/billing-setup-card.js
  js/src/components/paid-ads/budget-section/index.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/get-started-page/benefits-card/index.js
  js/src/get-started-page/index.js
  js/src/hooks/useApiFetchCallback.js
  js/src/hooks/useGoogleAdsAccount.js
  js/src/hooks/useGoogleAdsAccountStatus.js
  js/src/hooks/useSyncableProductsCalculation.js
  js/src/hooks/useUpsertAdsAccount.js
  js/src/setup-ads/ads-stepper/setup-accounts/index.js
  js/src/setup-mc/setup-stepper/setup-accounts/index.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-features-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/product-feed-status-section.scss
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/utils/getWindowFeatures.js
  src/API/Google/Ads.php
  src/API/Google/Middleware.php
  src/API/Site/Controllers/Ads/AccountController.php
  src/Ads/AccountService.php
  src/Ads/AdsService.php
  src/MerchantCenter/MerchantCenterService.php
  src/Options/AdsAccountState.php
  src/Options/OptionsInterface.php
  tests/Unit/API/Site/Controllers/Ads/AccountControllerTest.php
  tests/Unit/Ads/AccountServiceTest.php
  tests/Unit/Ads/AdsServiceTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-mc/step-4-complete-campaign.js
Labels: changelog: add

#2308 Update E2E tests for setup flow with Ads setup in Step 1
  js/src/components/google-ads-account-card/claim-account-modal.js
  js/src/setup-ads/ads-stepper/setup-accounts/index.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/specs/setup-mc/step-3-confirm-store-requirements.test.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-ads/setup-ads-accounts.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
  tests/e2e/utils/pages/setup-mc/step-4-complete-campaign.js
Labels: changelog: dev

#2369 API Pull - Verify a nonce when setting Google WPCOM auth status
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.test.js
  src/API/Site/Controllers/RestAPI/AuthController.php
  src/API/WP/OAuthService.php
  src/MerchantCenter/AccountService.php
  src/Options/OptionsInterface.php
  tests/Unit/API/Site/Controllers/RestAPI/AuthControllerTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: changelog: tweak
