Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-06, with the labels that each got.

#2409 Add Integration Status Report for the partner integration.
  src/ConnectionTest.php
Labels: type: enhancement, changelog: add

#2410 Add remove partner token section in the Connection Test page
  src/ConnectionTest.php
Labels: type: enhancement, changelog: add

#2418 Add Tracking snapshot
  src/Tracking/TrackerSnapshot.php
Labels: type: enhancement, changelog: add

#2419 Adjust event tracking for the creating and claim buttons of Google Ads account
  .eslintrc.js
  jest.config.js
  js/src/components/google-ads-account-card/claim-account-button.js
  js/src/components/google-ads-account-card/claim-account-button.test.js
  js/src/components/google-ads-account-card/claim-account-modal.js
  js/src/components/google-ads-account-card/create-account.js
  js/src/components/google-ads-account-card/terms-modal/index.js
  js/src/components/google-ads-account-card/terms-modal/index.test.js
  js/src/hooks/useEventPropertiesFilter.js
  js/src/hooks/useEventPropertiesFilter.test.js
  js/src/index.test.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/ads-stepper/index.test.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.js
  js/src/setup-mc/setup-stepper/saved-setup-stepper.test.js
  js/src/tests/expectComponentToRecordEventWithFilteredProperties.js
  js/src/tests/jest-unit.setup.js
  js/src/utils/tracks.js
  js/src/utils/tracks.test.js
Labels: changelog: tweak

#2421 Adjust click event tracking when connecting, disconnecting, and opening billing setup for Google Ads account
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-ads-account-card/connect-ads/index.test.js
  js/src/components/google-ads-account-card/disconnect-account.js
  js/src/components/google-ads-account-card/disconnect-account.test.js
  js/src/components/paid-ads/billing-card/billing-setup-card.js
  js/src/components/paid-ads/billing-card/billing-setup-card.test.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/google-ads-account-section.js
  js/src/tests/expectComponentToRecordEventWithFilteredProperties.js
  src/Tracking/README.md
Labels: changelog: tweak

#2420 Disallow tracking enabled check in the extension
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Tracking/TrackerSnapshot.php
Labels: type: bug, changelog: fix

#2423 Fix fatal error when fetching marketing campaigns for Marketing Channel
  src/MultichannelMarketing/GLAChannel.php
  tests/Unit/MultichannelMarketing/GLAChannelTest.php
Labels: type: bug, changelog: fix

#2428 API Pull - Enable pull and push mechanism to work together
  src/Coupon/SyncerHooks.php
  src/Jobs/Notifications/ShippingNotificationJob.php
  src/MerchantCenter/MerchantCenterService.php
  src/Product/SyncerHooks.php
  src/Shipping/SyncerHooks.php
  tests/Unit/Coupon/SyncerHooksTest.php
  tests/Unit/Product/SyncerHooksTest.php
  tests/Unit/Shipping/SyncerHooksTest.php
Labels: changelog: update

#2433 Add E2E tests for WP Consent API integration
  tests/e2e/bin/test-env-setup.sh
  tests/e2e/specs/gtag-events/wp-consent-api.test.js
  tests/e2e/test-snippets/test-snippets.php
Labels: changelog: dev

#2432 [Revert] Update docs domain name to Woo.com
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  README.md
  docs/gtag-consent-mode.md
  google-listings-and-ads.php
  js/src/components/contact-information/index.js
  js/src/components/google-account-card/connect-google-account-card.js
  js/src/components/google-account-card/read-more-link.js
  js/src/components/google-account-card/request-full-access-google-account-card.js
  js/src/components/help-icon-button.js
  js/src/get-started-page/faqs/index.js
  js/src/get-started-page/features-card/index.js
  js/src/settings/edit-phone-number.js
  js/src/settings/edit-store-address.js
  js/src/setup-mc/setup-stepper/store-requirements/pre-launch-checklist/index.js
  package.json
  readme.txt
  src/Integration/WooCommercePreOrders.php
  src/Menu/MenuFixesTrait.php
  src/MerchantCenter/MerchantStatuses.php
  src/MultichannelMarketing/GLAChannel.php
  src/Notes/LeaveReviewActionTrait.php
  src/Notes/SetupCampaign.php
  src/PluginHelper.php
  src/Tracking/README.md
  tests/e2e/specs/setup-mc/step-3-confirm-store-requirements.test.js
Labels: changelog: tweak

#2425 Add integration with WP Consent API
  js/src/wp-consent-api/index.js
  src/Google/GlobalSiteTag.php
  tests/e2e/bin/test-env-setup.sh
  tests/e2e/specs/gtag-events/wp-consent-api.test.js
  tests/e2e/test-snippets/test-snippets.php
  webpack.config.js
Labels: type: enhancement, changelog: add

#2436 [API Pull] Add language param in settings endpoint
  src/Integration/WPCOMProxy.php
Labels: changelog: tweak

#2437 Fix issue with inconsistent metadata format
  src/Integration/WPCOMProxy.php
Labels: type: bug, changelog: fix

#2438 Add docs note about WP Consent API integration
  README.md
  docs/gtag-consent-mode.md
Labels: changelog: tweak

#2442 Add a query param `campaign=saved` to the dashboard URL when campaign was successfully created and saved
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/utils/urls.js
Labels: type: enhancement, changelog: add

#2443 Change connection test page capabilities to manage_woocommerce
  src/ConnectionTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: changelog: tweak

#2424 [API Pull] Auth Flow
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/google-mc-account-card/connected-google-mc-account-card.js
  src/API/Google/Middleware.php
  src/API/Site/Controllers/RestAPI/AuthController.php
  src/API/WP/OAuthService.php
  src/MerchantCenter/AccountService.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/API/WP/OAuthServiceTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: type: enhancement, changelog: add

#2447 Update connect server URL in test proxy configuration
  tests/proxy/config.js
Labels: type: bug, changelog: fix

#2430 API Pull - Revoke access if plugin is deactivated
  src/API/Site/Controllers/RestAPI/AuthController.php
  src/API/WP/OAuthService.php
  src/Internal/DependencyManagement/ProxyServiceProvider.php
  src/Proxies/Jetpack.php
  tests/Unit/API/WP/OAuthServiceTest.php
Labels: type: enhancement, changelog: add
