Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-12, with the labels that each got.

#2705 Fix the failed E2E test case introduced by pull request 2698
  tests/e2e/specs/dashboard/edit-free-listings.test.js
  tests/e2e/specs/setup-mc/step-2-product-listings.test.js
  tests/e2e/utils/mock-requests.js
Labels: changelog: dev

#2700 Prevent translations from being called early
  src/API/Google/Middleware.php
  src/API/Google/Settings.php
  src/ConnectionTest.php
  src/Exception/ExtensionRequirementException.php
  src/Exception/InvalidVersion.php
  src/Exception/RuntimeExceptionWithMessageFunction.php
  src/Internal/DependencyManagement/ThirdPartyServiceProvider.php
  src/Internal/Requirements/RequirementValidator.php
  src/Proxies/WC.php
  tests/Unit/API/Google/MiddlewareTest.php
Labels: type: bug, changelog: fix

#2706 Avoid errors caused by automatically saving invalid shipping times during onboarding
  js/src/components/free-listings/setup-free-listings/index.js
Labels: type: bug, changelog: fix

#2709 Centralize frontend end images to the dedicated directory
  js/src/components/account-card/index.js
  js/src/components/free-listings/configure-product-listings/hero/index.js
  js/src/components/paid-ads/campaign-preview/campaign-preview.js
  js/src/components/paid-ads/campaign-preview/mockup-display.js
  js/src/components/paid-ads/campaign-preview/mockup-gmail.js
  js/src/components/paid-ads/campaign-preview/mockup-map.js
  js/src/components/paid-ads/campaign-preview/mockup-search.js
  js/src/components/paid-ads/campaign-preview/mockup-shopping.js
  js/src/components/paid-ads/campaign-preview/mockup-youtube.js
  js/src/dashboard/campaign-creation-success-guide/index.js
  js/src/get-started-page/benefits-card/index.js
  js/src/get-started-page/customer-quotes-card/index.js
  js/src/get-started-page/features-card/index.js
  js/src/get-started-page/get-started-card/index.js
  js/src/get-started-page/get-started-with-hero-card/index.js
  js/src/images/campaign-preview/ad-corner-buttons-image.svg
  js/src/images/campaign-preview/gmail-logo.svg
  js/src/images/campaign-preview/google-shopping-logo.svg
  js/src/images/campaign-preview/map-background.png
  js/src/images/campaign-preview/product-sample-image.jpg
  js/src/images/campaign-preview/shop-sample-logo.png
  js/src/images/campaign-preview/youtube-logo.svg
  js/src/images/final-url-icon.svg
  js/src/images/get-started/benefits.png
  js/src/images/get-started/hero.png
  js/src/images/get-started/img-dashboard.svg
  js/src/images/get-started/img-free-listings.svg
  js/src/images/get-started/img-product-promotion.svg
  js/src/images/get-started/img-quote.svg
  js/src/images/get-started/motivation.svg
  js/src/images/google-free-listings.png
  js/src/images/logo/gogole-g-logo.svg
  js/src/images/logo/google-ads-logo.svg
  js/src/images/logo/google-logo.svg
  js/src/images/logo/google-merchant-center-logo.svg
  js/src/images/logo/woocommerce-logo.svg
  js/src/images/logo/wp-logo.svg
  js/src/images/success-guide-header.svg
  js/src/product-feed/submission-success-guide/index.js
Labels: changelog: dev

#2712 Clean up unnecessary files under `js/src`
  js/src/components/wistia-video/index.js
  js/src/components/wistia-video/index.scss
  js/src/hello/index.js
  js/src/hello/index.test.js
  js/src/hooks/useScript.js
Labels: changelog: dev

#2697 Ensure coupon brand restrictions are uploaded to Google Merchant Center.
  src/Coupon/SyncerHooks.php
  src/Coupon/WCCouponAdapter.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  tests/Unit/Coupon/SyncerHooksTest.php
  tests/Unit/Coupon/WCCouponAdapterTest.php
Labels: type: bug, changelog: fix

#2713 Remove assertions from `reducer.test.js` that prevent the next state from being created by a way mutating unrelated references
  js/src/data/test/__helpers__/index.js
  js/src/data/test/reducer.test.js
Labels: changelog: dev

#2716 Combine `AppIconButton` and `HelpIconButton`
  js/src/components/app-icon-button/README.md
  js/src/components/app-icon-button/index.js
  js/src/components/help-icon-button/index.js
  js/src/components/help-icon-button/index.module.scss
  src/Tracking/README.md
Labels: changelog: dev

#2714 Fix initial php 8.4 compatibility
  bin/GoogleAdsCleanupServices.php
  bin/SymfonyPolyfillCleanup.php
  bin/prefix-vendor-namespace.php
  composer.json
  composer.lock
  src/Assets/BaseAsset.php
  src/Assets/ScriptAsset.php
  src/Assets/ScriptWithBuiltDependenciesAsset.php
  src/Assets/StyleAsset.php
  src/Container.php
  src/DB/Table/BudgetRecommendationTable.php
  src/Exception/ExceptionWithResponseData.php
  src/Exception/RuntimeExceptionWithMessageFunction.php
  src/Google/InvalidCouponEntry.php
  src/Infrastructure/View.php
  src/Internal/DependencyManagement/AbstractServiceProvider.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/DBServiceProvider.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Internal/DependencyManagement/ProxyServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Internal/DependencyManagement/ThirdPartyServiceProvider.php
  src/MerchantCenter/AccountService.php
  src/MerchantCenter/MerchantStatuses.php
  src/Shipping/ShippingLocation.php
  src/Validator/ImageUrlConstraintValidator.php
  src/View/PHPView.php
  tests/Tools/HelperTrait/GuzzleClientTrait.php
  tests/Unit/API/ClientTest.php
  tests/Unit/API/Google/AdsCampaignTest.php
  tests/Unit/API/Google/AdsReportTest.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/API/Google/SiteVerificationTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeControllerTest.php
  tests/Unit/API/WP/OAuthServiceTest.php
  tests/Unit/Ads/AccountServiceTest.php
  tests/Unit/DB/ProductFeedQueryHelperTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: type: bug, changelog: fix

#2703 Increase the specificity of `__styled--overflow-visible` selector
  js/src/components/app-modal/index.scss
Labels: type: bug, changelog: fix

#2718 Remove unnecessary Sass imports of `@wordpress/base-styles`
  js/src/css/index.scss
Labels: changelog: dev

#2723 Drop Jetpack packages and switch to packages bundled with WooCommerce
  .github/workflows/php-unit-tests.yml
  README.md
  composer.json
  composer.lock
  google-listings-and-ads.php
  readme.txt
  src/Autoloader.php
Labels: changelog: tweak

#2725 Fix the issue of the saved max shipping time not showing after revisiting the free listings editing page
  js/src/data/reducer.js
  js/src/data/test/reducer.test.js
Labels: type: bug, changelog: fix

#2726 Eliminate the duplicate functions used to group shipping time data
  js/src/components/free-listings/configure-product-listings/shipping-time-setup/shipping-countries-form.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useSaveShippingTimes.js
  js/src/utils/getShippingTimeMapKey.js
  js/src/utils/getShippingTimesGroups.js
Labels: changelog: dev

#2728 PHP 8.4 package compatibility
  composer.json
  composer.lock
Labels: type: bug, changelog: fix

#2732 Fix Budget Recommendation data not populating on install
  src/DB/Table/BudgetRecommendationTable.php
  tests/Unit/DB/Query/BudgetRecommendationQueryTest.php
  tests/Unit/DB/Table/BudgetRecommendationTableTest.php
  tests/Unit/DB/Table/MerchantIssueTableTest.php
Labels: type: bug, changelog: fix

#2729 Fix related products E2Es for WC9.5
  tests/e2e/config/default.json
  tests/e2e/specs/gtag-events/gtag-events.test.js
  tests/e2e/utils/__fixtures__/all-products.fixture.json
  tests/e2e/utils/__fixtures__/related-products.fixture.mjs
  tests/e2e/utils/block-page.js
  tests/e2e/utils/customer.js
Labels: changelog: dev

#2734 Prevent duplicate conversion and purchase event tracking
  src/Google/GlobalSiteTag.php
  src/Proxies/WP.php
  tests/Unit/Google/GlobalSiteTagTest.php
  tests/bootstrap.php
Labels: type: bug, changelog: fix

#2739 Adjust conditions for MCM
  src/Internal/DependencyManagement/CoreServiceProvider.php
Labels: type: bug, changelog: fix

#2738 Clear previous errors after completing sync
  src/Product/ProductHelper.php
  tests/Unit/Product/ProductHelperTest.php
Labels: type: bug, changelog: fix

#2741 Move the shared files for the tax rate settings
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/shipping-rate-section/shipping-rate-section.js
  js/src/components/shipping-rate-section/shipping-rate-section.test.js
  js/src/hooks/useSettings.js
  js/src/pages/edit-free-listings/index.js
  js/src/pages/onboarding/setup-stepper/saved-setup-stepper.js
  js/src/pages/onboarding/setup-stepper/saved-setup-stepper.test.js
  js/src/pages/settings/setup-tax-rate/tax-rate.js
  js/src/pages/settings/setup-tax-rate/useDisplayTaxRate.js
  js/src/pages/settings/setup-tax-rate/useDisplayTaxRate.test.js
Labels: changelog: dev

#2740 Update Google Ads API to v18
  bin/GoogleAdsCleanupServices.php
  composer.json
  js/src/pages/dashboard/all-programs-table-card/index.scss
  src/API/Google/Ads.php
  src/API/Google/AdsAsset.php
  src/API/Google/AdsAssetGroup.php
  src/API/Google/AdsAssetGroupAsset.php
  src/API/Google/AdsCampaign.php
  src/API/Google/AdsCampaignBudget.php
  src/API/Google/AdsCampaignCriterion.php
  src/API/Google/AdsCampaignLabel.php
  src/API/Google/AdsConversionAction.php
  src/API/Google/AdsReport.php
  src/API/Google/AssetFieldType.php
  src/API/Google/BillingSetupStatus.php
  src/API/Google/CallToActionType.php
  src/API/Google/CampaignStatus.php
  src/API/Google/CampaignType.php
  src/API/Google/ExceptionTrait.php
  src/API/Google/MerchantMetrics.php
  src/API/Google/Query/AdsCampaignQuery.php
  src/API/Google/Query/AdsQuery.php
  src/API/Google/Query/AdsReportQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/API/Site/Controllers/Ads/CampaignController.php
  src/Google/Ads/GoogleAdsClient.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsAssetGroupTest.php
  tests/Unit/API/Google/AdsAssetTest.php
  tests/Unit/API/Google/AdsCampaignCriterionTest.php
  tests/Unit/API/Google/AdsCampaignTest.php
  tests/Unit/API/Google/AdsConversionActionTest.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantMetricsTest.php
  tests/Unit/API/Site/Controllers/Ads/CampaignControllerTest.php
  tests/Unit/Ads/AdsServiceTest.php
Labels: changelog: update

#2742 Reorganizes the frontend code related to the calls of settings APIs
  js/src/data/actions.js
  js/src/hooks/useSettings.js
  js/src/pages/edit-free-listings/index.js
  js/src/pages/onboarding/setup-stepper/saved-setup-stepper.js
  js/src/pages/onboarding/setup-stepper/setup-paid-ads.js
Labels: changelog: dev

#2743 Bump the minimum supported WordPress version to 6.1 to align with the minimum supported WooCommerce
  README.md
  google-listings-and-ads.php
  phpcs.xml.dist
  readme.txt
  tests/phpcs.xml.dist
Labels: changelog: update
