Repository woocommerce/google-listings-and-ads, pull requests merged in 2024-10, with the labels that each got.

#2626 [API PULL] Fix tests for Notifying delete products
  src/Product/SyncerHooks.php
Labels: type: bug, changelog: fix

#2608 2593: Update AppSelectControl to single select
  js/src/components/ads-account-select-control/index.js
  js/src/components/app-select-control/index.js
  js/src/components/app-select-control/index.scss
  js/src/components/google-ads-account-card/connect-ads/ads-account-select-control.js
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-ads-account-card/connect-ads/index.test.js
  js/src/components/google-mc-account-card/connect-mc/index.js
  js/src/components/merchant-center-select-control/index.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
Labels: changelog: update

#2577 Remove the billing setup page from the Ads setup flow
  js/src/components/paid-ads/ads-campaign/ads-campaign.js
  js/src/components/paid-ads/ads-campaign/index.js
  js/src/components/paid-ads/continue-button.js
  js/src/components/title-button-layout/index.js
  js/src/components/title-button-layout/index.scss
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/ads-stepper/index.test.js
  js/src/setup-ads/ads-stepper/setup-billing/billing-saved-card/index.js
  js/src/setup-ads/ads-stepper/setup-billing/billing-saved-card/index.scss
  js/src/setup-ads/ads-stepper/setup-billing/index.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/utils/pages/setup-ads/setup-budget.js
Labels: changelog: update

#2623 2535: Consolidate Ad Creation
  js/src/components/audience-country-select.js
  js/src/components/paid-ads/ads-campaign/ads-campaign.js
  js/src/components/paid-ads/ads-campaign/faqs-panel.js
  js/src/components/paid-ads/ads-campaign/paid-ads-features-section.js
  js/src/components/paid-ads/ads-campaign/paid-ads-features-section.scss
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/audience-section.js
  js/src/components/paid-ads/audience-section.scss
  js/src/components/paid-ads/audienceSection.test.js
  js/src/components/types.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/ads-stepper/index.test.js
  js/src/setup-ads/ads-stepper/setup-paid-ads.js
  js/src/setup-ads/setup-ads-form.js
  js/src/setup-mc/setup-stepper/clientSession.js
  js/src/setup-mc/setup-stepper/constants.js
  js/src/setup-mc/setup-stepper/setup-paid-ads.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/index.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/paid-ads-setup-sections.js
  js/src/setup-mc/setup-stepper/setup-paid-ads/setup-paid-ads.js
  js/src/setup-mc/setup-stepper/skip-button.js
  js/src/setup-mc/setup-stepper/skip-paid-ads-confirmation-modal.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/page.js
  tests/e2e/utils/pages/setup-ads/setup-budget.js
Labels: changelog: update

#2629 Update budget recommendation text
  js/src/components/paid-ads/budget-section/budget-recommendation/index.js
Labels: changelog: none

#2622 Hide `GTIN` field for new installs make readonly for existing installs
  src/Admin/Input/Input.php
  src/Admin/Product/Attributes/AttributesForm.php
  src/Admin/Product/Attributes/Input/GTINInput.php
  src/Internal/InstallTimestamp.php
  src/Options/OptionsInterface.php
  tests/Unit/Admin/Input/InputTest.php
  tests/Unit/Admin/Product/Attributes/Input/AttributeInputCollectionTest.php
  tests/Unit/Product/Attributes/GtinMappingTest.php
Labels: changelog: update

#2552 Update Budget Setup Card.
  js/src/components/paid-ads/budget-section/budget-recommendation/index.js
  js/src/components/paid-ads/budget-section/budget-recommendation/useFetchBudgetRecommendationEffect.js
  js/src/components/paid-ads/budget-section/index.js
  js/src/data/action-types.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/data/utils.js
  js/src/hooks/useFetchBudgetRecommendation.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/ads-stepper/setup-paid-ads.js
  js/src/setup-ads/index.js
  js/src/setup-ads/setup-ads-form.js
  js/src/setup-mc/setup-stepper/setup-paid-ads.js
  js/src/utils/getHighestBudget.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/setup-ads/setup-budget.js
Labels: changelog: update

#2583 Add minimum budget limit
  js/src/components/app-input-control/index.scss
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/campaign-assets-form.test.js
  js/src/components/paid-ads/validateCampaign.js
  js/src/components/paid-ads/validateCampaign.test.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/setup-ads/ads-stepper/setup-paid-ads.js
  js/src/setup-mc/setup-stepper/setup-paid-ads.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/setup-mc/step-4-complete-campaign.test.js
Labels: changelog: update

#2595 Remove the accounts connection page from the Ads Setup flow.
  js/src/setup-ads/ads-stepper/index.js
  js/src/setup-ads/ads-stepper/index.test.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
Labels: changelog: update

#2645 [GTIN] Add GTIN migration JOB
  src/ConnectionTest.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/MigrateGTIN.php
Labels: type: enhancement, changelog: add

#2649 [GTIN] Prepare GTIN with the correct format before sending it to MC
  src/Product/WCProductAdapter.php
Labels: changelog: tweak

#2658 2596: Refactor ConnectAds with updated AccountCard
  js/src/components/account-card/index.js
  js/src/components/account-card/index.scss
  js/src/components/google-combo-account-card/connect-account-card.js
  js/src/components/google-combo-account-card/connect-account-card.scss
  js/src/components/google-combo-account-card/connect-ads/connect-ads-body.js
  js/src/components/google-combo-account-card/connect-ads/connect-ads.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-combo-account-card/index.scss
Labels: changelog: update

#2657 2597: Refactor ConnectMC with updated AccountCard
  js/src/components/account-card/index.js
  js/src/components/account-card/index.scss
  js/src/components/google-combo-account-card/connect-account-card.js
  js/src/components/google-combo-account-card/connect-account-card.scss
  js/src/components/google-combo-account-card/connect-mc/connect-mc-body.js
  js/src/components/google-combo-account-card/connect-mc/connect-mc-footer.js
  js/src/components/google-combo-account-card/connect-mc/connect-mc.js
  js/src/components/google-combo-account-card/connected-google-combo-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-combo-account-card/index.scss
Labels: changelog: update

#2640 Onboarding: Connect to existing Ads account in Google Accounts Card
  js/src/components/account-card/index.js
  js/src/components/account-card/index.scss
  js/src/components/app-select-control/index.js
  js/src/components/app-select-control/index.scss
  js/src/components/google-ads-account-card/connect-ads/connect-button.js
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-combo-account-card/account-details.js
  js/src/components/google-combo-account-card/connect-ads/connect-ads-footer.js
  js/src/components/google-combo-account-card/connect-ads/connect-ads.js
  js/src/components/google-combo-account-card/connect-ads/index.js
  js/src/components/google-combo-account-card/connected-google-combo-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-combo-account-card/index.scss
  tests/e2e/specs/setup-mc/step-1-accounts.test.js
  tests/e2e/utils/pages/setup-mc/step-1-set-up-accounts.js
Labels: changelog: update

#2641 Show promo for setting up Google Ads on the product feed tabs #2539
  js/src/product-feed/product-statistics/create-campaign-notice/index.js
  js/src/product-feed/product-statistics/create-campaign-notice/index.scss
  js/src/product-feed/product-statistics/index.js
  tests/e2e/specs/product-feed/product-feed-campaign-notice.test.js
  tests/e2e/test-data/test-data.php
  tests/e2e/utils/api.js
  tests/e2e/utils/pages/product-feed.js
Labels: changelog: add
