Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-02, with the labels that each got.

#2711 Replace WooCommerce logo with Woo 2.0 Brand
  js/src/images/get-started/img-free-listings.svg
  js/src/images/logo/woocommerce-logo.svg
  js/src/pages/product-feed/submission-success-guide/index.js
  js/src/pages/product-feed/submission-success-guide/index.scss
Labels: status: on hold, changelog: tweak

#2780 Update the `caniuse-lite` package to the latest
  package-lock.json
Labels: changelog: dev

#2779 Supplement the implementation of API Pull for the Settings page
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/google-mc-account-card/merchant-center-account-info-card.js
  js/src/data/selectors.js
  js/src/data/types.js
  js/src/hooks/useGoogleMCAccount.js
  src/Tracking/README.md
Labels: changelog: tweak

#2792 Update ubuntu image to 22.04 for QIT WF
  .github/workflows/run-qit.yml
Labels: changelog: dev

#2790 Opt-in to URL expansion
  src/API/Google/AdsCampaign.php
Labels: changelog: tweak

#2793 Fix error displayed when accessing campaign assets editing page without attached asset groups
  js/src/pages/edit-paid-ads-campaign/index.js
Labels: type: bug, changelog: fix

#2788 [API PULL] Backbone for SYNC endpoint
  src/API/Site/Controllers/RestAPI/SyncController.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Options/OptionsInterface.php
Labels: type: enhancement, changelog: add

#2796 [API PULL] POST method for SYNC endpoint
  src/API/Site/Controllers/RestAPI/SyncController.php
Labels: type: enhancement, changelog: add

#2803 Remove a test assertion that occasionally causes PHPUnit tests to false positive
  tests/Unit/Coupon/WCCouponAdapterTest.php
Labels: changelog: dev

#2801 Add the conversion action details to the connection test page
  src/ConnectionTest.php
Labels: changelog: dev
