Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-05, with the labels that each got.

#2876 Remove PriceBenchmarkAdjustments component
  js/src/constants.js
  js/src/data/reducer.js
  js/src/data/test/reducer.test.js
  js/src/pages/price-benchmark/constants.js
  js/src/pages/price-benchmark/index.js
  js/src/pages/price-benchmark/index.scss
  js/src/pages/price-benchmark/price-benchmark-adjustments.js
  js/src/pages/price-benchmark/price-benchmark-suggestions.js
  js/src/pages/price-benchmark/price-benchmark-suggestions/index.js
  js/src/pages/price-benchmark/price-benchmark-suggestions/index.scss
  js/src/pages/price-benchmark/price-benchmark-table/index.js
  js/src/pages/price-benchmark/table-type-navigation.js
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  tests/e2e/utils/pages/price-benchmark.js
Labels: type: enhancement, changelog: add

#2872 Add/2865 banner component
  .externalized.json
  js/src/components/badge/index.scss
  js/src/constants.js
  js/src/css/abstracts/_colors.scss
  js/src/hooks/usePreference.js
  js/src/images/price-benchmark/price-benchmark-banner-icon.svg
  js/src/pages/price-benchmark/banner/index.js
  js/src/pages/price-benchmark/banner/index.scss
  js/src/pages/price-benchmark/index.js
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  tests/e2e/utils/mock-requests.js
Labels: type: enhancement, changelog: add

#2857 Add endpoint for getting price benchmarks summary data
  src/API/Google/MerchantPriceBenchmarks.php
  src/API/Site/Controllers/MerchantCenter/PriceBenchmarksController.php
  src/DB/Query/MerchantPriceBenchmarksQuery.php
  src/DB/Table/MerchantPriceBenchmarksTable.php
  src/DB/TableManager.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/DBServiceProvider.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Jobs/UpdateMerchantPriceBenchmarks.php
  src/MerchantCenter/PriceBenchmarks.php
  tests/Unit/API/Site/Controllers/MerchantCenter/PriceBenchmarksControllerTest.php
  tests/Unit/DB/Table/MerchantPriceBenchmarksTableTest.php
  tests/Unit/Jobs/UpdateMerchantPriceBenchmarksTest.php
Labels: type: enhancement, changelog: add

#2889 ChangePriceModal QA followup
  js/src/pages/price-benchmark/change-price-modal/index.scss
  js/src/pages/price-benchmark/change-price-modal/price-input-footer.js
  js/src/pages/price-benchmark/index.scss
  js/src/pages/price-benchmark/label.js
Labels: type: enhancement, changelog: add

#2896 Provide the recommendations and metrics when setting a campaign budget
  .stylelintrc.json
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/budget-section/index.js
  js/src/components/paid-ads/budget-section/index.scss
  js/src/components/paid-ads/budget-setup/budget-radio-control.js
  js/src/components/paid-ads/budget-setup/budget-setup-header.js
  js/src/components/paid-ads/budget-setup/budget-setup.js
  js/src/components/paid-ads/budget-setup/budget-setup.module.scss
  js/src/components/paid-ads/budget-setup/index.js
  js/src/components/paid-ads/budget-setup/low-budget-notice.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/campaign-assets-form.test.js
  js/src/components/paid-ads/validateCampaign.js
  js/src/components/paid-ads/validateCampaign.test.js
  js/src/components/section/index.scss
  js/src/pages/ads-onboarding/ads-stepper/setup-paid-ads.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/pages/onboarding/setup-stepper/clientSession.js
  js/src/pages/onboarding/setup-stepper/setup-paid-ads.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/onboarding/step-2-product-listings.test.js
  tests/e2e/specs/onboarding/step-3-complete-campaign.test.js
  tests/e2e/utils/pages/ads-onboarding/setup-budget.js
Labels: type: enhancement, changelog: add

#2836 Controller for fetching incentive credits from Middleware
  src/API/Google/Middleware.php
  src/API/Site/Controllers/Ads/IncentiveCreditsController.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/API/Site/Controllers/Ads/IncentiveCreditsControllerTest.php
Labels: type: enhancement, changelog: add

#2899 Add sales notice to ChangePriceModal
  js/src/pages/price-benchmark/change-price-modal/index.js
  js/src/pages/price-benchmark/change-price-modal/index.scss
  js/src/pages/price-benchmark/change-price-modal/metric-value.js
  js/src/pages/price-benchmark/change-price-modal/price-input-footer.js
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
Labels: type: enhancement, changelog: add

#2891 Enhance price benchmarks endpoint with uplift data
  src/API/Google/MerchantPriceBenchmarks.php
  src/API/Google/Query/MerchantPriceBenchmarksProductReportQuery.php
  src/API/Site/Controllers/MerchantCenter/PriceBenchmarksController.php
  tests/Unit/API/Site/Controllers/MerchantCenter/PriceBenchmarksControllerTest.php
Labels: type: bug, changelog: fix

#2878 Add/2828 price suggestions table optimized import
  js/src/pages/price-benchmark/index.js
  js/src/pages/price-benchmark/price-benchmark-suggestions/index.js
  js/src/shims/wp-dataviews.js
  package.json
  src/Admin/Admin.php
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  webpack.config.js
Labels: type: enhancement, changelog: add

#2905 Add Experience Rating Banner
  js/src/components/experience-rating-banner/index.js
  js/src/components/experience-rating-banner/index.scss
  js/src/pages/attribute-mapping/index.js
  js/src/pages/dashboard/index.js
  js/src/pages/product-feed/index.js
  js/src/pages/reports/index.js
  js/src/pages/settings/index.js
  js/src/pages/shipping/index.js
  tests/e2e/specs/app-ratings-overview/experience-rating-banner.test.js
  tests/e2e/utils/app-ratings-overview.js
Labels: type: enhancement, changelog: add

#2906 Test API requests for Price Benchmarks
  src/API/Google/Query/MerchantQuery.php
  tests/proxy/README.md
  tests/proxy/config.js
  tests/proxy/handler.js
  tests/proxy/mocks/mc/price-benchmarks/merchant-report.json
  tests/proxy/mocks/mc/price-benchmarks/price-competitiveness.json
  tests/proxy/mocks/mc/price-benchmarks/price-insights.json
Labels: changelog: none

#2912 Modify `mc/price-benchmarks` data processing
  src/API/Google/MerchantPriceBenchmarks.php
Labels: changelog: update

#2913 #2890 Update test proxy benchmarks data
  src/API/Google/MerchantPriceBenchmarks.php
  tests/proxy/handler.js
  tests/proxy/mocks/mc/price-benchmarks/price-competitiveness-item.json
  tests/proxy/mocks/mc/price-benchmarks/price-insights-item.json
  tests/proxy/mocks/mc/price-benchmarks/price-insights.json
Labels: changelog: update

#2910 Add a prompt for suggesting a higher budget to get back free ad credits before completing onboarding and ads onboarding
  js/src/components/adaptive-form/adaptive-form.js
  js/src/components/free-ad-credit/country-modal/countryAmount.js
  js/src/components/free-ad-credit/country-modal/index.js
  js/src/components/free-ad-credit/country-modal/index.scss
  js/src/components/free-ad-credit/index.js
  js/src/components/paid-ads/budget-incentive-prompt.js
  js/src/components/paid-ads/budget-incentive-prompt.test.js
  js/src/components/paid-ads/budget-setup/budget-radio-control.js
  js/src/components/paid-ads/budget-setup/budget-setup-header.js
  js/src/components/paid-ads/budget-setup/budget-setup.js
  js/src/components/paid-ads/budget-setup/budget-setup.module.scss
  js/src/components/paid-ads/budget-setup/budget-setup.test.js
  js/src/data/actions.js
  js/src/data/types.js
  js/src/pages/ads-onboarding/ads-stepper/setup-paid-ads.js
  js/src/pages/onboarding/setup-stepper/setup-paid-ads.js
  js/src/utils/ceil.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/onboarding/step-3-complete-campaign.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/ads-onboarding/setup-budget.js
Labels: type: enhancement, changelog: add

#2916 Fix the decimal precision issue when comparing a budget with a low recommended value, which is used to trigger a recommended budget notice
  js/src/components/paid-ads/budget-setup/budget-setup.js
  js/src/components/paid-ads/budget-setup/budget-setup.test.js
Labels: changelog: dev

#2926 Add FAQ link to the price benchmark suggestions header.
  js/src/pages/price-benchmark/faq-link.js
  js/src/pages/price-benchmark/price-benchmark-suggestions/index.js
  src/Tracking/README.md
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
Labels: type: enhancement, changelog: add

#2921 Fix `UpdateMerchantPriceBenchmarks` job is not properly running
  src/API/Google/MerchantPriceBenchmarks.php
  src/API/Google/Query/MerchantPriceBenchmarksQuery.php
  src/Jobs/UpdateMerchantPriceBenchmarks.php
  src/MerchantCenter/PriceBenchmarks.php
  tests/Unit/Jobs/UpdateMerchantPriceBenchmarksTest.php
Labels: type: bug, changelog: fix

#2909 Add Price Benchmark tracking
  js/src/pages/price-benchmark/change-price-modal/index.js
  js/src/pages/price-benchmark/change-price-modal/price-input-footer.js
  js/src/pages/price-benchmark/change-price.js
  js/src/pages/price-benchmark/constants.js
  js/src/pages/price-benchmark/price-benchmark-suggestions/index.js
  src/Tracking/README.md
Labels: type: enhancement, changelog: add

#2940 Add Notice to ChangePriceModal component
  js/src/components/horizontal-stacked-bar/index.scss
  js/src/pages/price-benchmark/change-price-modal/index.js
  js/src/pages/price-benchmark/change-price-modal/index.scss
  js/src/pages/price-benchmark/change-price-modal/price-input-footer.js
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
Labels: type: enhancement, changelog: add
