Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-04, with the labels that each got.

#2846 WordPress 6.8 and WooCommerce 9.8 compatibility: Fix an issue that could cause all pages not to display properly
  js/src/index.js
Labels: type: bug, changelog: fix

#2839 Add/2826 price benchmark tab
  js/src/components/main-tab-nav/main-tab-nav.js
  js/src/data/reducer.js
  js/src/data/test/reducer.test.js
  js/src/index.js
  js/src/pages/price-benchmark/constants.js
  js/src/pages/price-benchmark/index.js
  js/src/pages/price-benchmark/index.scss
  js/src/pages/price-benchmark/price-benchmark-adjustments.js
  js/src/pages/price-benchmark/price-benchmark-suggestions.js
  js/src/pages/price-benchmark/table-type-navigation.js
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  tests/e2e/utils/pages/price-benchmark.js
Labels: type: enhancement, changelog: add

#2844 Add ProductComparisonChart component
  js/src/components/horizontal-stacked-bar/bars.js
  js/src/components/horizontal-stacked-bar/index.js
  js/src/components/horizontal-stacked-bar/index.scss
  js/src/components/horizontal-stacked-bar/index.test.js
  js/src/components/horizontal-stacked-bar/legend.js
  js/src/constants.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/usePriceBenchmarkSummary.js
  js/src/pages/price-benchmark/index.js
  js/src/pages/price-benchmark/index.scss
  js/src/pages/price-benchmark/product-comparison-chart.js
Labels: type: enhancement, changelog: add

#2835 Fix Ads Merchant Linking Failure Display Issue & Improve Retry Mechanism
  js/src/components/google-combo-account-card/connect-ads/connect-existing-account.js
  js/src/components/google-combo-account-card/connect-ads/connect-existing-account.test.js
  js/src/components/google-combo-account-card/indicator.js
  js/src/hooks/useGoogleAdsAccountReady.js
  js/src/hooks/useGoogleMCAccount.js
  js/src/pages/ads-onboarding/ads-stepper/setup-accounts.js
  js/src/pages/onboarding/setup-stepper/setup-accounts/index.js
  src/API/Google/Ads.php
Labels: type: bug, changelog: fix

#2838 Add support for getting price benchmarks & suggestions from the Content API
  src/API/Google/MerchantPriceBenchmarks.php
  src/API/Google/Query/MerchantPriceBenchmarksQuery.php
  src/API/Google/Query/MerchantPriceSuggestionsQuery.php
  src/API/Site/Controllers/MerchantCenter/PriceBenchmarksController.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  tests/Unit/API/Site/Controllers/MerchantCenter/PriceBenchmarksControllerTest.php
Labels: type: enhancement, changelog: add

#2848 Fix merchant price competitiveness query
  src/API/Google/Query/MerchantPriceBenchmarksQuery.php
Labels: type: bug, changelog: fix

#2850 Revert the Grant API Pull Access in Onboarding feature
  js/src/components/account-card/index.scss
  js/src/components/app-notice/index.js
  js/src/components/app-notice/index.scss
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/enable-new-product-sync-notice.test.js
  js/src/components/google-account-card/authorize-wpcom-app-card.js
  js/src/components/google-account-card/connected-google-account-card.js
  js/src/components/google-account-card/index.js
  js/src/components/google-account-card/useSwitchGoogleAccount.js
  js/src/components/google-combo-account-card/connect-google-combo-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-combo-account-card/index.test.js
  js/src/components/google-mc-account-card/merchant-center-account-info-card.js
  js/src/css/shared/_woocommerce-admin.scss
  js/src/hooks/useGoogleMCAccount.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.test.js
  js/src/pages/onboarding/index.js
  js/src/pages/onboarding/setup-stepper/setup-accounts/index.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.test.js
  js/src/pages/settings/disconnect-modal/confirm-modal.js
  js/src/pages/settings/disconnect-modal/constants.js
  js/src/pages/settings/index.js
  js/src/pages/settings/linked-accounts.js
  js/src/utils/tracks.js
  src/API/Google/Middleware.php
  src/API/WP/OAuthService.php
  src/ConnectionTest.php
  src/MerchantCenter/AccountService.php
  src/MerchantCenter/MerchantCenterService.php
  src/Options/MerchantAccountState.php
  src/Tracking/README.md
  tests/Tools/HelperTrait/GuzzleClientTrait.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/e2e/specs/notifications/notifications-banner.test.js
  tests/e2e/specs/onboarding/step-1-accounts.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/onboarding/step-1-set-up-accounts.js
  tests/e2e/utils/pages/settings.js
Labels: changelog: dev, changelog: none

#2851 Add back the Grant API Pull Access in Onboarding feature
  js/src/components/account-card/index.scss
  js/src/components/app-notice/index.js
  js/src/components/app-notice/index.scss
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/enable-new-product-sync-notice.test.js
  js/src/components/google-account-card/authorize-wpcom-app-card.js
  js/src/components/google-account-card/connected-google-account-card.js
  js/src/components/google-account-card/index.js
  js/src/components/google-account-card/useSwitchGoogleAccount.js
  js/src/components/google-combo-account-card/connect-google-combo-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-combo-account-card/index.test.js
  js/src/components/google-mc-account-card/merchant-center-account-info-card.js
  js/src/css/shared/_woocommerce-admin.scss
  js/src/hooks/useGoogleMCAccount.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.test.js
  js/src/pages/onboarding/index.js
  js/src/pages/onboarding/setup-stepper/setup-accounts/index.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.test.js
  js/src/pages/settings/disconnect-modal/confirm-modal.js
  js/src/pages/settings/disconnect-modal/constants.js
  js/src/pages/settings/index.js
  js/src/pages/settings/linked-accounts.js
  js/src/utils/tracks.js
  src/API/Google/Middleware.php
  src/API/WP/OAuthService.php
  src/ConnectionTest.php
  src/MerchantCenter/AccountService.php
  src/MerchantCenter/MerchantCenterService.php
  src/Options/MerchantAccountState.php
  src/Tracking/README.md
  tests/Tools/HelperTrait/GuzzleClientTrait.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/e2e/specs/notifications/notifications-banner.test.js
  tests/e2e/specs/onboarding/step-1-accounts.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/onboarding/step-1-set-up-accounts.js
  tests/e2e/utils/pages/settings.js
Labels: changelog: dev

#2864 Fix the issue where the interlink between Google Merchant Center and Google Ads accounts may not be completed
  src/API/Google/Ads.php
  src/API/Google/Merchant.php
  src/Ads/AccountService.php
  src/MerchantCenter/AccountService.php
  tests/Unit/API/Google/AdsTest.php
  tests/Unit/API/Google/MerchantTest.php
  tests/Unit/Ads/AccountServiceTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: type: bug, changelog: fix

#2853 Add PriceBenchmarkSuggestions component
  .externalized.json
  js/src/components/badge/index.js
  js/src/components/badge/index.scss
  js/src/css/abstracts/_colors.scss
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/hooks/usePriceBenchmarkSuggestions.js
  js/src/pages/price-benchmark/change-price.js
  js/src/pages/price-benchmark/constants.js
  js/src/pages/price-benchmark/effectiveness-indicator.js
  js/src/pages/price-benchmark/index.scss
  js/src/pages/price-benchmark/label.js
  js/src/pages/price-benchmark/price-benchmark-suggestions.js
  js/src/pages/price-benchmark/price-benchmark-table/index.js
  js/src/pages/price-benchmark/price-benchmark-table/index.scss
  js/src/pages/price-benchmark/price/index.js
  js/src/pages/price-benchmark/price/index.scss
  js/src/pages/price-benchmark/price/index.test.js
  package-lock.json
  package.json
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  tests/e2e/utils/__fixtures__/price-benchmark-suggestions.json
  tests/e2e/utils/mock-requests.js
  webpack.config.js
Labels: type: enhancement, changelog: add

#2873 Revert the Grant API Pull Access in Onboarding feature
  js/src/components/account-card/index.scss
  js/src/components/app-notice/index.js
  js/src/components/app-notice/index.scss
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/enable-new-product-sync-notice.test.js
  js/src/components/google-account-card/authorize-wpcom-app-card.js
  js/src/components/google-account-card/connected-google-account-card.js
  js/src/components/google-account-card/index.js
  js/src/components/google-account-card/useSwitchGoogleAccount.js
  js/src/components/google-combo-account-card/connect-google-combo-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-combo-account-card/index.test.js
  js/src/components/google-mc-account-card/merchant-center-account-info-card.js
  js/src/css/shared/_woocommerce-admin.scss
  js/src/hooks/useGoogleMCAccount.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.test.js
  js/src/pages/onboarding/index.js
  js/src/pages/onboarding/setup-stepper/setup-accounts/index.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.test.js
  js/src/pages/settings/disconnect-modal/confirm-modal.js
  js/src/pages/settings/disconnect-modal/constants.js
  js/src/pages/settings/index.js
  js/src/pages/settings/linked-accounts.js
  js/src/utils/tracks.js
  src/API/Google/Middleware.php
  src/API/WP/OAuthService.php
  src/ConnectionTest.php
  src/MerchantCenter/AccountService.php
  src/MerchantCenter/MerchantCenterService.php
  src/Options/MerchantAccountState.php
  src/Tracking/README.md
  tests/Tools/HelperTrait/GuzzleClientTrait.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/e2e/specs/notifications/notifications-banner.test.js
  tests/e2e/specs/onboarding/step-1-accounts.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/onboarding/step-1-set-up-accounts.js
  tests/e2e/utils/pages/settings.js
Labels: changelog: update

#2860 Add empty metrics notice.
  js/src/data/actions.js
  js/src/images/price-benchmark/empty-metrics.svg
  js/src/pages/price-benchmark/empty-metrics-notice/index.js
  js/src/pages/price-benchmark/empty-metrics-notice/index.scss
  js/src/pages/price-benchmark/index.scss
  js/src/pages/price-benchmark/price-benchmark-suggestions.js
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  tests/e2e/utils/mock-requests.js
Labels: changelog: update

#2869 Add ChangePriceModal component
  js/src/components/badge/index.scss
  js/src/components/delta-value/index.js
  js/src/components/delta-value/index.scss
  js/src/components/delta-value/index.test.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/hooks/useDispatchProduct.js
  js/src/hooks/usePriceBenchmarkSuggestionsProduct.js
  js/src/hooks/useProduct.js
  js/src/pages/price-benchmark/change-price-modal/index.js
  js/src/pages/price-benchmark/change-price-modal/index.scss
  js/src/pages/price-benchmark/change-price-modal/metric-value.js
  js/src/pages/price-benchmark/change-price-modal/metric-value.scss
  js/src/pages/price-benchmark/change-price-modal/price-input-footer.js
  js/src/pages/price-benchmark/change-price.js
  js/src/pages/price-benchmark/constants.js
  js/src/pages/price-benchmark/price-benchmark-suggestions.js
  js/src/pages/price-benchmark/price-benchmark-table/index.scss
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  tests/e2e/utils/__fixtures__/price-benchmark-suggestions.json
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/price-benchmark.js
Labels: type: enhancement, changelog: add

#2859 Add budget metrics to the frontend data store and apply it to the budget setup UI
  js/src/components/app-input-control/index.js
  js/src/components/app-input-control/index.scss
  js/src/components/paid-ads/ads-campaign/ads-campaign.js
  js/src/components/paid-ads/budget-section/getMonthlyMaxEstimated.js
  js/src/components/paid-ads/budget-section/index.js
  js/src/components/paid-ads/campaign-assets-form.js
  js/src/components/paid-ads/campaign-assets-form.test.js
  js/src/data/action-types.js
  js/src/data/adapters.js
  js/src/data/adapters.test.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/data/test/utils.test.js
  js/src/data/types.js
  js/src/data/utils.js
  js/src/hooks/useBudgetMetrics.js
  js/src/hooks/useBudgetRecommendation.js
  js/src/hooks/useCountryCodesForBudgetQuery.js
  js/src/pages/ads-onboarding/ads-stepper/setup-paid-ads.js
  js/src/pages/create-paid-ads-campaign/index.js
  js/src/pages/edit-paid-ads-campaign/index.js
  js/src/pages/onboarding/setup-stepper/setup-paid-ads.js
  tests/e2e/specs/add-paid-campaigns/add-paid-campaigns.test.js
  tests/e2e/specs/onboarding/step-3-complete-campaign.test.js
  tests/e2e/utils/mock-requests.js
Labels: type: enhancement, changelog: add
