Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-06, with the labels that each got.

#2915 Banner close button.
  .externalized.json
  js/src/components/experience-rating-banner/index.js
  js/src/constants.js
  js/src/hooks/usePreference.js
  js/src/pages/attribute-mapping/index.test.js
  js/src/pages/dashboard/index.test.js
  js/src/pages/product-feed/index.test.js
  tests/e2e/specs/app-ratings-overview/experience-rating-banner.test.js
  tests/e2e/utils/mock-requests.js
Labels: type: enhancement, changelog: add

#2935 Fix sorting and pagination in the `mc/price-benchmarks` endpoint
  phpcs.xml.dist
  src/API/Google/MerchantPriceBenchmarks.php
  src/API/Google/Query/MerchantPriceBenchmarksProductReportQuery.php
  src/API/Site/Controllers/Ads/AssetGroupController.php
  src/API/Site/Controllers/MerchantCenter/PriceBenchmarksController.php
  src/DB/Query/MerchantPriceBenchmarksQuery.php
  src/DB/Table/MerchantPriceBenchmarksTable.php
  src/Jobs/UpdateMerchantPriceBenchmarks.php
  src/MerchantCenter/PriceBenchmarks.php
  src/Product/ProductHelper.php
  tests/Unit/API/Site/Controllers/MerchantCenter/PriceBenchmarksControllerTest.php
  tests/Unit/MerchantCenter/PriceBenchmarksTest.php
  views/bulk-edit/shop_coupon.php
Labels: changelog: update

#2934 Add server side logic to DataViews interaction
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/hooks/useDispatchProduct.js
  js/src/hooks/usePriceBenchmarkSuggestions.js
  js/src/hooks/usePriceBenchmarkSuggestionsProduct.js
  js/src/pages/price-benchmark/change-price-modal/index.js
  js/src/pages/price-benchmark/change-price-modal/price-input-footer.js
  js/src/pages/price-benchmark/change-price.js
  js/src/pages/price-benchmark/price-benchmark-suggestions/index.js
  js/src/utils/generateKeyFromObject.js
  js/src/utils/generateKeyFromObject.test.js
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  tests/e2e/utils/__fixtures__/price-benchmark-product-suggestions.json
  tests/e2e/utils/__fixtures__/price-benchmark-suggestions.json
  tests/e2e/utils/mock-requests.js
Labels: type: enhancement, changelog: add

#2951 Test Proxy: Update mock data for price benchmarks
  tests/proxy/mocks/mc/price-benchmarks/merchant-report.json
  tests/proxy/mocks/mc/price-benchmarks/price-competitiveness-item.json
  tests/proxy/mocks/mc/price-benchmarks/price-competitiveness.json
  tests/proxy/mocks/mc/price-benchmarks/price-insights-item.json
  tests/proxy/mocks/mc/price-benchmarks/price-insights.json
Labels: changelog: none

#2952 Price Benchmarks: Fix search and sort updates
  src/MerchantCenter/PriceBenchmarks.php
  tests/Unit/MerchantCenter/PriceBenchmarksTest.php
Labels: changelog: none

#2954 Fix null price gap.
  js/src/pages/price-benchmark/price-benchmark-suggestions/index.js
Labels: type: bug, changelog: fix

#2914 Add Good Button logic for App Ratings
  js/src/components/experience-rating-banner/feedback-modal.js
  js/src/components/experience-rating-banner/index.js
  js/src/components/experience-rating-banner/index.scss
  tests/e2e/specs/app-ratings-overview/experience-rating-banner.test.js
  tests/e2e/utils/app-ratings-overview.js
Labels: type: enhancement, changelog: add

#2958 Add tracking events for App Ratings
  js/src/components/experience-rating-banner/feedback-modal.js
  js/src/components/experience-rating-banner/index.js
  js/src/constants.js
  src/Tracking/README.md
Labels: type: enhancement, changelog: add

#2948 Add the `EnhancedConversions` settings card.
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/pages/settings/enhanced-conversions/index.js
  js/src/pages/settings/enhanced-conversions/setup-enhanced-conversions.js
  js/src/pages/settings/enhanced-conversions/useEnableEnhancedConversions.js
  js/src/pages/settings/index.js
  js/src/pages/settings/setup-tax-rate/setup-tax-rate.js
  js/src/pages/settings/setup-tax-rate/tax-rate.js
  tests/e2e/specs/settings/settings.test.js
Labels: type: enhancement, changelog: add

#2943 Add Enhanced Conversions prompt to successful onboarding modal
  js/src/components/external/wordpress/guide/index.js
  js/src/pages/product-feed/submission-success-guide/index.js
  tests/e2e/specs/onboarding/step-3-complete-campaign.test.js
Labels: type: enhancement, changelog: add

#2961 Update README.md regarding development-related matters
  README.md
Labels: type: documentation, changelog: doc

#2960 Update Google Ads API from v18 to v20 for the Budget recommendations feature
  src/API/Google/BudgetMetrics.php
  src/API/Google/BudgetRecommendations.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/BudgetMetricsTest.php
  tests/Unit/API/Google/BudgetRecommendationsTest.php
Labels: changelog: update

#2946 Group similar tests together.
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
Labels: type: enhancement, changelog: add

#2966 Avoid the fallback in `CSSTransition` that would cause it to use the deprecated `findDOMNode`
  js/src/components/paid-ads/campaign-preview/campaign-preview.js
  js/src/components/paid-ads/campaign-preview/mockup-display.js
  js/src/components/paid-ads/campaign-preview/mockup-gmail.js
  js/src/components/paid-ads/campaign-preview/mockup-map.js
  js/src/components/paid-ads/campaign-preview/mockup-search.js
  js/src/components/paid-ads/campaign-preview/mockup-shopping.js
  js/src/components/paid-ads/campaign-preview/mockup-youtube.js
Labels: changelog: dev

#2967 Fix the invalid event property names sent to WC Tracks
  js/src/pages/dashboard/all-programs-table-card/edit-program-button/edit-program-prompt-modal.js
  js/src/pages/reports/products/products-report-filters.js
  js/src/utils/tracks.js
  src/Tracking/README.md
Labels: changelog: dev

#2975 Add ExperienceRatingBanner to price benchmarks tab.
  js/src/pages/price-benchmark/index.js
Labels: type: enhancement, changelog: add

#2979 Fix E2E tests for app ratings and minor tweaks
  js/src/pages/dashboard/index.js
  src/Tracking/README.md
  tests/e2e/specs/app-ratings-overview/experience-rating-banner.test.js
Labels: changelog: none

#2990 Add resolver for getEnableEnhancedConversions and update E2E tests.
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/hooks/useEnhancedConversionsStatus.js
  js/src/pages/settings/enhanced-conversions/setup-enhanced-conversions.js
  js/src/pages/settings/enhanced-conversions/useEnableEnhancedConversions.js
  tests/e2e/specs/settings/settings.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/settings.js
Labels: type: bug, changelog: fix

#2984 Prevent user from continuing if minimum shipping time is not set
  js/src/components/free-listings/configure-product-listings/__snapshots__/checkErrors.test.js.snap
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
  js/src/components/free-listings/configure-product-listings/shipping-time-setup/shipping-countries-form.js
  tests/e2e/specs/onboarding/step-2-product-listings.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/onboarding/step-2-product-listings.js
Labels: type: bug, changelog: fix
