Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-08, with the labels that each got.

#3039 Add YouTube icon to video assets
  js/src/components/paid-ads/asset-group/asset-group-editor/media-selector.js
  js/src/components/paid-ads/asset-group/asset-group-editor/media-selector.scss
  js/src/components/paid-ads/asset-group/asset-group-editor/youtube-video-selector/index.test.js
  js/src/images/pmax-assets-improvements/youtube-icon.svg
Labels: changelog: none

#3035 [GOOWOO-229] Campaign assets - video requirement hint
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-field.scss
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-group-videos-section.js
Labels: changelog: none

#3038 Restore key prop
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-field.js
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-group-editor.js
Labels: type: bug, changelog: fix

#3047 Remove EnableNewProductSyncButton component
  js/src/components/enable-new-product-sync-button.js
  js/src/components/google-mc-account-card/merchant-center-account-info-card.js
  src/Tracking/README.md
  tests/e2e/specs/settings/settings-wpcom-rest-api.test.js
Labels: type: bug, changelog: fix

#3007 Remove unnecessary kebab menu from `Google for WooCommerce` setup task
  src/TaskList/CompleteSetupTask.php
  tests/Unit/TaskList/CompleteSetupTaskTest.php
Labels: type: bug, changelog: fix

#3055 Add Budget Recommendation badge to campaign list
  js/src/components/badge/index.scss
  js/src/constants.js
  js/src/hooks/useRaiseBudgetRecommendations.js
  js/src/hooks/useRaiseBudgetRecommendations.test.js
  js/src/pages/dashboard/all-programs-table-card/budget-recommendation-badge.js
  js/src/pages/dashboard/all-programs-table-card/index.js
  js/src/pages/dashboard/all-programs-table-card/index.test.js
Labels: type: enhancement, changelog: add

#3071 Include the current plugin version in the `/settings/google-for-woocommerce` WPCOMProxy endpoint
  src/Integration/WPCOMProxy.php
  tests/Unit/Integration/WPCOMProxyTest.php
Labels: changelog: update

#3072 Fix Dependabot Security Alerts
  jest.config.js
  package-lock.json
  package.json
Labels: type: bug, changelog: fix

#3070 Schedule job to sync all products when the Push mode of product sync is switched to enable
  src/API/Site/Controllers/RestAPI/SyncController.php
  src/Event/StartProductSync.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Options/Options.php
  src/Proxies/WP.php
  src/Proxies/WPAwareInterface.php
  src/Proxies/WPAwareTrait.php
  tests/Tools/HelperTrait/OptionsTrait.php
  tests/Unit/API/Site/Controllers/RestAPI/SyncControllerTest.php
  tests/Unit/Event/StartProductSyncTest.php
Labels: changelog: update
