Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-01, with the labels that each got.

#2747 Refine the vertical gap for `Section` component
  js/src/components/paid-ads/asset-group/asset-group-section.js
  js/src/components/paid-ads/budget-section/index.js
  js/src/components/paid-ads/budget-section/index.scss
  js/src/components/section/index.js
  js/src/components/shipping-rate-section/shipping-rate-section.js
  js/src/components/stepper/step-content-footer/index.js
  js/src/components/vertical-gap-layout/index.js
  js/src/components/vertical-gap-layout/index.scss
  js/src/pages/ads-onboarding/ads-stepper/setup-accounts.js
  js/src/pages/onboarding/setup-stepper/setup-accounts/index.js
  js/src/pages/settings/linked-accounts.js
  js/src/pages/settings/reconnect-wpcom-account/reconnect-wpcom-account.js
Labels: changelog: dev

#2748 Show leaving prompt in Edit Ads Campaign if the form was modified.
  js/src/pages/edit-paid-ads-campaign/index.js
Labels: type: bug, changelog: fix

#2749 Move tax rate setup to the Settings page
  js/src/components/conditional-section.js
  js/src/components/free-listings/configure-product-listings/__snapshots__/checkErrors.test.js.snap
  js/src/components/free-listings/configure-product-listings/checkErrors.js
  js/src/components/free-listings/configure-product-listings/checkErrors.test.js
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-card.test.js
  js/src/components/shipping-rate-section/shipping-rate-section.test.js
  js/src/pages/onboarding/setup-stepper/saved-setup-stepper.js
  js/src/pages/settings/index.js
  js/src/pages/settings/setup-tax-rate/index.js
  js/src/pages/settings/setup-tax-rate/setup-tax-rate.js
  js/src/pages/settings/setup-tax-rate/tax-rate.js
  tests/e2e/specs/dashboard/edit-free-listings.test.js
  tests/e2e/specs/settings/settings.test.js
  tests/e2e/utils/pages/edit-free-listings.js
  tests/e2e/utils/pages/settings.js
Labels: changelog: update

#2751 Move the Edit free listings page to a dedicated page and rename page to Shipping
  js/src/components/free-listings/setup-free-listings/form-content.js
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/components/main-tab-nav/main-tab-nav.js
  js/src/index.js
  js/src/pages/dashboard/all-programs-table-card/edit-program-button/edit-program-prompt-modal.js
  js/src/pages/dashboard/all-programs-table-card/index.js
  js/src/pages/dashboard/all-programs-table-card/index.test.js
  js/src/pages/dashboard/index.js
  js/src/pages/onboarding/setup-stepper/hero/index.js
  js/src/pages/onboarding/setup-stepper/hero/index.scss
  js/src/pages/onboarding/setup-stepper/saved-setup-stepper.js
  js/src/pages/onboarding/setup-stepper/saved-setup-stepper.test.js
  js/src/pages/onboarding/setup-stepper/setup-listings.js
  js/src/pages/shipping/hasUnsavedShippingRates.js
  js/src/pages/shipping/hasUnsavedShippingRates.test.js
  js/src/pages/shipping/index.js
  js/src/utils/urls.js
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Menu/Shipping.php
  tests/e2e/specs/dashboard/edit-free-listings.test.js
  tests/e2e/specs/settings/settings.test.js
  tests/e2e/specs/shipping.test.js
  tests/e2e/utils/pages/dashboard.js
  tests/e2e/utils/pages/shipping.js
Labels: changelog: update

#2753 Clean up the leftover parameters used to support WooCommerce Navigation
  js/src/index.js
  src/Menu/AttributeMapping.php
  src/Menu/ProductFeed.php
  src/Menu/Reports.php
  src/Menu/Settings.php
Labels: changelog: dev

#2754 Fix tests in WooCommerce 9.6
  tests/Unit/Product/AttributeMapping/AttributeMappingWCProductAdapterTest.php
  tests/bootstrap.php
Labels: changelog: dev

#2755 Fix E2E tests in WC 9.6
  tests/e2e/bin/test-env-setup.sh
Labels: changelog: dev

#2756 Pop up confirmation prompt on the Shipping page before saving changes
  js/src/components/free-listings/setup-free-listings/index.js
  js/src/pages/shipping/confirm-save-modal.js
  js/src/pages/shipping/confirm-save-modal.module.scss
  js/src/pages/shipping/index.js
  tests/e2e/specs/shipping.test.js
  tests/e2e/utils/pages/shipping.js
Labels: changelog: tweak

#2760 Sync shipping max times to Google Merchant Center
  src/API/Google/Settings.php
  src/DB/Query/ShippingTimeQuery.php
  src/Shipping/GoogleAdapter/AbstractShippingSettingsAdapter.php
  tests/Unit/Shipping/GoogleAdapter/DBShippingSettingsAdapterTest.php
  tests/Unit/Shipping/GoogleAdapter/WCShippingSettingsAdapterTest.php
Labels: type: bug, changelog: fix

#2763 Remove unused Http proxy class
  src/Internal/DependencyManagement/ProxyServiceProvider.php
  src/Proxies/Http.php
Labels: changelog: tweak

#2764 Refactor installer class to load dependencies when needed
  src/Installer.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/DBServiceProvider.php
Labels: changelog: tweak

#2761 Consistent usage of ContainerAware
  src/API/Google/Middleware.php
  src/API/Google/Settings.php
  src/API/Site/Controllers/Ads/ReportsController.php
  src/API/Site/Controllers/BaseReportsController.php
  src/API/Site/Controllers/MerchantCenter/ReportsController.php
  src/API/Site/Controllers/MerchantCenter/ShippingTimeController.php
  src/API/Site/RESTControllers.php
  src/Admin/BulkEdit/BulkEditInitializer.php
  src/Ads/AccountService.php
  src/ConnectionTest.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/MerchantCenter/AccountService.php
  src/Tracking/EventTracking.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeBatchControllerTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeControllerTest.php
  tests/Unit/Ads/AccountServiceTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/MerchantCenter/ValidateAddressTest.php
Labels: changelog: tweak

#2758 Conditionally load job classes
  src/API/Site/Controllers/GTINMigrationController.php
  src/ConnectionTest.php
  src/Coupon/SyncerHooks.php
  src/Infrastructure/GoogleListingsAndAdsPlugin.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Jobs/JobException.php
  src/Jobs/JobInterface.php
  src/Jobs/JobRepository.php
  src/MerchantCenter/AccountService.php
  src/MerchantCenter/MerchantStatuses.php
  src/Product/SyncerHooks.php
  src/Settings/SyncerHooks.php
  src/Shipping/SyncerHooks.php
  tests/Unit/Jobs/JobInitializerTest.php
  tests/Unit/Jobs/UpdateMerchantProductStatusesTest.php
  tests/Unit/Jobs/UpdateProductsTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
Labels: changelog: tweak

#2762 Avoid the negative shipping rate leading to false onboarding completion and make its error message more explicit
  js/src/pages/onboarding/setup-stepper/setup-paid-ads.js
  js/src/pages/shipping/index.js
  src/Shipping/CountryRatesCollection.php
  tests/Unit/Shipping/CountryRatesCollectionTest.php
Labels: type: bug, changelog: fix

#2765 Add an admin service provider for WP Admin requests
  src/Admin/Admin.php
  src/Admin/BulkEdit/BulkEditInitializer.php
  src/Admin/MetaBox/AbstractMetaBox.php
  src/Admin/MetaBox/MetaBoxInterface.php
  src/Admin/Redirect.php
  src/ConnectionTest.php
  src/Container.php
  src/Internal/DependencyManagement/AdminServiceProvider.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
Labels: changelog: tweak

#2772 Resolve some of the plugin check errors and warnings
  google-listings-and-ads.php
  phpcs.xml.dist
  src/API/Google/AdsConversionAction.php
  src/API/Google/Connection.php
  src/API/Google/Middleware.php
  src/API/WP/NotificationsService.php
  src/Assets/ScriptAsset.php
  src/ConnectionTest.php
  src/Coupon/CouponSyncer.php
  src/DB/Migration/Migration20211228T1640692399.php
  src/DB/Query/ShippingRateQuery.php
  src/DB/Table/AttributeMappingRulesTable.php
  src/DB/Table/BudgetRecommendationTable.php
  src/DB/Table/MerchantIssueTable.php
  src/DB/Table/ShippingRateTable.php
  src/DB/Table/ShippingTimeTable.php
  src/Jobs/ActionSchedulerJobMonitor.php
  src/Jobs/Notifications/AbstractItemNotificationJob.php
  src/MerchantCenter/MerchantStatuses.php
  src/Notes/LeaveReviewActionTrait.php
  src/Product/BatchProductHelper.php
  src/Product/ProductSyncer.php
  src/Product/WCProductAdapter.php
  src/Shipping/GoogleAdapter/DBShippingSettingsAdapter.php
  src/Shipping/GoogleAdapter/WCShippingSettingsAdapter.php
  tests/Tools/HelperTrait/CouponTrait.php
  tests/Tools/HelperTrait/GuzzleClientTrait.php
  tests/Tools/HelperTrait/ProductTrait.php
  tests/Unit/API/Site/Controllers/MerchantCenter/SettingsSyncControllerTest.php
  tests/Unit/Coupon/WCCouponAdapterTest.php
  tests/Unit/MerchantCenter/MerchantStatusesTest.php
  tests/Unit/Product/Attributes/AttributeManagerTest.php
  tests/Unit/Product/WCProductAdapterTest.php
  tests/Unit/Shipping/ZoneLocationsParserTest.php
  tests/Unit/View/PHPViewFactoryTest.php
  tests/Unit/View/PHPViewTest.php
  tests/phpcs.xml.dist
Labels: changelog: tweak

#2774 Adjust some query and table functions
  src/DB/Query.php
  src/DB/Table.php
Labels: changelog: tweak
