Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-03, with the labels that each got.

#2800 Extract the API call of WPCOM app authorization URL and clean up authorization URL queries after being redirected back
  js/src/components/enable-new-product-sync-button.js
  js/src/data/actions.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.test.js
Labels: changelog: dev

#2802 Add the process of granting API Pull access to the onboarding flow
  js/src/components/account-card/index.scss
  js/src/components/enable-new-product-sync-button.js
  js/src/components/google-account-card/authorize-wpcom-app-card.js
  js/src/components/google-account-card/index.js
  js/src/components/google-account-card/useSwitchGoogleAccount.js
  js/src/components/google-combo-account-card/connect-google-combo-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-combo-account-card/index.test.js
  js/src/css/shared/_woocommerce-admin.scss
  js/src/hooks/useGoogleMCAccount.js
  js/src/pages/onboarding/index.js
  js/src/pages/onboarding/setup-stepper/setup-accounts/index.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.js
  src/MerchantCenter/MerchantCenterService.php
  src/Tracking/README.md
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/e2e/specs/notifications/notifications-banner.test.js
  tests/e2e/specs/onboarding/step-1-accounts.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/onboarding/step-1-set-up-accounts.js
Labels: type: enhancement, changelog: add

#2806 Fix the issue of not being able to reconnect to the auto-selected Google ads account during onboarding
  js/src/components/google-combo-account-card/connect-ads/connect-existing-account.js
  js/src/components/google-combo-account-card/connect-ads/connect-existing-account.test.js
Labels: type: bug, changelog: fix

#2804 Block Notifications when PULL mode is disabled
  src/API/Site/Controllers/RestAPI/SyncController.php
  src/API/WP/NotificationsService.php
  src/Coupon/SyncerHooks.php
  src/HelperTraits/SyncTrait.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Product/SyncerHooks.php
  src/Settings/SyncerHooks.php
  src/Shipping/SyncerHooks.php
  tests/Unit/API/WP/NotificationsServiceTest.php
Labels: type: enhancement, changelog: add

#2794 Grant API auth before MC connect
  src/API/Google/Middleware.php
  src/API/WP/OAuthService.php
  src/ConnectionTest.php
  src/MerchantCenter/AccountService.php
  src/Options/MerchantAccountState.php
  tests/Tools/HelperTrait/GuzzleClientTrait.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
Labels: changelog: tweak

#2811 [API Pull Sync] Add Connection Test info and refactor error debugging
  src/API/WP/NotificationsService.php
  src/ConnectionTest.php
  src/Coupon/SyncerHooks.php
  src/HelperTraits/SyncTrait.php
  src/PluginHelper.php
  src/Product/SyncerHooks.php
  src/Settings/SyncerHooks.php
  src/Shipping/SyncerHooks.php
Labels: changelog: tweak

#2812 Update the API Pull feature for the Settings page
  js/src/components/app-notice/index.js
  js/src/components/app-notice/index.scss
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/enable-new-product-sync-notice.test.js
  js/src/components/google-account-card/authorize-wpcom-app-card.js
  js/src/components/google-account-card/connected-google-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-mc-account-card/merchant-center-account-info-card.js
  js/src/pages/settings/disconnect-modal/confirm-modal.js
  js/src/pages/settings/disconnect-modal/constants.js
  js/src/pages/settings/linked-accounts.js
  src/Tracking/README.md
  tests/e2e/specs/notifications/notifications-banner.test.js
  tests/e2e/utils/pages/settings.js
Labels: changelog: update

#2813 Avoid getting stuck in loading state when it fails to fetch WPCOM app auth URL during onboarding
  js/src/pages/onboarding/useAutoWPComAppAuthorization.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.test.js
Labels: changelog: dev

#2814 Add event tracking of how users process the WPCOM app authorization for the API Pull feature
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.test.js
  js/src/pages/onboarding/index.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.test.js
  js/src/pages/settings/index.js
  js/src/utils/tracks.js
  src/Tracking/README.md
Labels: type: enhancement, changelog: add

#2795 Fetch budget recommendations from the Google Ads API
  src/API/Google/BudgetRecommendations.php
  src/API/Google/Query/AdsCountryQuery.php
  src/API/Site/Controllers/Ads/BudgetRecommendationController.php
  src/Google/Ads/ServiceClientFactoryTrait.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Options/TransientsAwareInterface.php
  src/Options/TransientsAwareTrait.php
  src/Options/TransientsInterface.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Unit/API/Google/BudgetRecommendationsTest.php
  tests/Unit/API/Site/Controllers/Ads/BudgetRecommendationControllerTest.php
Labels: changelog: tweak

#2823 Restrict Budget Metrics to positive numbers
  src/API/Site/Controllers/Ads/BudgetMetricsController.php
  tests/Unit/API/Site/Controllers/Ads/BudgetMetricsControllerTest.php
Labels: changelog: tweak

#2819 Grant API Pull Access in Onboarding
  js/src/components/account-card/index.scss
  js/src/components/app-notice/index.js
  js/src/components/app-notice/index.scss
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/enable-new-product-sync-notice.test.js
  js/src/components/google-account-card/authorize-wpcom-app-card.js
  js/src/components/google-account-card/connected-google-account-card.js
  js/src/components/google-account-card/index.js
  js/src/components/google-account-card/useSwitchGoogleAccount.js
  js/src/components/google-combo-account-card/connect-google-combo-account-card.js
  js/src/components/google-combo-account-card/index.js
  js/src/components/google-combo-account-card/index.test.js
  js/src/components/google-mc-account-card/merchant-center-account-info-card.js
  js/src/css/shared/_woocommerce-admin.scss
  js/src/hooks/useGoogleMCAccount.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.js
  js/src/hooks/useUpdateRestAPIAuthorizeStatusByUrlQuery.test.js
  js/src/pages/onboarding/index.js
  js/src/pages/onboarding/setup-stepper/setup-accounts/index.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.js
  js/src/pages/onboarding/useAutoWPComAppAuthorization.test.js
  js/src/pages/settings/disconnect-modal/confirm-modal.js
  js/src/pages/settings/disconnect-modal/constants.js
  js/src/pages/settings/index.js
  js/src/pages/settings/linked-accounts.js
  js/src/utils/tracks.js
  src/API/Google/Middleware.php
  src/API/WP/OAuthService.php
  src/ConnectionTest.php
  src/MerchantCenter/AccountService.php
  src/MerchantCenter/MerchantCenterService.php
  src/Options/MerchantAccountState.php
  src/Tracking/README.md
  tests/Tools/HelperTrait/GuzzleClientTrait.php
  tests/Unit/API/Google/MiddlewareTest.php
  tests/Unit/MerchantCenter/AccountServiceTest.php
  tests/Unit/MerchantCenter/MerchantCenterServiceTest.php
  tests/e2e/specs/notifications/notifications-banner.test.js
  tests/e2e/specs/onboarding/step-1-accounts.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/onboarding/step-1-set-up-accounts.js
  tests/e2e/utils/pages/settings.js
Labels: changelog: none
