Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-09, with the labels that each got.

#3074 Rename the log file to match the new product name
  src/Logging/DebugLogger.php
Labels: changelog: tweak

#3076 Adjust the value of Merchant Center in the `/settings/google-for-woocommerce` WPCOMProxy endpoint to return null before completing onboarding
  src/Integration/WPCOMProxy.md
  src/Integration/WPCOMProxy.php
  src/Internal/DependencyManagement/IntegrationServiceProvider.php
  tests/Unit/Integration/WPCOMProxyTest.php
Labels: changelog: tweak

#3049 Fix typos
  .github/workflows/php-unit-tests.yml
  changelog.txt
  js/src/components/different-currency-notice.js
  js/src/components/external/woocommerce/filter-picker/index.js
  js/src/components/free-listings/choose-audience-section/choose-audience-section.js
  js/src/components/free-listings/configure-product-listings/shipping-time-setup/countries-time-input/edit-time-modal.js
  js/src/components/free-listings/configure-product-listings/shipping-time-setup/shipping-countries-form.js
  js/src/components/order-value-condition-section/minimum-order-card/calculateValueFromGroupChange.js
  js/src/components/order-value-condition-section/minimum-order-card/minimum-order-card.test.js
  js/src/data/actions.js
  js/src/data/adapters.js
  js/src/data/selectors.js
  js/src/data/test/utils.test.js
  js/src/hooks/useMCProductStatistics.js
  js/src/hooks/useMappingAttributesSources.js
  js/src/pages/dashboard/app-date-range-filter-picker/index.js
  js/src/pages/dashboard/campaign-creation-success-guide/index.js
  js/src/pages/dashboard/summary-section/performance-card.js
  js/src/pages/dashboard/summary-section/summary-card.js
  js/src/pages/reports/compare-table-card.js
  js/src/pages/reports/products/compare-products-table-card.js
  js/src/pages/reports/programs/campaign-name-cell.js
  js/src/pages/reports/programs/compare-programs-table-card.js
  js/src/pages/reports/programs/filterConfig.test.js
  js/src/pages/reports/utils.js
  js/src/pages/shipping/hasUnsavedShippingRates.js
  js/src/pages/shipping/hasUnsavedShippingRates.test.js
  js/src/pages/shipping/index.js
  js/src/utils/getDifferentShippingRates.test.js
  js/src/utils/getDifferentShippingTimes.test.js
  js/src/utils/tracks.test.js
  src/API/Site/Controllers/TourController.php
  src/API/WP/OAuthService.php
  src/Admin/ProductBlocksService.php
  src/Ads/AssetSuggestionsService.php
  src/Coupon/CouponHelper.php
  src/Notes/AbstractNote.php
  src/PluginHelper.php
  src/Product/WCProductAdapter.php
  tests/Tools/HelperTrait/GoogleAdsClientTrait.php
  tests/Tools/HelperTrait/MerchantTrait.php
  tests/Unit/API/Google/AdsAssetGroupAssetTest.php
  tests/Unit/API/Google/AdsReportTest.php
  tests/Unit/API/Google/SiteVerificationTest.php
  tests/Unit/API/Site/Controllers/MerchantCenter/ShippingTimeControllerTest.php
  tests/Unit/Jobs/MigrateGTINTest.php
  tests/Unit/Utility/AddressUtilityTest.php
  tests/e2e/config/playwright.config.js
  tests/e2e/specs/price-benchmark/price-benchmark-suggestions.test.js
  tests/e2e/utils/mock-requests.js
Labels: changelog: dev

#3068 Update NPM packages with security issues
  .stylelintrc.json
  jest.config.js
  js/src/components/tree-select-control/index.scss
  js/src/css/abstracts/_breakpoints.scss
  js/src/css/abstracts/_colors.scss
  js/src/css/abstracts/_mixins.scss
  js/src/css/abstracts/_variables.scss
  js/src/pages/dashboard/summary-section/summary-card.scss
  js/src/pages/get-started/get-started-with-hero-card/index.scss
  js/src/pages/onboarding/setup-stepper/skip-paid-ads-confirmation-modal/survey-modal.scss
  js/src/pages/product-feed/submission-success-guide/index.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: changelog: dev

#3079 Use `isGoogleAdsReady` to check for connected Ads account
  js/src/components/experience-rating-banner/index.js
  js/src/components/pmax-improve-assets-banner/index.js
  js/src/components/pmax-improve-assets-banner/index.test.js
  tests/e2e/utils/app-ratings-overview.js
Labels: type: bug, changelog: fix

#3105 Fix: trying to access non-existent metric property.
  js/src/components/paid-ads/campaign-assets-form.js
Labels: type: bug, changelog: fix
