Repository woocommerce/google-listings-and-ads, pull requests merged in 2025-07, with the labels that each got.

#2971 Add AssetGroupEditor component
  js/src/components/paid-ads/asset-group/asset-group-card.js
  js/src/components/paid-ads/asset-group/asset-group-editor/add-asset-item-button.js
  js/src/components/paid-ads/asset-group/asset-group-editor/add-asset-item-button.scss
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-field.js
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-field.scss
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-field.test.js
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-group-editor.js
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-group-editor.scss
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-group-images-section.js
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-group-text-section.js
  js/src/components/paid-ads/asset-group/asset-group-editor/asset-group-videos-section.js
  js/src/components/paid-ads/asset-group/asset-group-editor/images-selector.js
  js/src/components/paid-ads/asset-group/asset-group-editor/images-selector.scss
  js/src/components/paid-ads/asset-group/asset-group-editor/images-selector.test.js
  js/src/components/paid-ads/asset-group/asset-group-editor/index.js
  js/src/components/paid-ads/asset-group/asset-group-editor/texts-editor.js
  js/src/components/paid-ads/asset-group/asset-group-editor/texts-editor.scss
  js/src/components/paid-ads/asset-group/asset-group-editor/texts-editor.test.js
  js/src/components/paid-ads/asset-group/asset-group-header/asset-group-header.js
  js/src/components/paid-ads/asset-group/asset-group-header/asset-group-header.test.js
  js/src/components/paid-ads/asset-group/asset-group-header/assets-loader.js
  js/src/components/paid-ads/asset-group/asset-group-header/assets-loader.scss
  js/src/components/paid-ads/asset-group/asset-group-header/final-url-card.js
  js/src/components/paid-ads/asset-group/asset-group-header/final-url-card.scss
  js/src/components/paid-ads/asset-group/asset-group-header/index.js
  js/src/components/paid-ads/asset-group/asset-group-section.scss
  js/src/components/paid-ads/asset-group/asset-group.js
  js/src/components/paid-ads/asset-group/asset-group.scss
Labels: type: enhancement, changelog: none

#2980 REST API endpoint to show Ads recommendations
  src/API/Site/Controllers/Ads/RecommendationsController.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  tests/Unit/API/Site/Controllers/Ads/RecommendationsControllerTest.php
Labels: type: enhancement, changelog: none

#2991 Fetch recommendations to improve PMax campaigns assets
  src/API/Google/Query/AdsRecommendationsQuery.php
  src/API/Site/Controllers/Ads/RecommendationsController.php
  src/Ads/AdsRecommendationsService.php
  src/DB/Query/AdsRecommendationsQuery.php
  src/DB/Table/AdsRecommendationsTable.php
  src/DB/TableManager.php
  src/Internal/DependencyManagement/CoreServiceProvider.php
  src/Internal/DependencyManagement/DBServiceProvider.php
  src/Internal/DependencyManagement/GoogleServiceProvider.php
  src/Internal/DependencyManagement/JobServiceProvider.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Jobs/UpdateAdsRecommendations.php
  tests/Unit/API/Site/Controllers/Ads/RecommendationsControllerTest.php
  tests/Unit/DB/Table/AdsRecommendationsTableTest.php
  tests/Unit/Jobs/UpdateAdsRecommendationsTest.php
  tests/proxy/handler.js
  tests/proxy/mocks/ads/recommendations/results.json
Labels: type: enhancement, changelog: none

#3001 Display notification badge in the admin menu when there are recommendations
  js/src/notification-manager/index.js
  src/Internal/DependencyManagement/AdminServiceProvider.php
  src/Menu/Dashboard.php
  src/Menu/NotificationManager.php
  tests/e2e/specs/dashboard/notification-badge.test.js
  tests/e2e/test-snippets/test-snippets.php
Labels: changelog: update

#3005 Hide EC Card When Ads Account is Not Connected
  js/src/pages/settings/enhanced-conversions/setup-enhanced-conversions.js
  js/src/pages/settings/enhanced-conversions/useEnableEnhancedConversions.js
  tests/e2e/specs/settings/settings.test.js
Labels: type: bug, changelog: fix

#3013 Clean up for the API Pull integration
  js/src/components/enable-new-product-sync-button.js
  js/src/components/enable-new-product-sync-notice.js
  js/src/components/enable-new-product-sync-notice.test.js
  src/Tracking/README.md
  tests/e2e/specs/notifications/notifications-banner.test.js
  tests/e2e/specs/settings/settings-wpcom-rest-api.test.js
  tests/e2e/utils/pages/settings.js
Labels: changelog: dev

#3012 Fix image preview aspect ratio
  js/src/components/paid-ads/asset-group/asset-group-editor/media-selector.js
  js/src/components/paid-ads/asset-group/asset-group-editor/media-selector.scss
  js/src/components/paid-ads/gen-ai-card.js
  js/src/components/paid-ads/gen-ai-card.scss
Labels: type: enhancement, changelog: add

#3018 Ensure EC settings defaults to false
  src/API/Site/Controllers/Ads/AdsSettingsController.php
  tests/Unit/API/Site/Controllers/Ads/AdsSettingsControllerTest.php
Labels: changelog: update

#3028 Fix: property name for user preference.
  js/src/components/pmax-improve-assets-banner/index.js
Labels: type: bug, changelog: fix

#2992 Add support for Enhanced Conversions
  js/src/components/external/wordpress/guide/index.js
  js/src/data/action-types.js
  js/src/data/actions.js
  js/src/data/reducer.js
  js/src/data/resolvers.js
  js/src/data/selectors.js
  js/src/data/test/reducer.test.js
  js/src/pages/product-feed/submission-success-guide/index.js
  js/src/pages/settings/enhanced-conversions/index.js
  js/src/pages/settings/enhanced-conversions/setup-enhanced-conversions.js
  js/src/pages/settings/enhanced-conversions/useEnableEnhancedConversions.js
  js/src/pages/settings/index.js
  js/src/pages/settings/setup-tax-rate/setup-tax-rate.js
  js/src/pages/settings/setup-tax-rate/tax-rate.js
  src/API/Site/Controllers/Ads/AdsSettingsController.php
  src/Ads/AccountService.php
  src/Google/GlobalSiteTag.php
  src/Internal/DependencyManagement/RESTServiceProvider.php
  src/Options/OptionsInterface.php
  src/Proxies/WC.php
  tests/Unit/API/Site/Controllers/Ads/AdsSettingsControllerTest.php
  tests/Unit/Ads/AccountServiceTest.php
  tests/Unit/Google/GlobalSiteTagTest.php
  tests/e2e/specs/onboarding/step-3-complete-campaign.test.js
  tests/e2e/specs/settings/settings.test.js
  tests/e2e/utils/mock-requests.js
  tests/e2e/utils/pages/settings.js
Labels: type: enhancement, changelog: add

#3029 Display a more detailed error message when failing to link Google Ads account
  js/src/components/google-ads-account-card/connect-ads/index.js
  js/src/components/google-combo-account-card/connect-ads/connect-existing-account.js
  js/src/tests/jest-unit.setup.js
  js/src/utils/console.js
  js/src/utils/handleError.js
  js/src/utils/handleError.test.js
Labels: changelog: tweak
